### ISSUE TITLE
Binary FBX Export

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/AssetStudio#104]
Blender cant import ASCII FBX, so converting the FBX to binary produces mangled models like this:
![](https://cdn.discordapp.com/attachments/300619803188789259/368484913122377728/unknown.png)

**Comment by Stellarspace** [comment]
This issue has nothing to do with Unity Studio.

**Comment by MichaelPriebe** [comment]
It was not an issue really, a suggestion to add binary fbx export. But yes, the mangled models may or may not be a unity studio, rather a blender or fbx converter issue, which could be alleviated through adding a binary fbx export.

**Comment by Stellarspace** [comment]
@MichaelPriebe Great suggestion!

**Comment by KekMcGee** [comment]
You can always just use http://richwhitehouse.com/index.php?content=inc_projects.php to convert to dae/Binaryfbx and many other formats.

**Comment by JuGGerNaunT** [comment]
This mangling happens because of incorrect skin processing in UnityStudio. By default, UnityStudio applying that every vertex has 4 bone influences. But that is almost always not true. Compressed mesh could contains 2200 vertices, 1900 bones influences and 1850 bones weights, so there is no definite correspondence between them. This algorithm should be improved in order to correctly export fbx.

**Comment by MichaelPriebe** [comment]
⬆️ This guy knows his stuff @Perfare

**Comment by Perfare** [comment]
@MichaelPriebe I don't have any knowledge of the 3D model, even if someone tells me where the problem is, I can't do anything.

**Comment by ngovandang** [comment]
@Perfare :-( I hope there is someone will help you on 3D model. Its needed for Unity Studio

**Comment by JuGGerNaunT** [comment]
My implementation of AssetBundle handler has correct skin processing, but it hasn't released yet. I'm going to publish  it within a few weeks.

**Comment by carpedee** [comment]
> My implementation of AssetBundle handler has correct skin processing, but it hasn't released yet. I'm going to publish it within a few weeks.
I'm really looking forward to it. Because of what you mentioned, the fbx obtained — while losslessly exported in a Unity environement point of view — are almost unusable elsewhere

**Comment by JuGGerNaunT** [comment]
Ok, I wasn't quite correct. Skin still has incorrect bone index influence issue. But at least visually it is looking good. I am working on improvement. If I wont find the solution for this problem, I release my current work as pull request for this repo.

**Comment by carpedee** [comment]
It does sound promising.

**Comment by mafaca** [comment]
I'va made pull request with correct skin reading. Other issue still actual. I hope someone who had worked with something similar can solve this problem: when UnityStudio export FBX it changes quaternion rotations to euler, but beside that it also make some math tricks to convert rotation from unity's world space to 3DSMax(?) world space. So, after those transofrms final euler rotation values dont directly correspond to initial quaternion values. But when Unity import that FBX, it convert those value back to inner format, so rotation value look fine. But!
Skinned mesh renderer read values from transformation matrices, not from euler value list. Unity Studio export FBX with fixes matrices. Transformation look like this:
ob.AppendFormat("{0},{1},{2},{3},", m[0, 0], -m[1, 0], -m[2, 0], -m[3, 0]);
ob.AppendFormat("{0},{1},{2},{3},", -m[0, 1], m[1, 1], m[2, 1], m[3, 1]);
ob.AppendFormat("{0},{1},{2},{3},", -m[0, 2], m[1, 2], m[2, 2], m[3, 2]);
ob.AppendFormat("{0},{1},{2},{3}", -m[0, 3], m[1, 3], m[2, 3], m[3, 3]);0},
It is just changing some signes. And it is work for transform which has uniform (like Vector3(1, 1, 1) or Vector3(2, 2, 2)) scale value. But for non uniform scale those sign transformations are not enough. It is required some more transformation to correctly export such matrices.
I tried much cases, but non or them work for me. So i hope someone can figure it out how correctly export those matrices.

**Comment by mafaca** [comment]
Those matrices are bind poses for skinned mesh renderer.

**Comment by Perfare** [comment]
Just the problem described by the title, AS now supports, but for other problem I suggest opening a new issue.
