### ISSUE TITLE
Vertex Colors Broken when exporting FBX from Scene Hierarchy.

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/AssetStudio#116]
https://mega.nz/#!9xYm0SZA!a1m4cMv8p_189hWO2Tt3guIDZXBqfBOFjIEAptkxRhQ

"MetaToyHappy"

Left how it should look, Right Broken colors.
https://i.imgur.com/RmRsjAr.png

**Comment by mafaca** [comment]
This https://imgur.com/a/jmk2o how it is look like in Blender

**Comment by Perfare** [comment]
After checking, the export of this file is normal.
