### ISSUE TITLE
Black area on Normal Maps

### ISSUE THREAD

**Issue by mhoangvslev** [Perfare/AssetStudio#117]
@Perfare, I encountered this problem with the normal map.
The problem came from the normal maps: The red channel lacks information ( in the normal map file it's pure white).

This is what it looks like on UE4:
![image](https://user-images.githubusercontent.com/19567683/32914291-578f44c4-cb15-11e7-9b26-661a669d76c8.png)

Here is the exported normal map:

![character_de_atlas_nrm](https://user-images.githubusercontent.com/19567683/32994647-8cfcef56-cd6a-11e7-8f07-0469c4f57089.jpeg)

**Comment by mhoangvslev** [comment]
@Perfare I found the solution: greyscale the normal map. Would you consider add this as an option?

**Comment by mhoangvslev** [comment]
@Perfare Anyone?

**Comment by WACOMalt** [comment]
Would really appreciate the greyscale option. This gets very tedius to fix when you have 1000s of files.

**Comment by WACOMalt** [comment]
I found the fix for me was making a Photoshop action to move the channels around to the correct order. Still took about an hour to process them all.

**Comment by mhoangvslev** [comment]
If possible, please describe the procedures, so the author may use to build an algorithm :)
