### ISSUE TITLE
Odd Mesh Deformation

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/AssetStudio#125]
Bowser's model from Super Mario Run when exported has a caved in nose, but when exported from the asset list It's fine. https://i.imgur.com/vStsO4P.png

https://mega.nz/#!4tAniLxK!JAXis2hZx3_GXSZVE0scM3-JVo3829ZOnMEQ9E3Inr4

**Comment by Perfare** [comment]
I think the new export function has fixed this problem.
