### ISSUE TITLE
Normals of FBX Model Exported from Unity Studio break.

### ISSUE THREAD

**Issue by Escope12** [Perfare/AssetStudio#139]
Whenever I export a model as FBX from Unity Studio with Normals and I import the model into 3ds max, the normal break.
![3dsmax_2018-01-21_20-56-38](https://user-images.githubusercontent.com/8963276/35202012-cad79b28-feed-11e7-9e20-8d0628bf8693.png)

**Comment by Perfare** [comment]
As mafaca said, this problem may be because 3D model program can't read Normals from fbx file or something like that.
But if you provide file, I will check them.

**Comment by Escope12** [comment]
@Perfare Would this file do? Its FBX.
[Butterfly.zip](https://github.com/Perfare/AssetStudio/files/2234221/Butterfly.zip)
