### ISSUE TITLE
Over 2GB asset bundle(MemoryStream limitation 2G)

### ISSUE THREAD

**Issue by OkazakiNaoki** [Perfare/AssetStudio#149]
BundleFile.cs
line 207 System.IO.IOException: '資料流太長。'

Well I think it's an over 2GB bundle...
Some people said use FileStream instead. Maybe like the method UABE used?(save the decompressed then read)
But you know UnityStudio's hierarchy export 3d model function is too convenient.
Would you fix the size problem? Thanks.

**Comment by Perfare** [comment]
You can use UABE to decompress it for the time being, UnityStudio support load Over 2GB assets file.
Fixing this problem is already in my plan.

**Comment by OkazakiNaoki** [comment]
Still need transform information which from prefab.
I would say UABE and UnityStudio both got some benefit.
Not one can replace each other.
Wait for your news, thanks again.

**Comment by Perfare** [comment]
Can you provide file ? It would be more easier for me to write code.
