### ISSUE TITLE
Unable to rip Animations/Misssing x64 version to rip animations

### ISSUE THREAD

**Issue by RamChupi** [Perfare/AssetStudio#157]
So,i've been trying to rip animations from the game Bendy and the Ink Machine,but i'm stuck at some of them.Biggest issue is that one of the files needed is a Streaming Assets file (which i'll call CH 3 ),a file that i've only managed to open with the x64 version from this version https://github.com/Perfare/UnityStudio .The linked version can't actually rip animations,and i've been struggling to try to build a x64 version of this one too,mostly cuz of the SlimDX and SB3Utility dlls,that won't work cuz they don't have x64 compatibility.It's only for this one CH 3 file too,since the x86 version can open the other Streaming Asset file (which i'll call CH 2) just fine,but it crashes when i try the CH 3 file.Any possible way to fix this?I've tried many many things but i've been unable to compile a working x64 version only cuz of those dlls.

**Comment by RamChupi** [comment]
Also,sorry if it's a little vague or weird around some parts,i'm not too good with describing things.

**Comment by Perfare** [comment]
The 64 bit needs to recompile a DLL file, I didn't intend to spend time to compile before the animation export was complete.
But recently I'm going to merge animation branch into master, there will have 64 bit versions at the time of completion

**Comment by RamChupi** [comment]
Oh nice to know

**Comment by Perfare** [comment]
Export animation has been merged to master branch
