### ISSUE TITLE
Rigging not exported & some broken on export

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/AssetStudio#16]
https://mega.nz/#!484A0TgA!-tnJS0YUSV8THoIofTzu14NTSNrIEqY-KC8UD6jJqUw

CAB-45ee4a4122620970a23401d8c8788675 Rigging not exported

CAB-a78ab9dae3eb4ad290c4a6a3848134ec Broken on export

from AdventureQuest 3D unity version 5.4.2F2

**Comment by Perfare** [comment]
Sorry, I lack of 3d model knowledge. 
I don't know whether I can fix this

**Comment by KekMcGee** [comment]
Ah, alright, that's fine then. Appreciate all you've done already.

**Comment by Perfare** [comment]
I think the new export function can handle these files normally.
