### ISSUE TITLE
Only AnimationClip

### ISSUE THREAD

**Issue by mhoangvslev** [Perfare/AssetStudio#163]
I am using this on a game called Verdun. I can export everything, except:
- FBX export meshes with skeleton
- AnimationClip but don't know what to do with it.

**Comment by RamChupi** [comment]
For FBX exports with skeletons,you gotta export from the Scene Hierarchy,while for 1 AnimationClip you have to also select the Animator used for that animation.

**Comment by lantiszhu** [comment]
@RamChupi how to export from the Scene Hierarchy?

**Comment by RamChupi** [comment]
@lantiszhu Pretty simple,select what you want then just press export selected 3D model.
