### ISSUE TITLE
Importing FBX in to 3D max issues

### ISSUE THREAD

**Issue by rodeo7** [Perfare/AssetStudio#164]
I am getting these errors when I try to import any FBX file I have extracted.

The following parent and/or ancestor node(s) is/are not part of the BindPose definition.
    -_PitcrewMech01:Root_Node
    -Pitcrew02_:Root_Node

Am I doing something wrong or is it just not exporting properly?
What is my next step to help? Provide the original Unity file I am trying to get the animation scene from?

**Comment by rodeo7** [comment]
Link to original file
https://www.dropbox.com/s/heb0kt1lu81r32g/pitanim.rab?dl=0

**Comment by rodeo7** [comment]
ok I finally got the Animations to import to 3d Max 2012. I am seeing some strange things like Limbs not acting normal......a leg will kick up over a head or an arm will fling all over for a frame and then go back. Is this just due to the animation extraction not being finalized? and what is the easiest way to fix these single frames so it looks more natural? bare with me I am using this to learn so a newbie of sorts with animation stuff.

**Comment by mafaca** [comment]
It's happens because Unity works with Quaternions but FBX requires Euler angles. For quaternion, transition from -170° to 170° mean that this 170° have to be translated as -190° for Euler. But currently it doesn't happens. If you are familiar with programming you can fix it yourself. [Here](https://gist.github.com/mafaca/c2ef018d698ba0d36dd7c28f7a47fbc5) is conversion code.

**Comment by Perfare** [comment]
Enable "EulerFilter" in export options will fix this problem
This option exists in Animation.v0.9.0.0.Beta version
Download from here https://pan.baidu.com/s/1KmeRhuvI2pL86pOO3l8DUQ#list/path=%2F

**Comment by rodeo7** [comment]
Cool will try and let you know how it does! Appreciate it.

**Comment by Perfare** [comment]
Export animation has been merged to master branch
I think the problem should have been solved.

**Comment by rodeo7** [comment]
I worked great thank you!
