### ISSUE TITLE
Models not exporting correctly?

### ISSUE THREAD

**Issue by toonjoey** [Perfare/AssetStudio#168]
I'm not sure what I'm doing wrong here but it seems like the models for a certain game wont export properly.
This is how the model should look:
![image](https://user-images.githubusercontent.com/19507339/38392647-3e022162-38f6-11e8-8bf0-107a4e312d8c.png)
Yet it ends up as this:
![image](https://user-images.githubusercontent.com/19507339/38392679-5c017c44-38f6-11e8-8550-e07fb6a35023.png)

Any reason for this? For reference I'm trying to extract some models from here: https://github.com/K1999/Toontown-2.0

**Comment by RamChupi** [comment]
You gotta set bind pose,things like that happen usually to me and just setting the bind pose helps.

**Comment by toonjoey** [comment]
Not sure how I'd do that (new to Maya).

**Comment by RamChupi** [comment]
https://www.youtube.com/watch?v=wUuyQ8mZdgU This could help

**Comment by toonjoey** [comment]
Wait, how would you extract the rig for a model if you can?

**Comment by RamChupi** [comment]
Exporting using the scene hierarchy should help

**Comment by toonjoey** [comment]
The thing is all the models I've wanted to extract are unused and don't seem to be extractable using the scene hierarchy. I may be wrong though.

**Comment by toonjoey** [comment]
Ok so I did some research using a small Unity engine (Thanks, Bumper Engine) and it turns out the models don't export correctly.

**Comment by toonjoey** [comment]
"If I can do it, then why can't you?"

Probably because I'm **basically completely new to Unity and Maya in general** and I have no idea how to rip them properly?

**Comment by Perfare** [comment]
I don't know what problem you are having, I tested all the files are working fine.

**Comment by toonjoey** [comment]
![image](https://user-images.githubusercontent.com/19507339/39227162-14cc00ea-4825-11e8-8359-aa6bb04def54.png)
I got the models in but the rig doesnt seem to function correctly sadly.

**Comment by Stellarspace** [comment]
@toonjoey The 3D models were rigged in Unity, not Maya.
