### ISSUE TITLE
Animation Export

### ISSUE THREAD

**Issue by mhoangvslev** [Perfare/AssetStudio#173]
When I export the Animator with many of its AnimationClip, the program crashes.
Below is the result of debugging session

```
System.IO.FileLoadException
  HResult=0x8007007F
  Message=A procedure imported by 'AssetStudioFBX.dll' could not be loaded.
  Source=AssetStudio
  StackTrace:
   at AssetStudio.Exporter.ExportAnimator(AssetPreloadData animator, List`1 animations, String exportPath) in D:\Workshops\AssetStudio\AssetStudio\StudioClasses\Exporter.cs:line 352
   at AssetStudio.AssetStudioForm.<>c__DisplayClass111_1.<ExportAnimatorwithAnimationClip_Click>b__0(Object state) in D:\Workshops\AssetStudio\AssetStudio\AssetStudioForm.cs:line 1902
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.QueueUserWorkItemCallback.System.Threading.IThreadPoolWorkItem.ExecuteWorkItem()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()

```
![image](https://user-images.githubusercontent.com/19567683/38453528-69eb3bd0-3a57-11e8-9cc6-8aa48a84d6c4.png)

You can find the sample file [here](https://mega.nz/#!J5hEQJDY!9ASxqFgXhOZEQLtVc84ZADu9zmWlMhJKYGJv6YgDz-w)

**Note:**
I use FBX SDK 2019.0

**Comment by Perfare** [comment]
Before building, you need to modify the proj file, change 'IncludeDirectories' and 'LibraryDirectories' to point to your own FBX SDK.
To be able to load dll, you need to install the corresponding version of Visual C++ Redistributable
According to your pull, you need to install Visual C++ 2015 Redistributable and Visual C++ 2017 Redistributable
In addition, I will not accept your pull, change PlatformToolset to v141 version means users need to install Visual C++ 2017 Redistributable, this is not a good choice, you can modify these in your own project.

**Comment by mhoangvslev** [comment]
Thank you for you reply.
I made changes accordingly:
- Uninstall Visual C++ 2017 Redistributable and install Visual C++ 2015 Redistributable
- Install on top Build Tools v140 (VS 2015)

The problem persists

**Comment by Perfare** [comment]
Sorry, there's something to forget to say, AssetStudioFBX.dll using FBX SDK 2015, If you use other versions of the FBX SDK, you need to replace 'AssetStudio\Library\x64 or \x86\libfbxsdk.dll' to your own FBX SDK, it should be this reason.

**Comment by mhoangvslev** [comment]
It works! Many thanks. Would you consider adding bulk export (one animator and selected AnimationClip)?

**Comment by Perfare** [comment]
'Export Animator with AnimationClip' is export selected one animator with selected AnimationClips

**Comment by mhoangvslev** [comment]
In my case, the output contains only the first selected animation

**Comment by Perfare** [comment]
It's impossible, 'animationList' will contain all you selected animations and export them

**Comment by mhoangvslev** [comment]
![image](https://user-images.githubusercontent.com/19567683/38460746-4af9df24-3ac0-11e8-99b8-480544f841a5.png)
 I selected using Ctrl + LMB, the output is one animator with 1 animation in it. Did I miss something?

**Comment by Perfare** [comment]
I think this problem may be due to you import program incompatibility of the fbx file

**Comment by mhoangvslev** [comment]
I am confused, I use
- Autodesk Maya 2018
- FBX SDK 2019

**Comment by Perfare** [comment]
I don't know why you happen, I can only confirm that this function has no problem.
![qq 20180409012824](https://user-images.githubusercontent.com/12952226/38470442-963b66f8-3b95-11e8-83c5-e5d40e5ff1a6.png)

**Comment by JuGGerNaunT** [comment]
Neither Maya nor Max support multiple animations for single FBX file.

**Comment by mhoangvslev** [comment]
Could @Perfare take into consideration this limit. I am convinced that it would be more helpful to have one fbx per animation. While waiting, Blender js rhe only work around?
