### ISSUE TITLE
About CubeMap

### ISSUE THREAD

**Issue by backjy** [Perfare/AssetStudio#174]
什么时候会添加cubemap 的导出支持呢?

**Comment by Perfare** [comment]
不太清楚你想要cubemap以什么形式导出

**Comment by muninger** [comment]
图片导出啊

**Comment by muninger** [comment]
导出的cubemap数据是.dat，这个文件怎么用才能变成cubemap

**Comment by Stellarspace** [comment]
@backjy Please close this issue if it has been resolved.
