### ISSUE TITLE
File with UnityFS header

### ISSUE THREAD

**Issue by thaipokecard** [Perfare/AssetStudio#176]
I have files with UnityFS header (the first word when I open them in text editor). The files do not have file extension. I load one file and it has 1 exportable asset so I export fbx file. The fbx file says that it does not see any texture2D. I try dragging this file to another software (devxunity demo version) and it gives me texture2D that can be saved as PNG. I wonder if I am using Unity Studio correctly. I can provide the files if necessary.

**Comment by Perfare** [comment]
You should upload a file or I can't help you

**Comment by thaipokecard** [comment]
Thank you for your reply. I upload some of them to google drive.

https://drive.google.com/drive/folders/1h4w0Rh6XCyuJd6k_nhFm8IzzUtgN0AXm?usp=sharing

**Comment by Perfare** [comment]
I don't know what's wrong with you. I tested all the files you provided and worked fine.

**Comment by thaipokecard** [comment]
Oh I forgot to check "Display all assets." I get it now. I apologize for taking your time with my simple mistake.
