### ISSUE TITLE
Export All 3D Objects (Split) into separate folders

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#178]
Is it possible to add a feature to 'Export All 3D Objects (Split)' into separate folders?

'Export All 3D Objects (Split)' function works pretty well but can it be done into separate folders for each model along with its owned textures?

Right now this function produces a single folder with all the models inside and a single Texture2D folder with all related textures.

**Comment by Perfare** [comment]
Now will export to separate folders named by node
