### ISSUE TITLE
Name exported file by Node name on 'Export selected objects'

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#179]
Is it possible to use Node name for exported FBX filename?
Right now current time stamp is used for exported FBX filename but I don't see any reason to do that — using Node name would makes much more sence.

**Comment by Perfare** [comment]
The logic of the code is that you can choose any node you want to export, so can't be sure which name to use
May need to add a right-click menu

**Comment by Tosyk** [comment]
Isn't it work the way 'Export all objects (Split)' function with naming by Node name?
I thought it's the same only it export selected nodes.

**Comment by Tosyk** [comment]
I understand. It seems architecture of the whole should be re-done to support this feature. thank you
