### ISSUE TITLE
Asset List RMB option to find parent Node in Scene Hierarchy

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#180]
Is it possible to add an 'Asset List' option under RMB to find bundle or parent Node in 'Scene Hierarchy'?
It's nice to sort and find things through 'Asset List' because it has a 'visual preview window' but all objects there are separated into pieces and I can export only specific object. For example racing game vehicles are separated into body, wheels and some other parts — it would be cool to jump from specific object of 'Asset List' into its parent Node in 'Scene Hierarchy' to export full model.

![1](https://user-images.githubusercontent.com/24209966/38920794-d5ed112a-42fc-11e8-9fea-69253d5b656d.jpg)

**Comment by Perfare** [comment]
Added, only supports mesh

**Comment by Tosyk** [comment]
works great, thanks!
