### ISSUE TITLE
Skeleton doesn't export correct

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#181]
Game 'CarX Drift Racing' Here: https://play.google.com/store/apps/details?id=com.CarXTech.CarXDriftRacingFull
Character in t-pose but skeleton doesn't correct.
Here's file with the character: [sharedassets2.zip](https://github.com/Perfare/AssetStudio/files/1923174/sharedassets2.zip)

**Comment by Perfare** [comment]
This file doesn't have full skeleton information so it can't be exported

**Comment by Tosyk** [comment]
Does it references somewhere?
I'm loading full folder of extracted bundles from OBB file and getting this incomplete skeleton.

**Comment by Perfare** [comment]
I checked the obb file to confirm that the model in this file does not contain skeleton information

**Comment by Tosyk** [comment]
that's wierd. well thanks for checking!
