### ISSUE TITLE
Problems during Compilation (Unable to make a build)

### ISSUE THREAD

**Issue by RamChupi** [Perfare/AssetStudio#182]
So i've been having many many problems trying to compile it (especifically this most recent version),such as the v140 error and missing "AssetStudioFBX.dll".Any way to fix these?I'd appreciate it also if someone could make me a x64 build.

**Comment by Perfare** [comment]
check https://github.com/Perfare/AssetStudio#build

**Comment by RamChupi** [comment]
Oh oki

**Comment by Perfare** [comment]
In addition, you can download the latest build version from here
[![Build status](https://ci.appveyor.com/api/projects/status/rnu7l90422pdewx4?svg=true)](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts)
It has been written on README.md
