### ISSUE TITLE
See resource type/preview in Scene Hierarchy

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#183]
When searching through _Scene Hierarchy_ it's not possible to understand which string is stand for what resource type. Is it possible to somehow see the type of resource or its preview in the preview window from _Scene Hierarchy_?
Right now _Scene Hierarchy_ can show only shader/script code but not the others, though _Asset List_ can show all of the resource types.

**Comment by Tosyk** [comment]
and any of this diagram string can be converted into _FBX with textures_ only by default?

**Comment by Perfare** [comment]
I can't understand what you mean

**Comment by Perfare** [comment]
I still don't know what you really want, but I can tell you that it is impossible to preview the resources on the Scene Hierarchy, GameObject does not have any direct contact with other resources such as Texture2D
