### ISSUE TITLE
Issue when exporting AnimationClips (Bones mixed around different rigs)

### ISSUE THREAD

**Issue by RamChupi** [Perfare/AssetStudio#189]
So i've been having this problem where i export an animation clip and the rig i want comes all stretched due to a problem where it's bones get mixed with other rigs.Basically  there's 5 characters (Boris,Allison,Tom,Alice,Searcher),i want Allison,then i select it's animation clips and export it as a file.When i open it,there's Alisson and all the other 4 characters in the file,with Alisson's bones being mixed around rigs which are in different positions,such as her arms in Boris' rig.Any way to fix this?I've tried turning things like EulerFilter off and on,but it happens every time i try.It's also not with one character alone,but every other character.I've also tried the "Export selected objects with AnimationClip",same problem.

**Comment by Perfare** [comment]
Try the latest build version, if the problem is not resolved, please upload the file to me
