### ISSUE TITLE
Error when exporting Model with AnimationClips

### ISSUE THREAD

**Issue by Pwrest** [Perfare/AssetStudio#191]
When i try to export model with AnimationClips give error [Error Here](https://imgur.com/6lGBgNh).
[File Here](https://drive.google.com/open?id=1Ei54yaoMtvgLu8k8WuKQVzmGyTuIlDTQ).

**Comment by Springtraph** [comment]
I get it too on paladins strike for android, but hey, we got animationclips semi-working!
Lets see if perfare can fix this.

**Comment by Perfare** [comment]
Now new features are temporarily unable to handle too old versions of mesh, however, AnimationClips can be exported normally and the errors in the images have been fixed.
