### ISSUE TITLE
Transparent model when exporting animationclip

### ISSUE THREAD

**Issue by Springtraph** [Perfare/AssetStudio#192]
When i export Animationclip, it works! but the model is transparent (also model looks kinda deformed but thats OK).
[Here is the model exported with animationclip](https://resmim.net/f/yZABAU.png)
[And here is the model that contains all sub files (shaders, animationclips, etc)](https://resmim.net/f/Y1NqF2.png)

**Comment by Perfare** [comment]
You should put all assets files in a folder, then use the load file to read globalgamemanager or use the load folder to read the folder.

**Comment by Springtraph** [comment]
As you can see at the folder structure, there are only entries that are related to the model. I loaded entire game folder, get the one animator that contains all entries for that model, reopen that only one animator to load files related to that model.
And result is this.

**Comment by Perfare** [comment]
Use other software to load the model, my test result is not encountered this problem

**Comment by Springtraph** [comment]
Shall I upload the sample files?
The second result is what confuses me.

**Comment by Springtraph** [comment]
[Here is the link](https://drive.google.com/file/d/1N4VjYEVV3q3H7ClRvQk_VnVBaC3TqsuK/view?usp=sharing)
Thanks for your support.

**Comment by Perfare** [comment]
I did not encounter any problems, so I think you need to use other software to load fbx file

**Comment by Springtraph** [comment]
Thanks, may i ask which software you used and how did you export correct model with animations?

**Comment by Perfare** [comment]
I think a lot of 3d software like 3ds Max or Maya can load fbx file correctly
Just export animator will contain all the animation

**Comment by Springtraph** [comment]
Sorry for taking your time, but [:)](https://resmim.net/f/EYo2Ml.png)
I exported animator and its still transparent even if i open it with 3ds max
