### ISSUE TITLE
Unable to load "crunchunity.dll"

### ISSUE THREAD

**Issue by HeresHavi** [Perfare/AssetStudio#193]
I'm getting this error when trying to open a Texture2D or whatever. I tried multiple games, happens on them all. I used AssetStudio.x64.v0.10.0.22 and it works. So there's something wrong in your latest build.

![error](https://user-images.githubusercontent.com/39027816/39674250-36f35f6a-5149-11e8-81d7-344e21b30a6c.png)

**Comment by Perfare** [comment]
Unity using new crunch library after 2017.3.
I just prepared the relevant code but did not upload the library.
Because there is still a lot of work to do, it will not upload the library right away

**Comment by HeresHavi** [comment]
That's very good that you don't upload it immediately! I just thought I'd report it so you are aware ;)

**Comment by HeresHavi** [comment]
There is also something wrong with extracting Models. I'm not getting any logs regarding the crash so I can't provide much. It extracts the objects and after a while, the program closes.

**Comment by Perfare** [comment]
uploaded, other questions please create a new issue
