### ISSUE TITLE
Issues with animation clips when extracting

### ISSUE THREAD

**Issue by victti** [Perfare/AssetStudio#194]
I had 3 new errors:
https://imgur.com/a/l77HTdV

I can't send these files since as you can see, there are a lot of them.. But it shows the error to some files that don't have an animation (@TPose). If you want I can try to get the correct files and send here if you really need them to fix.

Btw thanks for fixing the others 2 errors, you helped me a lot!

**Comment by Perfare** [comment]
I can't solve any problems with pictures only

**Comment by victti** [comment]
https://drive.google.com/open?id=1IcFAe-6AzOYVy_WmkZh7P15K3G3ZA-CP

It has some of my files. Some of them extract normally but after few seconds it just gives me different erros

**Comment by victti** [comment]
The error only occurs when extracting all files when loaded all the folders at once.

**Comment by Perfare** [comment]
I verified that these files in the latest version and I don't get these errors. 
I noticed that you have out of memory problem, it is recommended not load too many files at once.
