### ISSUE TITLE
Can Unity Studio Open PS Vita Asset files?

### ISSUE THREAD

**Issue by Shinigami-Guntz** [Perfare/AssetStudio#196]
I have a assets file from Corpse Party: Blood drive but when i try to open it in unity studio it just tells me that it imported one file with 0 exportable ones (sometimes it will say there's one exportable object but there's nothing listed anywhere), and on the hiearchy it says it has no children,which i find hard to believe, the file is over 900+mb in size, i dont know if its just encryption or if its because its on the ps vita, i really need to export the characters with their rigs and so far this is the only program for unity files that can do so. and even if it says. there arent any shared assets in the folder from the looks of it, only other thing is a .resS file, and a psarc file which may contain the rest of the asset files if there are more than just the one i have access too. https://drive.google.com/file/d/1oosEEWrxAlYisRw04hk_U3hi84tT6nsf/view
![image](https://user-images.githubusercontent.com/39101703/39781590-32562162-52d5-11e8-9e2f-dadc29652f63.png)

**Comment by sdbds** [comment]
yes，i tried.

**Comment by Perfare** [comment]
This file is not a valid Unity file, may be encrypted.
