### ISSUE TITLE
Exporting models exports the whole world many times over.

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/AssetStudio#199]
Thought I made an issue for this a long time ago. Here it is again:

![](https://i.imgur.com/N5Ri9ab.png)

I want to export the world, so I select the tree with all the models, instead it exports the whole world positioned where each model is and rotated.

**Comment by Stellarspace** [comment]
Didn't @Perfare say she or he couldn't fix it?

**Comment by Daniel-Ayala** [comment]
Exactly the same thing happened to me. And not only when exporting the whole scene. When I try to export one single item, the mesh includes a huge amount of objects. The same thing doesn't happen with another ripping program, which is able to separate the meshes correctly, so the problem should be possible to solve.

Still, if solving it is too complicated, yet another reason to have another kind of port, like glTF.

**Comment by Perfare** [comment]
I tried to fix this on 9b1e3435d6b66be327898f62f75e6a43aeda58bf
It is now can export each component normally, not export the entire mesh multiple times. But there is still a location problem with each part and I don't know how to fix it for the time being.,

**Comment by Perfare** [comment]
I tried to fix this combine mesh problem in new export fbx feature, on commit 9b1e343
It is now can export each component normally, not export the entire mesh multiple times. But there is still a location problem with each part and I don't know how to fix it for the time being.

**Comment by Tosyk** [comment]
Perfare, can be more specific on what you can't find to place objects in a right positions - I have a friend with a strong experience on that field that might help with this.

**Comment by Tosyk** [comment]
yeah that's what I asked. I know it's not model itself but maybe some other files that control the model transforming. so if you have any clue I might hand this info to my friend
