### ISSUE TITLE
Some Animators crash Asset Studio

### ISSUE THREAD

**Issue by Cpt-Hazama** [Perfare/AssetStudio#202]
I've been trying to look at the models/animations for SCP Unity and SCP Secret Laboratory, but some of the animators crash the program. Is there anyway I can fix this? 
![capture](https://user-images.githubusercontent.com/7193583/41448309-eb6073d2-7027-11e8-9767-c1423599ca97.JPG)
![capture2](https://user-images.githubusercontent.com/7193583/41448333-0cef8f24-7028-11e8-8cde-5a10f133a739.JPG)
These are my export settings and what I tried to export

**Comment by Stellarspace** [comment]
Upload the data and post it here, so that the developer can help you.
