### ISSUE TITLE
Problem when exporting an animation

### ISSUE THREAD

**Issue by Kapocha33** [Perfare/AssetStudio#203]
If you use the "Export Animation with selected Animation Clip" method, this error occurs
![sin titulo](https://user-images.githubusercontent.com/40285107/41448888-e3f2fc8a-7033-11e8-82ff-a59b8503f61d.png)

If you want to use the option "All assets" is blocked

https://drive.google.com/file/d/1jjKyJxSXHsVzmedMHOL_pAIcu5E1B0y_/view

**Comment by Stellarspace** [comment]
Exporting animations is incomplete.
