### ISSUE TITLE
Won't open new mesh files, please fix!!!!!!!!!!!!

### ISSUE THREAD

**Issue by kim-sama** [Perfare/AssetStudio#204]
I have all the requirements for this program and I had no trouble with it, but today I started to get a error that says "unable to read beyond the end of the stream" and now it crashes when I try to export, when I used this program before I got this error it was 100% working, now it's not working anymore. Please fix

**Comment by kim-sama** [comment]
![image](https://user-images.githubusercontent.com/40289574/41454827-3e52d986-70be-11e8-8e89-68d0f9f93c9a.png)

**Comment by kim-sama** [comment]
I really need this program for my work, so is there a way to fix it?

**Comment by Stellarspace** [comment]
It's difficult for the developer to fix the program for bundle or asset specific issues. Make sure you are running the [latest build](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts) and please upload the data somewhere such as here.

**Comment by kim-sama** [comment]
I think I know the problem I tried to open old versions of the files and they work, I don't know why it doesn't work with the new version

**Comment by Perfare** [comment]
Please upload the problematic file or I cannot solve the problem

**Comment by kim-sama** [comment]
Problematic files
https://drive.google.com/open?id=1anLVDWAHeAeBzYbuMG3iP1ToXILTYm3n
