### ISSUE TITLE
Application exits automatically when importing asset files.

### ISSUE THREAD

**Issue by MilutinMujovic** [Perfare/AssetStudio#205]
I didn't have this problem in Unity Studio, but in this one when I try to import 1500 asset files, the application automatically closes with no warning.
I can't find any logs nor I know the way to debug this issue.
Can someone help me?

**Comment by Stellarspace** [comment]
You would have to download [Visual Studio Community](https://www.visualstudio.com/) and [debug](https://msdn.microsoft.com/en-us/library/wx0123s5.aspx).

Make sure you are using the latest build, which contains additional fixes that the compiled release does not.

**Comment by MilutinMujovic** [comment]
Which one should I choose?
https://i.imgur.com/cUKqfSb.png

**Comment by Perfare** [comment]
Please upload files I will check them

**Comment by MilutinMujovic** [comment]
@Perfare Here you go. Just extract the zip file and open folder with Asset Studio.
https://mega.nz/#!gU4gyAgL!-AVi-Z4BaVPfgtywcynK9hAZZTuY95KRVnlpI01Ts-4

**Comment by MilutinMujovic** [comment]
Did you test it?

**Comment by Perfare** [comment]
Sonme files have the same name in these bundle files, AssetStudio can not load two files with the same name at the same time.
It is recommended to use the Extract folder and then manually process these files.

**Comment by MilutinMujovic** [comment]
I extracted the folder, and all files are no larger than 200mb each, so definitely not even close to 2GB.
I also renamed them all so that they don't have the same name and it still crashes.
