### ISSUE TITLE
FBX files not right with my export.

### ISSUE THREAD

**Issue by rodeo7** [Perfare/AssetStudio#206]
I try to export to FBX and I get a bunch of stuff made over and over and not correctly. There is no Materials done properly on the objects that are supposed to export. This is a Race track and was wondering if you could try yourself to see why it is not working properly. Otherwise I will spend a year in my spare time remapping everything. I would like to have things work better to utilize my time better for my mods.
Here is a link to the file.
https://www.dropbox.com/s/5kpvezw2qnj0fca/Texas_Trk.rar?dl=0

Regards!

**Comment by Stellarspace** [comment]
It isn't perfect. Mind posting a screenshot?

**Comment by rodeo7** [comment]
That is why I made the file available. I can post a screenshot but it is a mess of planes on top of the other objects. will post in a bit for you.

**Comment by rodeo7** [comment]
![fbx-import](https://user-images.githubusercontent.com/37726377/41573799-1bfd52e8-7344-11e8-8ccf-fd685760f488.png)

**Comment by rodeo7** [comment]
Will the file I posted help at all?

**Comment by rodeo7** [comment]
I hope you can look into this. Just let me know if you are going to so I can decide how I am going to move forward.

**Comment by Stellarspace** [comment]
@rodeo7 This is the same issue several other people have been having with this program. There is no fix for it because @Perfare lacks 3D model knowledge. You will have to clean up the model manually. I forget the issue number.

**Comment by rodeo7** [comment]
Thank you I will try it out. I hope you figure out the rest. If you need any files let me know.

**Comment by rodeo7** [comment]
Yeah I see the improvement and the meshes not aligned like they should be. what I did find you though is if I just exported one element at a time to FBX instead of the whole main element it would place things properly with proper texture mapping. So I am really excited about that now.

**Comment by Perfare** [comment]
Duplicate #199
