### ISSUE TITLE
Help (mesh problem)

### ISSUE THREAD

**Issue by SoldierCF** [Perfare/AssetStudio#207]
My windows is 8 and so I can not download and install visual studio, could someone send me the already compiled version? Please.

**Comment by Stellarspace** [comment]
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

**Comment by SoldierCF** [comment]
Thanks! ^^

**Comment by Stellarspace** [comment]
@SoldierCF Please close the issue if resolved.

**Comment by SoldierCF** [comment]
Yes, it worked, but now this error occurs when trying to open / export mesh.

https://s15.postimg.cc/wbad2kftn/erro.png

But I have the necessary programs ... The problem is with crossfire mobile files (cfm)

**Comment by kim-sama** [comment]
It opens the files fine from the old CFM versions, I don't know what they were thinking to make this happen

**Comment by Perfare** [comment]
Please upload the problematic file or I cannot solve the problem
