### ISSUE TITLE
Weird looking model

### ISSUE THREAD

**Issue by MilutinMujovic** [Perfare/AssetStudio#210]
One model appears broken for some reason, as you can see in the pic: i.imgur.com/bEtbCaM.png but all other models are fine, and this one appears normal in the game.
Here you go: 
https://mega.nz/#F!MEgASZaT!J5i3vUJ02RP0fXKKX4UW2A
I uploaded both basic and legendary looks, just so you can see.
It's the same character, just with a basic and legendary look. Legendary look model is perfectly fine and basic is broken like in the picture. 
The weird part is that they both appear normal in the game, so the model isn't corrupted or anything, I checked with multiple people who sent me their files as well.
Maybe there is additional encryption or code that that model has or something?

**Comment by MilutinMujovic** [comment]
Fixed the link, sorry for the bad one.
@Perfare can you please check it out by the end of this month?

**Comment by Stellarspace** [comment]
@MilutinMujovic I haven't checked it, but there is definitely no encryption.
