### ISSUE TITLE
Error when select "mesh" type

### ISSUE THREAD

**Issue by heiansamurai** [Perfare/AssetStudio#211]
is there any workaround for this?
array dimension exceeded supported range

See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.OutOfMemoryException: Array dimensions exceeded supported range.
   at AssetStudio.Mesh..ctor(AssetPreloadData MeshPD, Boolean readSwitch) in C:\projects\assetstudio\AssetStudio\Classes\Mesh.cs:line 650
   at AssetStudio.AssetStudioForm.PreviewAsset(AssetPreloadData asset) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 842
   at AssetStudio.AssetStudioForm.selectAsset(Object sender, ListViewItemSelectionChangedEventArgs e) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 685
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudio
    Assembly Version: 0.10.0.36
    Win32 Version: 0.10.0.36
    CodeBase: file:///E:/Unity/Asset%20Studio%20v100/AssetStudio.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0
    CodeBase: file:///E:/Unity/Asset%20Studio%20v100/OpenTK.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0
    CodeBase: file:///E:/Unity/Asset%20Studio%20v100/OpenTK.GLControl.DLL
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
SharpDX.Mathematics
    Assembly Version: 4.0.1.0
    Win32 Version: 4.0.1
    CodeBase: file:///E:/Unity/Asset%20Studio%20v100/SharpDX.Mathematics.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.

![image](https://user-images.githubusercontent.com/40525910/41812835-f9d5250a-7754-11e8-800b-05769a85da00.png)

tried to open this file
https://drive.google.com/open?id=1PXmyYTtBOTORMVwb8AcuSaCZJl5ZnnRa
after click the mesh the error popped up

**Comment by epikus29** [comment]
Honkai Impact 3 ^^
You should use Unity Studio v0.9 for this game, it extracted everything for me without errors
