### ISSUE TITLE
HELP - Mesh CFM

### ISSUE THREAD

**Issue by SoldierCF** [Perfare/AssetStudio#212]
I used several versions of unity, my program has the requirements, but I can not extract the mesh's if someone can help me.

File: http://www.mediafire.com/file/nkyai9y6ktl4n96/Help.rar

I need this files:

![files](https://user-images.githubusercontent.com/40343992/41825201-dff426f6-77f2-11e8-8414-4eeb3adffc9c.PNG)

**Comment by kim-sama** [comment]
There is a update that fixes it

**Comment by SoldierCF** [comment]
Even with this update, I can not extract the files, if you can extract it for me

**Comment by Perfare** [comment]
This issue is only fixed in the 0.10.0.36 version. I don't know how to fix this bug perfectly.
