### ISSUE TITLE
Feature: log files

### ISSUE THREAD

**Issue by MilutinMujovic** [Perfare/AssetStudio#215]
Not an issue, but a feature request. 
It would be nice if there was a generated log file when we use AS so that those of us who don't have Visual Studio can troubleshoot issues. :)

**Comment by Stellarspace** [comment]
This has already been requested and I don't think it's absolutely necessary.

**Comment by MilutinMujovic** [comment]
Okay, I was just wondering because you didn't tell me how to do it precisely in other issue. 
The program keeps constantly crashing for some reason when importing a lot of files and it's not only for one game, there are others that make it crash as well, which is strange because Unity Studio never had that problem.
I tried opening those files with Unity Studio and they open normally.

**Comment by HeresHavi** [comment]
Yeah, best way to get an issue fixed is by sending Perfare the file you are trying to extract/open and he can look into it.

**Comment by MilutinMujovic** [comment]
@HeresHavi Yes, but I don't wanna wait for him/her to take a look at it. I want to see for myself and try to fix it so that we both benefit from it. :)
Can you at least then tell me how to open the source code in VB? I downloaded the repository and imported it in VB, but I don't know what to do from there. :)

**Comment by Stellarspace** [comment]
@MilutinMujovic If it's an asset bundle (.unity3d file extension) and it's over 2GB in size, Unity Studio won't be able to decompress the file. You won't be able to fix it if you aren't a developer and don't know the programming language. You don't even have Visual Studio installed on your computer. If you want it so bad, then you must download and install Visual Studio Community, download the code as a ZIP file, extract the contents of the ZIP file and open the "AssetStudio.sln" file, which is in the parent folder.

**Comment by Stellarspace** [comment]
**Perfare has already stated the following:** 

Some files have the same name in these bundle files, AssetStudio can not load two files with the same name at the same time.
It is recommended to use the Extract folder and then manually process these files.

**Comment by MilutinMujovic** [comment]
I extracted the folder, and all files are no larger than 200mb each, so definitely not even close to 2GB.
I also renamed them all so that they don't have the same name and it still crashes.

**Comment by Perfare** [comment]
Duplicate #198
