### ISSUE TITLE
Unable to open this file.

### ISSUE THREAD

**Issue by HeresHavi** [Perfare/AssetStudio#216]
I'm able to open all the other files except this one. Maybe because it's over 2 GB?
http://prntscr.com/k2jwvm

File: http://www.mediafire.com/file/3odxaqlkf3vue4s/core_deps
_2.68GB_

**Comment by Perfare** [comment]
AssetStudio can't directly load bundle files larger than 2gb for a variety of reasons. You can use UABE or using UABE to export the asset file, AssetStudio support load over 2GB assets file.

**Comment by HeresHavi** [comment]
Ah, that makes sense! Thank you very much!

**Comment by HeresHavi** [comment]
Ok, so I did what you said. But even when I combine the .resource, .resS it says "can't find the resource file .resS"

What am I doing wrong?

**Comment by Perfare** [comment]
You need to use UABE to export all the files and put them together, make sure the file name is correct

**Comment by HeresHavi** [comment]
It worked. Feel free to close this case. Also, maybe an idea to add a message whenever someone is trying to open a file larger than 2 GB or maybe in a README.txt
