### ISSUE TITLE
Shaders are still serialized! (5.6.3p1)

### ISSUE THREAD

**Issue by classyham** [Perfare/AssetStudio#219]
Here is an example of a shader exported from a vrchat asset bundle. The shaders come out serialized and I have no idea on how to solve that. I've attached an example of one of the shaders pulled from the asset bundle
[Shader #00070.txt](https://github.com/Perfare/AssetStudio/files/2172498/Shader.00070.txt)
.

**Comment by Stellarspace** [comment]
@classyham How is it serialized? It looks like C# programming language.

**Comment by Perfare** [comment]
There is no way to handle binary shader file now.

**Comment by Perfare** [comment]
The serialized Shader can already be exported, although there is still a need to improve.

**Comment by sebastientromp** [comment]
Is there a way to then reimport this into Unity?
