### ISSUE TITLE
Program Crashes

### ISSUE THREAD

**Issue by ExtraOrdinary3** [Perfare/AssetStudio#222]
So for some reason, every time I try to open the program it keeps crashing, and the issue keeps persisting

**Comment by Stellarspace** [comment]
Do you have .Net Framework installed?

**Comment by ExtraOrdinary3** [comment]
I installed them, but the issue is still persisting, whenever I open it, it shows the program for 1 second, and then it disappears

**Comment by Stellarspace** [comment]
@ExtraOrdinary3 Are you using the latest build: https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

What operating system and architecture?

**Comment by Perfare** [comment]
Can you upload the file somewhere?

**Comment by HeresHavi** [comment]
I probably know what it is. 

Make sure that the file is not over 2 GB. AssetStudio doesn't allow loading a file that big due many reason. Use: https://7daystodie.com/forums/showthread.php?22675-Unity-Assets-Bundle-Extractor to extract that specific file if that's the case and split them up. Make sure when you extract the parts, you name them exactly how they are.

**Comment by Stellarspace** [comment]
@Perfare He said the program crashes when he opens the program.

**Comment by Perfare** [comment]
@Stellarspace My mistake
@ExtraOrdinary3 This is a very special situation and I can hardly fix it. I can only confirm that AssetStudio is operational on most computers.

**Comment by ExtraOrdinary3** [comment]
Ah, I see. Thank you for trying to help me.
