### ISSUE TITLE
Can't Download Latest Build from AppVeyor: "ResourceNotFound"

### ISSUE THREAD

**Issue by hairycactus** [Perfare/AssetStudio#227]
I have tried repeatedly to download the latest build of AssetStudio (currently v0.10.0.51 - 17 Jul 2018) from [AppVeyor](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts).

However, neither the [x64](https://ci.appveyor.com/api/buildjobs/y85my8doioi3vtgy/artifacts/AssetStudio%2Fbin%2Fx64%2FAssetStudio.x64.v0.10.0.51.zip) nor [x86](https://ci.appveyor.com/api/buildjobs/y85my8doioi3vtgy/artifacts/AssetStudio%2Fbin%2Fx86%2FAssetStudio.v0.10.0.51.zip) ZIP links work in the web browser, or standalone file downloaders. I have also tried using a VPN, but different IP addresses do not help.

The error message shown in the browser is as follows:-
> ResourceNotFound
> The specified resource does not exist.

Are the file permissions set to public access ?

Alternatively, is it possible to continue hosting the downloads at [Github](https://github.com/Perfare/AssetStudio/releases), or at another suitable mirror ?

Thanks !

**Comment by Stellarspace** [comment]
@hairycactus https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts works for me.

**Comment by Perfare** [comment]
May be just a temporary network fluctuation, please test if you can download now

**Comment by hairycactus** [comment]
For web browsers, I found that an addon is interfering with the ZIP download (presumably URL redirect). Disabling the addon allows the download to succeed.

On the other hand, the download still fails in standalone file downloaders, such as the commandline tool [Nugget.exe](http://trax.x10.mx/nugget).

Error for the [latest build](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts) v0.10.0.52 x64 (19 Jul 2018):
`> nugget https://ci.appveyor.com/api/buildjobs/7opplec0v5r2k3iu/artifacts/AssetStudio/bin/x64/AssetStudio.x64.v0.10.0.52.zip`

> Retrieving AssetStudio.x64.v0.10.0.52.zip... [################
Resource not found. Double-check URL and network connectivity.

**Comment by hairycactus** [comment]
Somewhat related question ... Does the project's AppVeyor '[Artifacts](https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts)' or '[History](https://ci.appveyor.com/project/Perfare/assetstudio/history)' pages provide feeds-notification about new builds ?

I tried the following (as well as other rss/atom & URL variations), but none of them work:
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts/feed.xml
https://ci.appveyor.com/project/Perfare/assetstudio/history/feed.xml

AppVeyor's own feed does work: https://www.appveyor.com/feed.xml

The feed at the project's Github '[Releases](https://github.com/Perfare/AssetStudio/releases)' page continue to work, but is now irrelevant since the last update there was 29/30 May 2018: https://github.com/Perfare/AssetStudio/releases.atom

For now, I check the project's Github '[Commits](https://github.com/Perfare/AssetStudio/commits)' feed as a substitute, but I'm wondering if there is a possibility that the project might totally move away from Github in the future:
https://github.com/Perfare/AssetStudio/commits.atom

**Comment by Stellarspace** [comment]
@hairycactus I use the latest version of Google Chrome with uBlock Origin and HTTPS Everywhere and both artifacts download as expected. I used wget in Terminal and it downloaded as expected too.

#### > wget https://ci.appveyor.com/api/buildjobs/7opplec0v5r2k3iu/artifacts/AssetStudio%2Fbin%2Fx86%2FAssetStudio.v0.10.0.52.zip
> --2018-07-20 00:26:45--  https://ci.appveyor.com/api/buildjobs/7opplec0v5r2k3iu/artifacts/AssetStudio%2Fbin%2Fx86%2FAssetStudio.v0.10.0.52.zip
> Resolving ci.appveyor.com (ci.appveyor.com)... 138.91.141.243
> Connecting to ci.appveyor.com (ci.appveyor.com)|138.91.141.243|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://appveyorcidata.blob.core.windows.net/perfare-61446/assetstudio/0-10-0-52/7opplec0v5r2k3iu/AssetStudio/bin/x86/AssetStudio.v0.10.0.52.zip?sv=2015-12-11&sr=c&sig=sFnJ%2F22kChl%2FEwFri37Xbhrv5biYpI%2BKUaW2hQT1%2F5Y%3D&st=2018-07-20T04%3A25%3A46Z&se=2018-07-20T04%3A31%3A46Z&sp=r [following]
> --2018-07-20 00:26:46--  https://appveyorcidata.blob.core.windows.net/perfare-61446/assetstudio/0-10-0-52/7opplec0v5r2k3iu/AssetStudio/bin/x86/AssetStudio.v0.10.0.52.zip?sv=2015-12-11&sr=c&sig=sFnJ%2F22kChl%2FEwFri37Xbhrv5biYpI%2BKUaW2hQT1%2F5Y%3D&st=2018-07-20T04%3A25%3A46Z&se=2018-07-20T04%3A31%3A46Z&sp=r
> Resolving appveyorcidata.blob.core.windows.net (appveyorcidata.blob.core.windows.net)... 13.88.145.64
> Connecting to appveyorcidata.blob.core.windows.net (appveyorcidata.blob.core.windows.net)|13.88.145.64|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 7156303 (6.8M) [application/octet-stream]
> Saving to: ‘AssetStudio%2Fbin%2Fx86%2FAssetStudio.v0.10.0.52.zip’
> 
> AssetStudio%2Fbin%2 100%[===================>]   6.82M  2.01MB/s    in 3.5s    
> 
> 2018-07-20 00:26:50 (1.94 MB/s) - ‘AssetStudio%2Fbin%2Fx86%2FAssetStudio.v0.10.0.52.zip’ saved [7156303/7156303]

#### > wget https://ci.appveyor.com/api/buildjobs/7opplec0v5r2k3iu/artifacts/AssetStudio%2Fbin%2Fx64%2FAssetStudio.x64.v0.10.0.52.zip

> --2018-07-20 00:27:01--  https://ci.appveyor.com/api/buildjobs/7opplec0v5r2k3iu/artifacts/AssetStudio%2Fbin%2Fx64%2FAssetStudio.x64.v0.10.0.52.zip
> Resolving ci.appveyor.com (ci.appveyor.com)... 138.91.141.243
> Connecting to ci.appveyor.com (ci.appveyor.com)|138.91.141.243|:443... connected.
> HTTP request sent, awaiting response... 302 Found
> Location: https://appveyorcidata.blob.core.windows.net/perfare-61446/assetstudio/0-10-0-52/7opplec0v5r2k3iu/AssetStudio/bin/x64/AssetStudio.x64.v0.10.0.52.zip?sv=2015-12-11&sr=c&sig=H360VuL0hYi7x3edzA2F1ww4KNxNpe5A0j9uvM8hDtc%3D&st=2018-07-20T04%3A26%3A02Z&se=2018-07-20T04%3A32%3A02Z&sp=r [following]
> --2018-07-20 00:27:02--  https://appveyorcidata.blob.core.windows.net/perfare-61446/assetstudio/0-10-0-52/7opplec0v5r2k3iu/AssetStudio/bin/x64/AssetStudio.x64.v0.10.0.52.zip?sv=2015-12-11&sr=c&sig=H360VuL0hYi7x3edzA2F1ww4KNxNpe5A0j9uvM8hDtc%3D&st=2018-07-20T04%3A26%3A02Z&se=2018-07-20T04%3A32%3A02Z&sp=r
> Resolving appveyorcidata.blob.core.windows.net (appveyorcidata.blob.core.windows.net)... 13.88.145.64
> Connecting to appveyorcidata.blob.core.windows.net (appveyorcidata.blob.core.windows.net)|13.88.145.64|:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 7782241 (7.4M) [application/octet-stream]
> Saving to: ‘AssetStudio%2Fbin%2Fx64%2FAssetStudio.x64.v0.10.0.52.zip’
> 
> AssetStudio%2Fbin%2 100%[===================>]   7.42M  1.54MB/s    in 5.0s    
>

**Comment by Stellarspace** [comment]
@hairycactus You need an account with AppVeyor to get email notifications. https://www.appveyor.com/docs/notifications/
@Perfare isn't moving away from GitHub unless they remove the repository. AppVeyer allows developers to build programs from the current source code. This way is more efficient and less time consuming since the developer would have to rebuild in Visual Studio, then upload the compiled program to GitHub. This program is a decompiler in an early stage, so it requires regular updates. There will most likely be a v0.11 compiled and uploaded very soon.

**Comment by hairycactus** [comment]
> @Stellarspace : ["I also used wget in Terminal and it downloaded as expected."](https://github.com/Perfare/AssetStudio/issues/227#issuecomment-406486299)

Thanks for suggesting **Wget.exe**, which I hadn't tried. The file download from AppVeyor was successful -- reason: Wget automatically follows URL redirects, which affect files hosted at AppVeyor. (However, using Wget's "`--spider`" parameter to check if the target file exists leads to a misleading "_Remote file does not exist -- broken link!!!_" error.)

I previously tried **cURL.exe** at the command prompt, but the file download from AppVeyor failed (outcome: 0-byte file) -- reason: cURL does not follow URL redirects by default. After some investigations, I found that specifying the "`-L`" ("`--location`") parameter allows the file download to succeed.

**Nugget.exe** (a simplified form of cURL) probably failed to download the file for the same reason ("_Resource not found. Double-check URL_" error), & there is no workaround since it does not appear to support parameters.

As for the web browser, the failed download is caused by an addon that is supposed to strip extraneous garbage/ tracking strings appended to URLs.

Taking the **v0.10.0.51 x64 (17 Jul 2018)** build as an example, the ZIP URL as shown upfront:
https://ci.appveyor.com/api/buildjobs/7opplec0v5r2k3iu/artifacts/AssetStudio/bin/x64/AssetStudio.x64.v0.10.0.52.zip

... redirects to a longer URL appended with numerous strings (sv, sr, sig, st, se, sp), as follows:
`https://appveyorcidata.blob.core.windows.net/perfare-61446/assetstudio/0-10-0-52/7opplec0v5r2k3iu/AssetStudio/bin/x64/AssetStudio.x64.v0.10.0.52.zip?sv=<XXXXXX>&sr=<X>&sig=<XXXXXXXXXXXXXXX>&st=<XXXXXXXXXXX>&se=<XXXXXXXXXXX&sp=<X>`

For instance, the download fails if the following strings are removed:
* "`sig`" removed: Leads to "_ResourceNotFound_" error
* "`st`" removed:  Leads to "_AuthenticationFailed_" error

PS: Closing this issue, since the file download query has been resolved. Thanks again !

**Comment by hairycactus** [comment]
> @Stellarspace  : ["You need an account with AppVeyor to get](https://github.com/Perfare/AssetStudio/issues/227#issuecomment-406487473) [email notifications](https://www.appveyor.com/docs/notifications)."

Yes,  I am aware of AppVeyor providing email notifications. I'm just trying to avoid having to register another account, & also having to receive emails for every notification. I was wondering if web feeds is a function that project owners have to enable in order for the feeds to become available to users. But I guess not.

The reason why I prefer web feeds is because I can simply open the feed's URL in a browser to fetch a list of project feeds (latest & historical) in a single browser tab -- as opposed to receiving single feeds for every notification via a feed reader, & having to delete them later.

> "AppVeyer allows developers to build programs from the current source code. [...] This program is a decompiler in an early stage, so it requires regular updates. There will most likely be a v0.11 compiled and uploaded very soon."

I see, thanks for the explanation. Are these frequently-released builds (sometimes as close as every 1-3 days) at AppVeyor akin to unstable Nightly or Beta builds ? I don't recall seeing such frequent releases previously. The project's [README.md](https://github.com/Perfare/AssetStudio#assetstudio) & [Releases](https://github.com/Perfare/AssetStudio/releases) pages merely describe the files hosted at AppVeyor as the "latest build".

Would the upcoming AssetStudio v0.11 be a Stable release ?

**Comment by Stellarspace** [comment]
@hairycactus The developer has been correcting issues that people are having with specific Unity assets that people are trying to extract. Every file is different.
