### ISSUE TITLE
The FBX is not extracted well

### ISSUE THREAD

**Issue by Kapocha33** [Perfare/AssetStudio#230]
When I extract the model the animations along with its skeleton does not appear well
![2](https://user-images.githubusercontent.com/40285107/43011915-48b78a98-8c1b-11e8-9c08-cf3d1db6ddcc.png)
![sin titulo](https://user-images.githubusercontent.com/40285107/43011916-48da366a-8c1b-11e8-9ba7-f50a3833760a.png)

https://drive.google.com/open?id=1HxtIOxGDtFdTdgMJBY0neuhXlRF_iU-w

**Comment by Stellarspace** [comment]
@Kapocha33 How is it supposed to appear? What is missing?

**Comment by mafaca** [comment]
I think it is the same issue as https://github.com/Perfare/AssetStudio/issues/231

**Comment by Perfare** [comment]
Fixed in 2d0278db87fe0762c309adec479bbad85656f0fa
