### ISSUE TITLE
Bone&weight

### ISSUE THREAD

**Issue by TSelman61** [Perfare/AssetStudio#231]
Mesh files does not have vertex groups. The bones are ineffective although I export mesh files in .fbx format.
Files: https://drive.google.com/open?id=1f8AsasSrcWHZmOMe-vhvWcSt4fjHb1mM

**Comment by mafaca** [comment]
That is happaned because Animator has optimized hierarchy. That is mean that information about hierarchy is contained inside Mesh and bones pathes is contained inside Avatar. So no GameObjects with Transform component exist for bones.

**Comment by Perfare** [comment]
Fixed in 2d0278db87fe0762c309adec479bbad85656f0fa

**Comment by TSelman61** [comment]
Thank you.
I guess it's working now. :)
