### ISSUE TITLE
Feature Request & Some Questions

### ISSUE THREAD

**Issue by Stellarspace** [Perfare/AssetStudio#232]
Why can't I export all objects with AnimationClip if there is an AnimationClip with Animator attached to some objects, but not other objects?

Why is "Export all objects (Split)" displayed twice in the Export menu?

"Jump to scene hierarchy" and "export objects with selected AnimationClip" does not work on any of the assets listed.

How is exporting the select asset useful on AnimationClip assets if it comes out as a DAT file? How do I use the DAT file on a model?

**Comment by Perfare** [comment]
If Animator has a binding AnimationClip, use "Export all objects (Split)" will export it.
The old export feature is preserved for compatibility reasons.
"Jump to scene hierarchy" only support Mesh. I tested "export objects with selected AnimationClip", it work properly.
AnimationClip can only be exported with Animator or Object.

**Comment by Stellarspace** [comment]
@Perfare If I use the split option, all of the objects lose their positions. I tried ""Jump to scene hierarchy" on multiple Meshes and it doesn't work. Is there a way for it to tell me whether an object has Animator with AnimationClip?

**Comment by RamChupi** [comment]
The simplest way to find the AnimationClips connected to an Animator is to export the Animator itself with no AnimationClips.It will look for it's AnimationClips and export all of the ones that match to the Animator,it's handy i'd say.
