### ISSUE TITLE
Array dimensions exceeded supported range

### ISSUE THREAD

**Issue by PriChama** [Perfare/AssetStudio#237]
Whenever I load some unity3d files I get an error when trying to export with AnimationClip. All of the ones that have errors do not have an Animator file. However I have exported ones without the Animator using this method... But some of them don't work. If you could look at it that'd be great! Or if there's something I need to do, if someone could tell me.
![error](https://user-images.githubusercontent.com/41806074/43346464-76161854-91ae-11e8-98ac-1d90a970bf22.png)

[sample.zip](https://github.com/Perfare/AssetStudio/files/2237226/sample.zip)

**Comment by nasvaykid** [comment]
same problem
