### ISSUE TITLE
Can't export animation clip from the assets

### ISSUE THREAD

**Issue by nasvaykid** [Perfare/AssetStudio#239]
When i try to export animation clip from asset AssetStudio print "No Object can be exported."
![ddd](https://user-images.githubusercontent.com/41837508/43364127-a6e5850c-932d-11e8-8de6-e06dd74a50af.jpg)
P.S. Pls help :c

**Comment by RamChupi** [comment]
You need to find the Animator that corresponds with the AnimationClip.A much easier trick is just to look for the Animators and export them alone since they track all the AnimationClips assigned to the animator.

**Comment by Perfare** [comment]
AnimationClip can only be exported with Animator or exported with GameObject which in Scene Hierarchy

**Comment by FoxyExperiments** [comment]
![image](https://user-images.githubusercontent.com/97281389/150198156-45b1248c-e199-430f-a447-1041d8bfbd24.png)
bruh
