### ISSUE TITLE
Unable to load DLL 'TextureConverterWrapper.dll': The specified module could not be found.

### ISSUE THREAD

**Issue by Dinoguy1000** [Perfare/AssetStudio#240]
Attempting to open or export certain Texture2D resources in Asset Studio x64 0.10.0.58 results in this error message. I've confirmed that TextureConverterWrapper.dll is present in the Asset Studio directory.

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.DllNotFoundException: Unable to load DLL 'TextureConverterWrapper.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at AssetStudio.Texture2DConverter.Ponvert(Byte[] buffer, IntPtr bmp, Int32 nWidth, Int32 nHeight, Int32 len, Int32 type, Int32 bmpsize, Boolean fixAlpha)
   at AssetStudio.Texture2DConverter.TextureConverter() in C:\projects\assetstudio\AssetStudio\StudioClasses\Texture2DConverter.cs:line 955
   at AssetStudio.Texture2DConverter.ConvertToBitmap(Boolean flip) in C:\projects\assetstudio\AssetStudio\StudioClasses\Texture2DConverter.cs:line 871
   at AssetStudio.AssetStudioForm.PreviewAsset(AssetPreloadData asset) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 709
   at AssetStudio.AssetStudioForm.selectAsset(Object sender, ListViewItemSelectionChangedEventArgs e) in C:\projects\assetstudio\AssetStudio\AssetStudioForm.cs:line 685
   at System.Windows.Forms.ListView.OnItemSelectionChanged(ListViewItemSelectionChangedEventArgs e)
   at System.Windows.Forms.ListView.WmReflectNotify(Message& m)
   at System.Windows.Forms.ListView.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3131.0 built by: NET472REL1LAST
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
AssetStudio
    Assembly Version: 0.10.0.58
    Win32 Version: 0.10.0.58
    CodeBase: file:///C:/Users/Phillip/Downloads/AssetStudio.x64.v0.10.0.58/AssetStudio.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
OpenTK
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0
    CodeBase: file:///C:/Users/Phillip/Downloads/AssetStudio.x64.v0.10.0.58/OpenTK.DLL
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3110.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0 built by: NET472REL1
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
OpenTK.GLControl
    Assembly Version: 3.0.0.0
    Win32 Version: 3.0.0
    CodeBase: file:///C:/Users/Phillip/Downloads/AssetStudio.x64.v0.10.0.58/OpenTK.GLControl.DLL
----------------------------------------
System.Web.Extensions
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3056.0
    CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Web.Extensions/v4.0_4.0.0.0__31bf3856ad364e35/System.Web.Extensions.dll
----------------------------------------
System.Half
    Assembly Version: 0.0.0.0
    Win32 Version: 0.0.0.0
    CodeBase: file:///C:/Users/Phillip/Downloads/AssetStudio.x64.v0.10.0.58/System.Half.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.
```

![image](https://user-images.githubusercontent.com/818183/43369501-40f37526-9335-11e8-9528-b27879927fbb.png)

![image](https://user-images.githubusercontent.com/818183/43369486-05e4fde2-9335-11e8-8ad2-f4476ebd45db.png)

**Comment by HeresHavi** [comment]
Can u upload the file and post it here?

**Comment by Dinoguy1000** [comment]
One of the files resulting in the error, you mean? I don't know how to export them without triggering the error. If it helps at all, though, some of them have the string "fmt12" in their names, corresponding to the pixel format they're stored in (others that do display without error are "fmt2" in ARGB4444, "fmt4" in RGBA32, and "fmt3" in RGB24).

**Comment by HeresHavi** [comment]
Just send the whole file you open

**Comment by Dinoguy1000** [comment]
[resources.zip](https://github.com/Perfare/AssetStudio/files/2239245/resources.zip)

**Comment by HeresHavi** [comment]
You gotta upload the resources.assets.resS too.

**Comment by Dinoguy1000** [comment]
Aah, sorry, I didn't have any idea! This is my first time messing with anything Unity-related. =X

Here you are:
[resources.assets.zip](https://github.com/Perfare/AssetStudio/files/2239260/resources.assets.zip)

**Comment by HeresHavi** [comment]
https://www82.zippyshare.com/v/eBlp1iCl/file.html

I have managed to extract it without any issues.

**Comment by Dinoguy1000** [comment]
Thanks for extracting that for me, but it doesn't really help with my issue, considering there are almost 2 gb of other files to extract, and I'd much rather be able to preview them from within Asset Studio before extracting.

**Comment by HeresHavi** [comment]
Ok, what you should do is upload them all on Mediafire or Mega and then I'm trying again and make sure it's not on your end.

**Comment by HeresHavi** [comment]
The game is called **Yu-Gi-Oh! Links** right?

**Comment by HeresHavi** [comment]
I installed the game myself and extracted everything there can be extracted.

https://www86.zippyshare.com/v/WJcJASTq/file.html

If the AssetStudio doesn't work, it has something to do on your end.

**Comment by Dinoguy1000** [comment]
Telling me this is a PEBKAC problem without even suggesting what I might have done wrong isn't the least bit helpful. I'll meet you halfway here: I downloaded the [0.10.0.58 x64 build](https://ci.appveyor.com/project/Perfare/assetstudio/build/0.10.0.58/artifacts) and extracted and ran it from my Downloads folder, without doing anything else. Yu-Gi-Oh! Duel Links is the first and only game/app I've tried opening in it, and I have been getting that error message consistently on the same assets every time I've tried viewing or extracting them.

Also, just as a heads-up, in order to get everything you can in Duel Links, you have to actually launch the game and pick what country you're in; once you've clicked through far enough, the game then downloads a massive collection of over 400 resource files (and that's only for if you select the United States as your country; I have no idea how much more data there is for other selected countries). If you didn't do that, you didn't get anywhere near everything the game has to be extracted.

**Comment by HeresHavi** [comment]
Alright, well I have no idea why it's not working for you, I really don't. It should just work fine for you. I'm just helping so that Prefare doesn't have to extract all these files to see if any errors occur. I just did what you said about the United States as the country and launching the game. Got 5 GB worth of extracted data. Also, the other languages will have the exact same data but then other languages on their images, audio, text etc.

I only uploaded the Sprite and Texture2D:

Sprite: http://www.mediafire.com/file/srt645rur158c81/Sprite.rar (130.74MB)
Texture2D: http://www.mediafire.com/file/g2aa19p3qv3rrf0/Texture2D.rar (1.73GB) (Still in progress)

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio/blob/master/README.md#requirements

**Comment by Dinoguy1000** [comment]
The listed requirements are already installed on my computer. The "missing" dependency is one of your project's DLLs, not any file from any of the listed requirements.

**Comment by Dinoguy1000** [comment]
They're already installed on this computer: 
![image](https://user-images.githubusercontent.com/818183/43376369-0a865b98-9380-11e8-8140-c13351fb4078.png)

**Comment by Perfare** [comment]
Make sure you have x86 and x64 versions installed, or you may need to reinstall them.
In addition, if you still encounter this problem, I can't help you anymore. This is a problem with your computer, not a problem with AssetStudio.

**Comment by leizongmin** [comment]
I install both Microsoft Visual C++ 2013 Redistributable and Microsoft Visual C++ 2015 Redistributable, problem solved.

**Comment by CasasAlex** [comment]
I had it when I used the theme of high contrast

> They're already installed on this computer:
> ![image](https://user-images.githubusercontent.com/818183/43376369-0a865b98-9380-11e8-8140-c13351fb4078.png)

I had it when I used the theme of high contrast
