### ISSUE TITLE
[Suggestion] Search for models like asset list

### ISSUE THREAD

**Issue by HeresHavi** [Perfare/AssetStudio#241]
Hey Prefare,

Maybe it's a good idea to add the same search method you have in the asset list for models.

For example, If I search for a ladder in asset list, it shows only the assets with ladder mentioned in their names: http://i.prntscr.com/wKA0aR-rSTGENMfbASlBKA.png

If I do that for models, it just only shows one: http://i.prntscr.com/xMxK81Y3RrGoRp7iLhUVSw.png

So if it's possible, maybe make it the same?

**Comment by Perfare** [comment]
asset list uses the ListView control. The ListView has VirtualMode, so it is very convenient and quick to control the displayed item, but the scene hieraicy uses the TreeView control. It does not have this mode, so controlling the displayed content requires high-consumption operations.

**Comment by bsimser** [comment]
I'm not able to put this into the code right now and send in a PR but this should work:

```
private List<TreeNode> CurrentNodeMatches = new List<TreeNode>();
private int LastNodeIndex = 0;
private string LastSearchText;

    private void button1_Click(object sender, EventArgs e)
    {


        string searchText = this.textBox1.Text;
        if (String.IsNullOrEmpty(searchText))
        {
            return;
        };


        if (LastSearchText != searchText)
        {
            //It's a new Search
            CurrentNodeMatches.Clear();
            LastSearchText = searchText;
            LastNodeIndex = 0;
            SearchNodes(searchText, treeView1.Nodes[0]);
        }

        if (LastNodeIndex >= 0 && CurrentNodeMatches.Count > 0 && LastNodeIndex < CurrentNodeMatches.Count)
        {
            TreeNode selectedNode = CurrentNodeMatches[LastNodeIndex];
            LastNodeIndex++;
            this.treeView1.SelectedNode = selectedNode;
            this.treeView1.SelectedNode.Expand();
            this.treeView1.Select();

        }
    } 

    private void SearchNodes(string SearchText, TreeNode StartNode)
    {
        TreeNode node = null;
        while (StartNode != null)
        {
            if (StartNode.Text.ToLower().Contains(SearchText.ToLower()))
            {
                CurrentNodeMatches.Add(StartNode);
            };
            if (StartNode.Nodes.Count != 0)
            {
                SearchNodes(SearchText, StartNode.Nodes[0]);//Recursive Search 
            };
            StartNode = StartNode.NextNode;
        };
    }
````

**Comment by HeresHavi** [comment]
@Perfare

**Comment by Perfare** [comment]
@bsimser @HeresHavi This is no different from the current search function, press the button once to display the next eligible node

**Comment by Perfare** [comment]
Because there are all kinds of problems, I finally decided not to implement this function.
