### ISSUE TITLE
Morph Issues

### ISSUE THREAD

**Issue by PriChama** [Perfare/AssetStudio#248]
Since I know animations are a work in progress, I have noticed a lot of models having broken facial morphs when ripping. I found one that was particularly bad and was wondering if you could take a look at it. Thanks!

[ddd.zip](https://github.com/Perfare/AssetStudio/files/2285077/ddd.zip)

**Comment by Perfare** [comment]
I don't think this is a problem, or I hope you can describe it in detail.

**Comment by PriChama** [comment]
When exporting some models, the morphs/facials turn get all scrambled like this;
![morph](https://user-images.githubusercontent.com/41806074/48688196-50e10480-eb82-11e8-8113-62040dc36919.png)

**Comment by Perfare** [comment]
In my opinion, this is your import or view program compatibility issue, try to lower the fbx version or change the used program.
![qq 20181119141756](https://user-images.githubusercontent.com/12952226/48689595-38b2c900-ec06-11e8-98fd-ca74dfe3b2f1.jpg)

**Comment by PriChama** [comment]
I tried multiple different versions, both Binary and ascii and a few different viewers but I'm coming with the same result.
Oh, but the original face is fine. Like without the game morphs or anything, it looks fine. Its just when applying the game morphs, sometimes they export weirdly. Like the picture I sent before.

**Comment by Perfare** [comment]
Ok, I already know the specific problem, I hope I can fix it.

**Comment by gcovers** [comment]
Hi, I have the same problem with morphs. Just load one with errors and not everyone else. The example character is from the Idolm @ ster Million Live game.

![Blender](https://user-images.githubusercontent.com/55722432/65472839-cde8a480-de4b-11e9-8d33-0d1808da8af4.png)
