### ISSUE TITLE
Broken Textures

### ISSUE THREAD

**Issue by kim-sama** [Perfare/AssetStudio#250]
Mesh and textures display and extract perfect when I extract from Android with app installed but when I extract from .apk textures and mesh are broken
![image](https://user-images.githubusercontent.com/40289574/44304970-9dfce100-a3af-11e8-99aa-90f1c7d6c4c1.png)
![image](https://user-images.githubusercontent.com/40289574/44305021-968a0780-a3b0-11e8-8bba-9d0c161f50ac.png)

Files to fix: https://drive.google.com/open?id=1Ube1AnLhFNsz9VOyDaqWo4bPFbNkiKBT

**Comment by Perfare** [comment]
This game uses its own special format, you can modify the code below to support it.
https://github.com/Perfare/AssetStudio/blob/9f482b7cf98935da247a1c89c9c6e3ee75a9fa8c/AssetStudio/Classes/Texture2D.cs#L72-L83
to
```
var m_StreamingMipmapsPriority = reader.ReadInt32();
var m_StreamingGroupID = reader.ReadUInt32();
```
https://github.com/Perfare/AssetStudio/blob/9f482b7cf98935da247a1c89c9c6e3ee75a9fa8c/AssetStudio/Classes/Mesh.cs#L610-L613
to
```
var m_UsedForStaticMeshColliderOnly = reader.ReadBoolean();
```
