### ISSUE TITLE
能导出资源，能不能加个导入？

### ISSUE THREAD

**Issue by mindoff6502** [Perfare/AssetStudio#254]
我看有个软件叫AssetBundleExtractor，也是Unity资源导出，但是部分资源比如说图像，可以直接编辑，导入新内容，也可以导入Raw数据，测试发现同版本自己的文件可以替换，所以能不能研究下，加入这种功能？代码是你写的话应该不难？2年前手动试过替换图像资源，似乎只要验证文件头部大小，以及更新后的纹理偏移就可以替换小图为大图。不知道作者能不能研究下加入这种方便的东西，让软件更好更方便。

**Comment by Perfare** [comment]
有UABE用就行了，这功能不是说写就能写的

**Comment by mindoff6502** [comment]
有什么难点么？可以一起研究下？我觉得既然有人能写出来，并且你又可以正确写出解包，封包问题应该也不太大才对。并且我2年前写过替换，似乎并不是不可能，也成功了。只是有工具能直接支持似乎更好。还是说有其他不太方便说的顾虑？
