### ISSUE TITLE
Model > Export selected objects (with animation clip) error.

### ISSUE THREAD

**Issue by Galaxyzd** [Perfare/AssetStudio#256]
Every time I try to export with animation clip or without it returns the following error. I have made sure to try and check if the CAB file is in use. Which it absolutely not. 

![image](https://user-images.githubusercontent.com/16174954/44852288-1773b980-ac63-11e8-8620-8ca3fea005e2.png)

The following error might also be related:

![image](https://user-images.githubusercontent.com/16174954/44852402-70435200-ac63-11e8-880d-dbc62c994348.png)

**Comment by Perfare** [comment]
Please open a new issue and upload the file to me.
