### ISSUE TITLE
Export selected objects with AnimationClip seems to still be broken.

### ISSUE THREAD

**Issue by Galaxyzd** [Perfare/AssetStudio#257]
![image](https://user-images.githubusercontent.com/16174954/44861391-b820a400-ac78-11e8-96c5-03ed4ee762e6.png) 
Which file do you need exactly @Perfare?

**Comment by Galaxyzd** [comment]
@Perfare I've tried twice now but my chrome crashes when I upload it because I think it's too big. The file is Steam\steamapps\common\Rust\Bundles\shared\content.bundles. Hope you've got the game already, model where this error occurred on is the LR300 mesh.

**Comment by Galaxyzd** [comment]
Okay got it working. WinRar did an excellent job compressing 5.5GB down to only 2.5GB.
Sorry for the delay!

https://mega.nz/#!T4d0xYBZ!DGKlgLNQZoq6JwXZcuVt_El4ndrH3-igz7LnWMiMyu4

**Comment by Perfare** [comment]
I have not encountered any errors on this model, which AnimationClip did you choose?

**Comment by Galaxyzd** [comment]
I have just got all these selected as in the picture and no others. When I try to export with AnimationClip it doesn't work. If I choose export selected objects it comes out without any animations.
