### ISSUE TITLE
AssetStudioFBX is using VS2015 but AssetStudio is using VS2017.

### ISSUE THREAD

**Issue by leozzyzheng** [Perfare/AssetStudio#260]
If I don't upgrade AssetStudioFBX to VS2017 and new windows SDK, I will need install both VS2015 and VS2017, is it safe to simply upgrade AssetStudioFBX to VS2017 or just commit the upgraded AssetStudioFBX so that others won't need think whether to upgrade it.

Thanks!

**Comment by Perfare** [comment]
你可以使用任何vs版本打开AssetStudioFBX，只需要修改目标平台版本和平台工具集
另外在vs2017上也是可以安装windows SDK 8 和 v140工具集的
不使用v141的原因是可以让用户少安装一个Microsoft Visual C++ 2017 Redistributable
