### ISSUE TITLE
i Extract Models With T-Pose/Skeleton with AssetStudio

### ISSUE THREAD

**Issue by PredatorXUchiha** [Perfare/AssetStudio#267]
Hey How Can i Extract Models With T-Pose/Skeleton with AssetStudio

**Comment by Perfare** [comment]
I'm sorry I do not quite understand your question

**Comment by nigthshadex** [comment]
> 
> 
> I'm sorry I do not quite understand your question

Some of the models exported doesn't appear to display them in a bind pose. Like in a animated posed, like some would import them sitting down or doing weird poses, instead of bind pose.

**Comment by Perfare** [comment]
The common reason is because the model does not have a t-pose frame.
