### ISSUE TITLE
Suggestion: separate open and export directories

### ISSUE THREAD

**Issue by epikus29** [Perfare/AssetStudio#268]
I don't know how difficult that would be to implement, but could you make it so that 'Load file' saves the file directory separately from 'export selected objects', so that the menu opens at the last location imported and not the last location exported to?
It would make the import process much smoother, since quite some time can be lost if you have your unity files deep on your HDD (games installed from Steam for example) and want to save the files in a folder you made just for storing assets.
Thank you in advance!

**Comment by Perfare** [comment]
I finally decided not to implement this function, you can paste the address in the address bar of the Dialog to make the import process much smoothe.
