### ISSUE TITLE
.bytes file extracting as .txt

### ISSUE THREAD

**Issue by alphadrive** [Perfare/AssetStudio#269]
I have multiple Unity files which the latest build of AssetStudio (v0.10.0.86 as of the time of writing this) is able to load and recognise as containing two exportable assets when "Display all assets" is enabled.  One of the listed assets is listed as type "AssetBundle", while the remaining asset is recognised as a "TextAsset". Attempting to extract the TextAsset file will yield a .txt file with what appears to be serialized/binary data.

However, the serialized data of the AssetBundle asset actually seems to reference the TextAsset file as a ".bytes" file, which AssetStudio seems to be capable of recognising and decompressing into more assets when these were encountered with other games (at least when the .bytes file is actually another AssetBundle file itself). The .txt files that are extracted in this case don't seem like they can be read or recognised by AssetStudio as they don't contain the usual file headers attached to .unity3d and .assets files -- however, their filenames have me fairly convinced that they contain various game assets and multimedia files.

I've attached one of these Unity files which I'm fairly sure should contain some kind of sound file in the text/bytes asset (the text asset in this one has "BGM" in its path name). Please let me know if I should attach more samples to help with the issue, and I apologise if this is actually not a problem concerning AssetStudio itself.

https://mega.nz/#!jeRjGabC!6mHq4ONShxQO1hn-Nr1w94Ktk-QEjTgPYEW41E1dX2o

**Comment by Perfare** [comment]
The suffix name can't represent anything, because most of the TextAsset types in the asset are TXT files, so AssetStudio adds a .txt suffix to the export. If you think it is a .bytes file, why not rename it?

**Comment by JuGGerNaunT** [comment]
@alphadrive https://docs.unity3d.com/Manual/class-TextAsset.html

**Comment by JuGGerNaunT** [comment]
TextAsset doesn't has any specific format. It is any file that developer put in Unity project and named *.bytes, or *.txt or *.json. It could be compressed image, binary data for AI, json for visualization items in shop or information about some structure. Anything that dev decided.

**Comment by mani901** [comment]
![Screenshot (17)](https://user-images.githubusercontent.com/77674233/105033261-ae7e7d80-5a79-11eb-8e9e-4c77a60460c6.png)
how to read this text asset
