### ISSUE TITLE
Need too much memories to unpack assets.

### ISSUE THREAD

**Issue by mnixry** [Perfare/AssetStudio#271]
I used to unpack a very big assets,and it was crashed.
I use a newest version(v 0.11.3),and the software spent much memories over 4096MB,then it crashed.
I tried to use an x86 version to solve crash problem,but the software crash faster than x64 version,and I disabled "Enable Preview" Option.
The asset I want to unpack is an Android application.The orgin .apk pack is about 1.5GiB.I make sure about It's an Unity application.
My computer have 8192MB memories,GTX 760 GPU(the GPU have a little bit problem) and i5-3470 CPU.Using Windows 10 system.
You can download the .apk pack via [Here](https://pkgdl.biligame.net/games/wmlabsshl_1.4_1_20180925_181534_489248.apk)

----------------
Thank you very much.(I'm not good at English,sorry)

**Comment by Perfare** [comment]
既然内存不够的话，分开读取不就好了？本来就是分了很多assets，没必要一口气全部读取

**Comment by mnixry** [comment]
不是很懂为什么会占这么多内存（Unity Studio 0.9还没这么多占用来着）
另外不是很了解Unity确实不知道还有分开读取这种操作

**Comment by JuGGerNaunT** [comment]
@Perfare But it isn't normal. AssetStudio allocate 3.5Gb memory for 750Mb asset bundle files, it is almost x5.

**Comment by Perfare** [comment]
bundle类文件AS为了减少io操作会直接在内存中解压，所以会占用比原始文件更多的内存
另外.net的内存管理机制对于解压中所使用到的内存并不一定会立即释放
内存占用过多的话可以考虑一次别载入太多的文件就行
