### ISSUE TITLE
bones/rigging issue's with Dragalia Lost

### ISSUE THREAD

**Issue by Demonslayerx8** [Perfare/AssetStudio#273]
in the latest version, almost every single model has a broken bone structure, besides the main character, and the main dragon model, but sadly, upon exporting, there is no rigging data saved with those 2 models.
![image](https://user-images.githubusercontent.com/17195757/46903694-56657380-ce8d-11e8-8b22-c702c3c44577.png)
![image](https://user-images.githubusercontent.com/17195757/46903698-60877200-ce8d-11e8-9b87-e97308a3c505.png)

As for the other models, chars and dragons, they all have broken bone structures.
![image](https://user-images.githubusercontent.com/17195757/46903157-10f17800-ce86-11e8-9968-b6d9fcc747b6.png)
![image](https://user-images.githubusercontent.com/17195757/46903161-1e0e6700-ce86-11e8-9e94-ed556e0a3f23.png)

Another thing I'd like to note is that even animations aren't exporting.
[Dragon - Pele broken bone structure.zip](https://github.com/Perfare/AssetStudio/files/2475233/Dragon.-.Pele.zip)
[Dragon (Spoilers) with proper bones on export.zip](https://github.com/Perfare/AssetStudio/files/2475243/Dragon.Spoilers.with.proper.bones.on.export.zip)
[Character - Main Hero with proper bones (High Poly).zip](https://github.com/Perfare/AssetStudio/files/2475249/Character.-.Main.Hero.High.Poly.zip)
[Character - broken bone structure.zip](https://github.com/Perfare/AssetStudio/files/2475257/Character.-.broken.bone.structure.zip)

**Comment by Perfare** [comment]
Bone issue should be fixed in f15ee038b4f8aeb17e7b21fa4f30d0801278877a
These files do not contain any animation information, you need to find the file where the animation is located and export it manually.
