### ISSUE TITLE
Crashing assets.

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/AssetStudio#274]
Another batch for you to see whats up.

https://mega.nz/#!ngVxQAJa!O0-jyN-xlZLftmLQqpCH2CUfJ6rueiUMhZHCcEC4H3A

**Comment by Perfare** [comment]
I checked these files
9b8520d52ff1ee87700c386eae8f5a50.unity3d - d1a2724ebc1bca49d1bc915794589352.unity3d
14937d5d43c7a045c064207648ec11d8.unity3d - bb06aecb7a317eb73e8ef514a807bc7d.unity3d
3d042fccbe057a89c32d90472f8416e0.unity3d - d731f3dac475a9a284a90986481ba37b.unity3d
4b0e4bd1b7075138374248fc98fc4781.unity3d - 50de007dfd5d0f78ac68f68d320f1384.unity3d
8fbd64ff43b482dea004ca71e24be55b.unity3d - 717ea1b71630c58131f5f079c3ae99b7.unity3d
b9d19bc1ed10778383e417696b044321.unity3d - e49ee672c37a4963bc7cc6691384a526.unity3d
Each of these two bundles has same structure and file name.
For details, you can use the Extract folder to confirm.
In my opinion, one file is an updated version of another file.
AssetStudio cannot load two identical files at the same time.
One suggestion is to clear the game's data and re-download the data to ensure that all files are up to date.
