### ISSUE TITLE
Export not keeping files in seperate folders and merges them into one big folder.

### ISSUE THREAD

**Issue by Xanthor** [Perfare/AssetStudio#277]
When I load the Unity resource files in, the program displays each section they belonged to which is fantastic, but wont display unless you look in the asset list by single item. When I export the entire list, there are a lot of errors but my main concern is the file structure it shows in your program doesn't seem to carry over to the export, and just puts all the graphics items into one HUGE folder, instead of keeping them together in separate folders like it shows in the program. 

Do you have a main website, and also do you take donations? Despite the above issues, your program has saved me a lot of grief. I like making mods for several games, and one I have taken an interest in has just about no mods, despite it being pretty popular. Looking into the mod section, the developers put out a demo file structure, without leaving any information what so ever on block/pixel size, frames, limitations, etc. The developers just got up and left, and the one person who made a workable mod who obviously had this information got themselves vac banned from the looks of it. I looked high and low for a program that would extract a Unity games graphics and everything that claimed to do this, didn't and was about to just give up when I came across Asset Studio. With this I was able to not just understand the games graphical structure, I was able to find the sound structure as well. Even though everything got lumped in one folder, I can at least get enough information to make a better mod. Great program btw.

**Comment by Perfare** [comment]
AssetStudio will only keep the source path when you load the bundle file and check "Display asset original name". Other situations will only be grouped according to the way you choose.
