### ISSUE TITLE
3d models curves

### ISSUE THREAD

**Issue by jahhat** [Perfare/AssetStudio#278]
from the game the long dark, animated 3d character models

![2](https://user-images.githubusercontent.com/29805338/47345027-77f70400-d6b2-11e8-8614-ddcd0bf058ef.PNG)
![default](https://user-images.githubusercontent.com/29805338/47345298-14210b00-d6b3-11e8-9677-7656a7a8e686.PNG)

**Comment by jahhat** [comment]
[CINE_Convict.zip](https://github.com/Perfare/AssetStudio/files/2507355/CINE_Convict.zip)
[Uploading CINE_Methuselah_manual_export.zip…]()

**Comment by jahhat** [comment]
[CINE_Methuselah_manual_export.zip](https://github.com/Perfare/AssetStudio/files/2507362/CINE_Methuselah_manual_export.zip)

**Comment by Perfare** [comment]
What software are you importing? I did not find obvious errors on the fbx file. Try to export to 7.3 or 6.1 version of the fbx file.

**Comment by Perfare** [comment]
Did not encounter this problem in Unity or 3ds Max, I think it is a compatibility issue with fbx, try using other software to import.
