### ISSUE TITLE
Sprites export "chopped off"

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#279]
So I'm playing around with a game called Bloons TD 6, and so I wanted to export some sprites. In the file preview and as well as when they're extracted, though, the sprites are a bit "chopped off". Idk if this applies to any other game as I haven't used this program with anything else, but it happens here and I'd love if it'd be fixed! I tried exporting the same sprites in other tools like DevX and they exported perfectly fine with nothing chopped off.

Also, suggestion: I'd really love to see bundle modifying come! Currently the only tool to do this is UABE, but I feel like if AssetStudio were to have modifying features it'd make it a whole lot better because I love this program's UI and performance compared to UABE's.

Below is an example of a "chopped off" sprite
![image](https://user-images.githubusercontent.com/42720004/47348741-fb8b0380-d666-11e8-9c8b-f37c1cf178d6.png)
^ How sprite looks in AssetStudio and when extracted by AssetStudio
![image](https://user-images.githubusercontent.com/42720004/47348864-3d1bae80-d667-11e8-83ac-696fcc7d5093.png)
^ How it's supposed to look (taken from DevX)

**Comment by BowDown097** [comment]
The file? Like the direct .png exported by AssetStudio or the Texture2D it reads off of?

**Comment by Perfare** [comment]
Original assets file.

**Comment by BowDown097** [comment]
Alright, it's like 300 MB so how should I upload it?

**Comment by Perfare** [comment]
You can upload to mega or google drive

**Comment by BowDown097** [comment]
https://drive.google.com/open?id=1gIrz8pxa9yV2pxsg3ZD2t37WsJj6o-fi
Here it is

**Comment by Perfare** [comment]
Fixed in e13b4489c3b5749b9265c1b627fe1d1b21c1ca78

**Comment by BowDown097** [comment]
![respect](https://user-images.githubusercontent.com/42720004/48178957-6710da00-e2d1-11e8-87eb-a8dc6740e51b.png)
