### ISSUE TITLE
*.lua.bytes Unrecognized

### ISSUE THREAD

**Issue by bournes** [Perfare/AssetStudio#281]
*.lua.bytes Unrecognized

**Comment by JuGGerNaunT** [comment]
https://github.com/Perfare/AssetStudio/issues/269

**Comment by alphadrive** [comment]
@bournes If AssetStudio is managing to extract it as a .txt file, then I recommend trying to open it with Notepad++ or a hex editor -- if you're lucky, there may be a file header in the .bytes file hinting at what type of file it actually is (though I've also seen cases where it appears to be unreadable binary).
