### ISSUE TITLE
ability to control far and near clip plane

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#283]
3d preview now is really super cool thing to work with!
but sometimes models are really big (lke model of a level in 'Hard West') and clip plane is clipping the near and far model when I zoom so there's no way to see the details of a model.

It would be nice to have some control over these clip planes OR don't clip at all to be able to zoom at any level without lose model.

Here's a screenshot of how it look like:
![levelm](https://user-images.githubusercontent.com/24209966/47491945-95fc6a00-d854-11e8-91e8-e80a65341c80.png)

**Comment by Perfare** [comment]
First of all, this problem is beyond my ability. In addition, if you want to observe the model in detail, it is recommended to use other professional software after exporting.

**Comment by Tosyk** [comment]
so it's impossible to change that clip planes? I'm sure there a line of code that defines these frotn/back cuts. can you check if you have a time?

**Comment by Perfare** [comment]
I am completely unfamiliar with opentk, so even if there is code that works, I don't know how to do it.

**Comment by Tosyk** [comment]
okay, I got it
