### ISSUE TITLE
character skin of 'Hard West' are broken

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#284]
here's a link to sharedassets2.assets:
https://drive.google.com/file/d/1pQ9BhW2peI0LrGc-XIRza589VxrX5E87/view?usp=sharing

characters are in t-pose but parts of them are unpositioned and their skeletons are broken

**Comment by Perfare** [comment]
Some parts are in other files, need all the files to check for errors.

**Comment by Perfare** [comment]
Progress bar issue has been fixed.
