### ISSUE TITLE
How do I extract and apply a skeleton.atlas TextAsset to a model?

### ISSUE THREAD

**Issue by Masamiki0218** [Perfare/AssetStudio#286]
Hello. I'm trying to extract some King of Fighters All Star models with all of their bones.

However, when I export them normally, there's some bones that are lost. For example, as you can see here, this model's face lacks of any bones other than the ones to move the eyeballs (the rest of bones in his head are to move the hair, the hair band and the whole head itself).
![sin titulo](https://user-images.githubusercontent.com/13398181/47621191-64093300-daf4-11e8-8f5c-88d84ad837f3.png)
But checking the TextAsset file included with the model, and that I suppose its the model's complete skelleton used ingame, you can see it actually includes some lines for Eyebrows (and I imagine it also includes Eyelids, Mouth... but they aren't actually named like that since it's a Japanese game).
![sin t2itulo](https://user-images.githubusercontent.com/13398181/47621213-e134a800-daf4-11e8-9d5c-cc28c2d36dea.png)
So my question is...

### **How can I export the model mesh with this skeleton instead of the basic one it is using in the first image (so I can fully manipulate all of the face's features like the eyebrows?)**

**Comment by Perfare** [comment]
According to my experience, .atlas and .skel are spine files, has nothing to do with the 3d model.

**Comment by Masamiki0218** [comment]
Ohhh ok. Then I guess it is used for the animated 2D portraits? Thanks.

**Comment by alphadrive** [comment]
@Masamiki0218 if the model's coming out with a mostly correct skeleton structure, then there's a chance the face is animated using morphs/shape keys instead of bones.

It looks like you're converting the model to use with MMD -- try checking your "facial manipulation" panel for any options which might control the face, or go back to Blender (or whatever program you used to convert the .fbx file into a .pmd or .pmx file) and check if there're any shape keys that came with the extracted model. Searching around some of the issues, there _may_ have been some progress with getting AssetStudio to extract models properly with morphs, assuming that's how your game is handling the facial animations.

**Comment by Masamiki0218** [comment]
> @Masamiki0218 if the model's coming out with a mostly correct skeleton structure everywhere else, then there's a chance the face is animated using morphs/shape keys instead of bones.
> 
> It looks like you're converting the model to use with MMD -- try checking your "facial manipulation" panel (in MMD) for any options which might control the face, or go back to Blender (or whatever program you used to convert the .fbx file into a .pmd or .pmx file) and check if there're any shape keys that came with the extracted model. Searching around some of the issues, there _may_ have been some progress with getting AssetStudio to extract models properly with morphs, assuming that's how your game is handling the facial animations.
> 
> If shape keys are included with the .fbx but not carrying over to pmd/pmx file, that's probably a problem with the plugin you're using to export to pmd/pmx format and isn't a problem with AssetStudio. If there're no shape keys with the fbx, then it _might_ be another morph issue assuming that's how the facial animation is actually being done with your game.

Ok, I checked what you said and it actually looks like the model came out with morphs by extracting the model contained in the "Animator" file. I was able to convert it from Blender to MMD correctly and looks like they work nicely. A shame though, since it doesn't have that many morphs, but this will do. Thank you!
