### ISSUE TITLE
Made Icon

### ISSUE THREAD

**Issue by 1dadou1** [Perfare/AssetStudio#288]
I am a design enthusiast
I made the AS icon. I can download it here. I hope you like it.
https://drive.google.com/open?id=1dL1r5qJ2iZJqT6PyKJ9A_pMFAZ10eBQR
![icon_01](https://user-images.githubusercontent.com/26129828/47701851-22909900-dc56-11e8-95c3-e004879b29e8.png)
![icon_02](https://user-images.githubusercontent.com/26129828/47701852-23c1c600-dc56-11e8-92ba-7c7427d2faa2.png)
![icon_03](https://user-images.githubusercontent.com/26129828/47701857-258b8980-dc56-11e8-8d5b-c38c0bb884f1.png)

**Comment by Perfare** [comment]
Got it, thank you for your help.
