### ISSUE TITLE
Texture2D ASTC 8×8

### ISSUE THREAD

**Issue by khanhhung1221** [Perfare/AssetStudio#290]
I just used your Assetstudio tool. Thank you very much for creating this great, practical tool for free.
However, the situation I encountered is as follows. When I try to view the texture file in compressed format like ASTC 8×8, I get a blank image (no content). I hope that you can solve this problem

**Comment by Perfare** [comment]
Please upload the assets file to me.

**Comment by khanhhung1221** [comment]
[ASTC DATA.zip](https://github.com/Perfare/AssetStudio/files/2540773/ASTC.DATA.zip)
Texture2D name: image
Unity 5.6.x

**Comment by Perfare** [comment]
Have you extracted all the files from AssetStudio.zip?
I tested this assets and it works fine.
I think you are missing astcenc.exe or Microsoft Visual C++ 2010 Redistributable
