### ISSUE TITLE
Can't find .resS file

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#291]
Game 'Sudden Strike 4'

Trying to extract 'gamedata' file. It's only 10mb and not the main data archive. Unfortunately it can't find a .resS files while extracting:
![image](https://user-images.githubusercontent.com/24209966/48120597-a284b780-e283-11e8-85e1-973845119a8c.png)

Also I search through the game dir and couldn't find any other resources except this folder:
![image](https://user-images.githubusercontent.com/24209966/48120696-ef688e00-e283-11e8-961e-b4856818c716.png)
I tried to copy these files to the data folder but it doesn't seem to work either.

**Comment by Perfare** [comment]
The file at the beginning of the CAB is usually in the bundle file, usually located in the StreamingAssets folder. 
Use the Load folder to read all game files, if you still have this problem, you can consider uploading the file to me, I will check it out.

**Comment by Tosyk** [comment]
In this game assets split into the type groups and stores within separate files like ' models' or 'unitymodels' with no extension. I actually like to export asset archives one by one to:
1. keep things separated
2. be sure that I'm not missed anything

and here's what is in 'StreamingAssets' folder:
![image](https://user-images.githubusercontent.com/24209966/48126927-8852d580-e293-11e8-9d4f-4794c3d25c25.png)

**Comment by Perfare** [comment]
Because the bundle file is compressed, it is not known which bundle the file is in before the load.
In addition to using the Load folder, you can also choose to extract all the buble files first using the Extract folder.

**Comment by Tosyk** [comment]
So after extracting I need to put all the files together and next my only option is to extract everything in one place?
