### ISSUE TITLE
textures exported not into the 'Texture2D' root

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#292]
Game 'Sudden Strike 4'

Most of the when I export models (FBX ASCII) the corresponded textures exported NOT into the '<path>\Texture2D\' folder but into '<path>\Texture2D\assets\models\animals\chicken\textures\'.

Is it possible to set it to actually '<path>\Texture2D\' folder(?) or choose texture folder from settings somehow?

**Comment by Perfare** [comment]
I think you should check the "Display asset original name", uncheck this will solve this problem.

**Comment by Tosyk** [comment]
thanks! it wasn't clear how it works though
so 'Display asset original name' sould be unckecked before asset file load into the 'AssetStudio' — it won't work on loaded asset archive.

**Comment by Perfare** [comment]
When you check "Display asset original name", if the asset has a path structure displayed in "Asset List" name column , it will be exported according to the path structure.
