### ISSUE TITLE
weird skeleton/skin behavior

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#293]
Game 'Sudden Strike 4'

asset 'horse_chr_02_animated' have a weird skeleton where all the bones appeares as dummies (if open in 3ds max) and it's not connected with mesh.

here's asset file: https://drive.google.com/open?id=1blMw8p7wE4u-wv8bdrv8PZdGX_Z7Vn3o

**Comment by Perfare** [comment]
I want to know if you have checked this issue on the new version. If there still is, I will continue to check it.

**Comment by Tosyk** [comment]
sorry for the late reply. I have same result with 0.12.00 and 0.12.60
![image](https://user-images.githubusercontent.com/24209966/48898059-d0a9f000-ee5c-11e8-817a-0133378d0e94.png)
