### ISSUE TITLE
'Texture2D' doesn't created in latest build

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#295]
'Export selected objects' doesn't create 'Texture2D' folder anymore.
also can export object folder have a name of root name (like it happen with 'Export selected objects (split)') instead of 'GameObject'?

**Comment by Perfare** [comment]
> 'Export selected objects' doesn't create 'Texture2D' folder anymore.

The behavior of the Export object has changed. Now the image will be placed in the same directory as the fbx file.

> also can export object folder have a name of root name (like it happen with 'Export selected objects (split)') instead of 'GameObject'?

I will consider changing it.

**Comment by Tosyk** [comment]
> The behavior of the Export object has changed. Now the image will be placed in the same directory as the fbx file
can you add an option to export textures in 'texture' folder as it was before? it's just for sake of resource organization

**Comment by Perfare** [comment]
Sorry about that, I finally decided to keep the current behavior.

**Comment by Tosyk** [comment]
is it hard to make something like this(?):
![image](https://user-images.githubusercontent.com/24209966/48690047-0db47f00-ebde-11e8-9052-e0214d678401.png)
