### ISSUE TITLE
希望可以让相同名称的文件也一起导出

### ISSUE THREAD

**Issue by fricyo** [Perfare/AssetStudio#296]
导出资源，已经存在的文件不会导出
希望能增加选项功能，相同名称的文件也一起导出
因为有些来自不同文件夹，内容是不相同的

另外
读取大量文件夹，有时解析到一半，程式会突然自行关闭
变成一次只能读取少量文件夹，才能正常执行
但不确定是否我电脑性能不足

非常感谢开发者！

**Comment by Perfare** [comment]
同类型同名字的文件在载入就会加上单独的ID，所以应该不存在同名问题.

**Comment by fricyo** [comment]
大部分文件会加上ID，但少数没有
我打包了两个这样的文件供参考
https://1drv.ms/u/s!AuUx3kmxL_oXaeIT2-qHQHkNCRg  (Onedrive空间)
一起载入只会出现一个文件，分别导入能发现实际有两个不同图片
而且由于我同时载入大量文件夹时会强制关闭，只能拆成少量批次载入
导出文件夹已存在同名文件就不会再导出了

**Comment by fricyo** [comment]
原来是这样，明白原因了，谢谢
那么导出时存在相同文件名，能不能增加功能选择不跳过，以(2)(3)...的方式也全部导出?

目前我发现一个方法，先使用Extract folder，再把文件全拉出来，就可以全部一起载入了，而且原先这情况的文件也都会产生不同ID
不过全部导出时，程序会突然自己关闭消失，只好分批导出

**Comment by Perfare** [comment]
相同名字在添加进assets list的时候就会加上单独的ID，所以不会存在同名文件。
如果是文件夹里已有的，建议新建文件夹。
最后的情况大概率是内存不足，如果是bundle文件建议先全部Extract到本地再进行载入。
