### ISSUE TITLE
crashes on model export

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#298]
Game 'Dead Trigger'

AssetStudio crashes on export models from this game.
here's link to the game: https://drive.google.com/open?id=1mycq13OGVPsnMwc31iouqvCS3eDece4D

**Comment by Perfare** [comment]
Which model you export causes a crash? I tested all can be exported normally.

**Comment by Tosyk** [comment]
it happened when use 'Export all objects (split)' option

**Comment by Perfare** [comment]
Yes, I use this test and it works fine.

**Comment by Tosyk** [comment]
I'll repeat this with new versions I use (26 and 16) and reply here

**Comment by Tosyk** [comment]
it works now with v0.11.16. here's settings I'm using:

![image](https://user-images.githubusercontent.com/24209966/48372067-7c6d7600-e6ce-11e8-8dd6-598ba92537aa.png)

**Comment by Tosyk** [comment]
everything is working now, thank you!
