### ISSUE TITLE
crash while Export selected objects

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#299]
Games 'Marvel Future Fight' and 'Frozen Free Fall'

I have crashes on random asset which I can't specify because I use 'Export selected objects' option.
here's a screenshot from future fight:
![image](https://user-images.githubusercontent.com/24209966/48319470-6eace780-e61f-11e8-99a3-90eea1f27216.png)

**Comment by Perfare** [comment]
Need files to check for this error.

**Comment by Tosyk** [comment]
Okay, I'll upload these two games in few hours.

p.s.: thank you for the feedback man, really appreciated

**Comment by Tosyk** [comment]
here's links
frozen: https://drive.google.com/open?id=15v84RD8ChzRyhXwbklU8T5RbRyMC120x
future fight: https://drive.google.com/open?id=1mrRGhTwrS5s7yiaI6S-u-5WBPiWybY06

**Comment by Tosyk** [comment]
on v0.11.27
got this for frozen (but no crash):
![image](https://user-images.githubusercontent.com/24209966/48373947-61056980-e6d4-11e8-94f3-e6be345a8527.png)
but 'Marvel Future Fight' exported just fine
