### ISSUE TITLE
weird geometry composing within FBX

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#300]
game 'Dead trigger'

it happened not only in this game but sometimes for other games too: when -mostly- level geometry (props) is doubling for some reason (see !cars folder) and transforming randomly. please see screenshots. link to the game: https://drive.google.com/open?id=1mycq13OGVPsnMwc31iouqvCS3eDece4D

![image](https://user-images.githubusercontent.com/24209966/48371839-e0dc0580-e6cd-11e8-9fb5-5acdf1814e22.png)

![image](https://user-images.githubusercontent.com/24209966/48371804-d02b8f80-e6cd-11e8-9fb6-a6b1e5efebbf.png)

**Comment by Perfare** [comment]
Please use the new export function to export FBX, the old function is deprecated and no longer supported.

**Comment by Perfare** [comment]
In addition, I hope that you will confirm whether your other questions about the model have occurred on the new version. If it happens only in the old version, please close them.

**Comment by Tosyk** [comment]
on v0.11.27
I'm getting correctly textured levels. but appearence is still chaotic:
![image](https://user-images.githubusercontent.com/24209966/48376375-c446ca00-e6db-11e8-8ae9-cf9dc58c30f5.png)

**Comment by Perfare** [comment]
As I said in #199 , there is still a location and rotation problem with each part and I don't know how to fix it.

**Comment by Tosyk** [comment]
yeah, I found one more issue (#29) with similar problem. so it seems it's not only v5 problem.
it's seems that this kind of geometry uses a matrix transformation tables of some kind.

**Comment by Perfare** [comment]
Just close this issue because now it is the same as #199
