### ISSUE TITLE
can't export model without animation in v0.11.27

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#303]
I might do something wrong but I can't export models without animation (v0.11.27) with option 'Export selected object'
so if I want a reference pose I always get first frame of included animation.

**Comment by Perfare** [comment]
I don't think this is a problem. You can choose whether to import animation when importing fbx files into software like Blender or 3ds max.

**Comment by Tosyk** [comment]
I've checked 3ds max and you were right — there's an option called 'No animation' which pose the models into its initial pose wheather it's first frame of the animation or t-pose if present.

though if it's not too much I hope you can separate animation and model by addressing issue #304
