### ISSUE TITLE
textures not applied automaticaly when import in external tools like 3ds max

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#305]
on v0.11.27

when I import models into 3ds max the textures (diffuse) are applied automaticaly on v0.11.16 but not on v0.11.27.

when I export models with v0.11.27 and import them into 3ds max the name of the texture is present in the material editor but not seen in the scene whatever I try

**Comment by Perfare** [comment]
Only added scalefactor feature in v0.11.27.
If you set the scalefactor to 1, will this problem still happen?

**Comment by Tosyk** [comment]
that's weird

I've tested it in 3ds max 2013 (I'm using 2009) and textures applies normally. I've tested scale factor 1.00 and 1.08.

also, 2013 version has full path to the texture in the material but in 2009 version material has only texture name.

p.s.: I don't use newer 3ds max versions because they're slow and laggy for my machine and 2009 works perfectly.

**Comment by Perfare** [comment]
Obviously this is a compatibility issue with the FBX version.
7.5 - 2016
7.4 - 2014
7.3 - 2013
7.2 - 2012
7.1 - 2011
Changing the exported version of fbx should solve this problem.

**Comment by Tosyk** [comment]
thanks, I'll try this evening and will reply back here

**Comment by Tosyk** [comment]
whatever I tried textures are not showing.

p.s.: also scale doesn't work for 3ds max 2009 :/
