### ISSUE TITLE
Error Extracting Texture2D and possibly Sprite [V: 0.11.30]

### ISSUE THREAD

**Issue by HeresHavi** [Perfare/AssetStudio#307]
Hey Prefare,

Here are the files:
Thank you for your time! <3

https://www59.zippyshare.com/v/rWud7NLo/file.html

**Comment by HeresHavi** [comment]
![afbeelding](https://user-images.githubusercontent.com/39027816/48508213-46ef9680-e84e-11e8-966e-06f2a7eff566.png)

**Comment by Perfare** [comment]
You are missing [Microsoft Visual C++ 2013 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=40784) or [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840)

**Comment by HeresHavi** [comment]
> 
> 
> You are missing [Microsoft Visual C++ 2013 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=40784) or [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840)

Thank you. I forgot to install these since I formatted my PC. Fixed the issue. I apologize.
