### ISSUE TITLE
Index was outside of bounds of the array (Book of unwritten tales 2)

### ISSUE THREAD

**Issue by cesm1980** [Perfare/AssetStudio#308]
In the game The Book of Unwritten Tales 2 many models and animators gives a strange error when trying to export models with bound animations or animators, one of them, the animator "nate_avatar_prefab" (with the EXPORT-SELECT ASSETS option) gives this error (i am using the latest 0.11.30 version :

![animator](https://user-images.githubusercontent.com/42876695/48510378-a5ffdc00-e84b-11e8-9754-dff6ca0acc9d.jpg)

Or the corresponding model with animations, using the option EXPORT SELECTED OBJETS:

![model](https://user-images.githubusercontent.com/42876695/48510383-aa2bf980-e84b-11e8-80be-a7ae4dcf37c4.jpg)

It's strange that the animator and model the same names and the errors seem to be different, perhaps because the extraction method was run by different functions on the top down menu. Anyway here's the asset i got this from, i think it's not necessary to upload others since the errors are the same, i think.

Is there any fix for this, or it's simply yet another unsupported game?

Asset link : https://mega.nz/#!o9lHDIzQ!j8owQ0K-Q1b9I5BunoroOKu2q7zbBeu862mZtTjfXuM

**Comment by Perfare** [comment]
Fixed.
