### ISSUE TITLE
Error when exporting model from CSR2

### ISSUE THREAD

**Issue by MoparHellcat** [Perfare/AssetStudio#311]
Hello! Firstly, thank you for your work, great software! I found something, please check this if you can.
1. When I trying to export some models from CSR2 game, I got this error

![error](https://user-images.githubusercontent.com/45193069/48756186-87696d00-ecb1-11e8-9b20-d9bed67cb59c.jpg)

2. Also, another strange thing. In options I change format textures to BMP. But textures always converted in PNG when I exporting models from menu "Model" or "Export".
When I exporting textures manually from Asset List tab (Exporting selected assets), textures exporting in BMP.

**Comment by Perfare** [comment]
Please upload the game files to me.

**Comment by MoparHellcat** [comment]
[Ford_Mustang_302_1970.zip](https://github.com/Perfare/AssetStudio/files/2603134/Ford_Mustang_302_1970.zip)
Getting this error when trying to export LOD_A model. Also, I tried to export model with AssetStudio.x64.v0.10.0.80, and export ended successfully.
