### ISSUE TITLE
LZ4 decompress mismatch when extracting some bundles of KiraraFantasia

### ISSUE THREAD

**Issue by Rambin** [Perfare/AssetStudio#312]
https://github.com/Perfare/AssetStudio/blob/8c749e21e14ea9d0d9bd9d21ab34cbc80146ecb2/AssetStudio/BundleFile.cs#L208

I debugged the code, when I try to extract a .muast file from KiraraFantasia, data decoded at BundleFile.cs:L208 is less than that said in blockInfo.uncompressedSize. I don't understand LZ4 algorithm, so I can't determine what happened here. Can anyone help?
In additional, these files have a 4-bytes offset in the header, with unknown meaning.

我尝试在调试时对きららファンタジア(闪耀幻想曲)中的一些.muast文件进行ExtractFile操作，跟踪到BundleFile.cs:L208时，发现经过Lz4DecoderStream解压的数据长度小于blockInfo.uncompressedSize，使得解压后的数据错误，最终导致读取图片的时候出现大片花屏现象。我不懂LZ4算法所以也不知道这里到底出了什么问题，希望有人能指点一下。
另外这些解压有问题的文件存在一个4字节的不明头部，使正常的头部偏移了4字节，不知道是否是这个的影响。

**Comment by Perfare** [comment]
上传一下有问题的文件给我

**Comment by Rambin** [comment]
感谢
没有百度盘，上传OneDrive了
https://flyme123-my.sharepoint.com/:f:/g/personal/rambin_flyme123_onmicrosoft_com/EgzofzZOd8xBtoqHWjhZ3z8BaFsvPtbXCuuFErHjkfn2Pw?e=5BBLmI

**Comment by Perfare** [comment]
文件应该还要再进行处理，具体的只能去逆向了.
