### ISSUE TITLE
Issues with extracting Angry Birds 2 OBB assets (Android)

### ISSUE THREAD

**Issue by DanteMele** [Perfare/AssetStudio#313]
![image](https://user-images.githubusercontent.com/30186527/48820578-5d906480-ed0a-11e8-8b61-b6b24cb80e49.png)

This error appears while extracting Angry Birds 2 OBB Unity assets, any way/plan to fix this?

**Comment by Perfare** [comment]
Please upload the game files to me.

**Comment by DanteMele** [comment]
http://www.filedropper.com/main2230005comroviobaba

**Comment by DanteMele** [comment]
Another problem, the game uses a global-metadata.dat for its assembly, is that usable for viewing its monoscripts?

**Comment by Perfare** [comment]
Use my another tool [Il2CppDumper](https://github.com/Perfare/Il2CppDumper) to create dummy dll, then load them to dump MonoBehaviour.
Sprite issue Has been fixed.

**Comment by DanteMele** [comment]
Ok. I have the dummy DLLs, just tell AssetStudio to use them?

**Comment by Perfare** [comment]
When you first click on MonoBehaviour, you will be asked to select the directory where the dll is located.

**Comment by DanteMele** [comment]
Yes I did that.

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
