### ISSUE TITLE
Cant preview and export any audio

### ISSUE THREAD

**Issue by FarlandsRedstone** [Perfare/AssetStudio#315]
I tried to export some music in rortos's game airlinecommander but every time it show error and nothing happen.other features are ok

**Comment by Perfare** [comment]
Need game files to check for this error.

**Comment by FarlandsRedstone** [comment]
it s too big:( You can download it at Google play store.it called Airline
Commander

**Comment by Perfare** [comment]
What error did you encounter? I tested this game and everything works fine.
