### ISSUE TITLE
Is can't work on 2018 3.0b12 version , it will close.

### ISSUE THREAD

**Issue by Icetric** [Perfare/AssetStudio#318]
Is can't work on 2018 3.0b12 version , it will close.

原来能用中文……在2018 3.0b12的时候会闪退~~

就是用AssetStudio打开下面这个的时候会闪退
链接: https://pan.baidu.com/s/1CEuo0sZqLcChhtKCnfKOUg 提取码: necn

**Comment by Perfare** [comment]
好了
