### ISSUE TITLE
v0.8.0.0版本或v0.9.0.0版本能导入资源,最新版本反而导入会崩溃

### ISSUE THREAD

**Issue by yayangyang** [Perfare/AssetStudio#319]
[yasuobao.zip](https://github.com/Perfare/AssetStudio/files/2652624/yasuobao.zip)

**Comment by yayangyang** [comment]
level2有时可以读取,看看我的截图,我找到另一个不可以读取的,
截图:[yasuo.zip](https://github.com/Perfare/AssetStudio/files/2659881/yasuo.zip),
不可以读取的那个文件大一点发不上来,
可看:https://pan.baidu.com/s/1TU1WymKiNMcsQXTf2xEXcg

**Comment by Perfare** [comment]
resources.assets的问题已修复
AssetStudio处理External文件时会搜索所在文件夹下所有文件包括子目录，所以你第二次操作的时候level2还没载入完成，因为还在搜索xternal文件
