### ISSUE TITLE
How do I extract and apply a skeleton.atlas TextAsset to a portrait from KOF ALL STARS?

### ISSUE THREAD

**Issue by XenonKusanagi** [Perfare/AssetStudio#322]
Hello. I'm trying to extract some King of Fighters All Star portraits but when I try to open .skel files in Spine, shows error message during export. For example I try to assemble this portrait.

![image](https://user-images.githubusercontent.com/45806359/49841348-e3895380-fd7c-11e8-853b-a2af21dbb28b.png)

I know you need an .atlas, .json file and obviously the image, but in this case only .skel and .atlas are included.

![image](https://user-images.githubusercontent.com/45806359/49841517-7fb35a80-fd7d-11e8-873f-9b602bb9552b.png)

So My question is...

**How I can export or open .skel files in spine or another software?**

Here are files in case someone wants to support me.
[Kyo98.zip](https://github.com/Perfare/AssetStudio/files/2670157/Kyo98.zip)

**Comment by Perfare** [comment]
Obviously you raised the question in the wrong place.
You should go to the place related to spine to ask questions instead of here.
It is recommended to use Google to find your answer.
