### ISSUE TITLE
Suggestion: Ability to see what scene an asset is from in preview

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#325]
A game I mod has a very big asset bundle, containing 40+ scenes. When I'm trying to mod an asset, I have to search through every single individual scene file and find out where the asset is located. 

So, here's where the suggestion comes in: It'd be great for in the top left corner where the asset details are (width, height, etc.) to also show what scene an asset is from. For example, if a Texture2D asset is included in a scene named "BuildPlayer-MainMenu", it could say in the top left corner with the asset details "Scene: BuildPlayer-MainMenu". This would make it a lot easier for locating where a particular asset is for modification in a tool like UABE.

**Comment by Perfare** [comment]
You can right click "Show original file" on the asset to see which file the asset is in.

**Comment by BowDown097** [comment]
> 
> 
> You can right click "Show original file" on the asset to see which file the asset is in.
Ya ik, but I was asking about showing what scene an asset is in, in the Scene Hierarchy, because if an asset bundle has multiple scenes each scene will have its own assets.
