### ISSUE TITLE
Automatically deletes empty GameObjects?

### ISSUE THREAD

**Issue by brandondsantos** [Perfare/AssetStudio#328]
Greetings! First off, I would just like to thank you for creating such an amazing and useful application. However, I am having a problem in Asset Studio 12 in which the application automatically deletes empty GameObjects on export. Is there possibly a workaround to this? Any help on this would be greatly appreciated. Thanks in advance!

**Comment by Perfare** [comment]
Please elaborate on "automatically deletes empty GameObjects".
