### ISSUE TITLE
Meshes cannot be exported, opening a file crashes latest version

### ISSUE THREAD

**Issue by tiramisu6** [Perfare/AssetStudio#332]
Hi! The subject game is 'Animal Crossing: Pocket Camp' and attempting to open a unity3d file in the latest version of AssetStudio (x64 and the other) will crash the program halfway through the loading process for any file from it.

Textures seem to export fine in AssetStudio.x64.v0.10.0.76 but clicking on a mesh results in an unhandled exception error. Exporting the mesh from the Model tab will export it as fbx, but then the program crashes afterwards and the fbx is actually messed up.

Here is a small unity3d file from the game I uploaded on DBREE. https://dbr.ee/WkjF
I tried to attach the zip to this post but it doesn't work.

**Comment by Perfare** [comment]
Fixed in e602a5cf3b2fd3168fcccadcc6349b5e14dd8ac2

**Comment by tiramisu6** [comment]
Thank you!
