### ISSUE TITLE
FBX不能导出问题

### ISSUE THREAD

**Issue by BigFaceCat2017** [Perfare/AssetStudio#333]
[DR_4.zip](https://github.com/Perfare/AssetStudio/files/2706556/DR_4.zip)

直接用中文了，附件是个U3D打包的资源文件，里面有个FBX格式的文件，但是使用了最新版本的，却无法导出，还请解决一下

**Comment by Perfare** [comment]
可以导出啊

**Comment by BigFaceCat2017** [comment]
> 可以导出啊

我使用的是刚下载的最新版0.12.35，提取附件的DR_04，只能得到obj文件，却导不出fbx文件，obj是缺少蒙皮信息的。不知，你这边是否是选项上做了配置才能导出的还是什么情况？

**Comment by Perfare** [comment]
在"Scene Hierarchy"勾上DR_04，使用Model菜单导出

**Comment by BigFaceCat2017** [comment]
感谢，能导出了，但是还是缺少蒙皮信息。在Asset List界面，Name为DR_04的这个文件，应该是个Animator，但是工具却识别成了Mesh，导致缺少了蒙皮信息。所以，虽然导出了FBX文件，但是还是没有蒙皮信息。这个不知道该如何解决

**Comment by BigFaceCat2017** [comment]
补一下，这个文件，我用Unity Assets Bundle Extractor查看文件数据，是可以看到骨骼和蒙皮数据的，而用AssetStudio没识别到，所以这块可能代码方面还是有点问题

**Comment by Perfare** [comment]
为什么你会这么执着的认为是AssetStudio的问题？整个文件只有一个transform连child和father都没有，请截图告诉我你说的骨骼和蒙皮数据在哪儿？

**Comment by BigFaceCat2017** [comment]
![image](https://user-images.githubusercontent.com/26595691/50441603-6f32e080-0936-11e9-9e0a-f03168ba6792.png)

这个是我用Unity Assets Bundle Extractor 找到的蒙皮数据

**Comment by Perfare** [comment]
这不只是告诉你骨骼权重吗，骨骼数据在哪呢？m_BoneNameHashes是空的，SkinnedMeshRenderer里m_Bones也是空的，请问骨骼数据在哪？
