### ISSUE TITLE
导出的FBX缺失动画

### ISSUE THREAD

**Issue by BigFaceCat2017** [Perfare/AssetStudio#334]
[data.haozip04.zip](https://github.com/Perfare/AssetStudio/files/2708432/data.haozip04.zip)
[data.haozip01.zip](https://github.com/Perfare/AssetStudio/files/2708433/data.haozip01.zip)
[data.haozip02.zip](https://github.com/Perfare/AssetStudio/files/2708434/data.haozip02.zip)
[data.haozip03.zip](https://github.com/Perfare/AssetStudio/files/2708435/data.haozip03.zip)
附件太大，所以拆包上传了。用AssetStudio最新版打开后，选择名为ZepetoBaseModel的Animator并随便选一个对应的AnimationClip，例如ANI_001，虽然可以导出，但是导出的FBX缺少动画。
不知是什么原因引起的

**Comment by Perfare** [comment]
AssetStudio不支持humanoid动画
#221 #314
