### ISSUE TITLE
Exported fbx bones still not parented correctly

### ISSUE THREAD

**Issue by MisterPrawn** [Perfare/AssetStudio#335]
I opened up #330 before, and it said the issue was fixed, but for some reason, I'm still having the same issue from before where the bones aren't parented to their respective bone. They're still parented to the root bone, for some reason.
![image](https://user-images.githubusercontent.com/27305795/50426911-d83f2900-084e-11e9-8c04-c94a4f1f0e44.png)

I'm using a different model for an example, because it affects this game Nickelodeon Super Brawl Universe, too. Any help would greatly be appreciated: https://mega.nz/#!sEY3yaaa!qvYvp8AdWj5j3eSqR9NfEWKRO5Ir7HT4dwf3lKHLTxQ

Also Perfare, would it be possible to add you on Discord? I feel messaging you directly about these kinds of issues would be better as a whole. Thanks.

**Comment by HeresHavi** [comment]
I think it would be nice to have a Discord Server for AssetStudio. What do you think Prefare?

**Comment by Perfare** [comment]
I close #330  issue because it is not the reason for AssetStudio. Just like I replied to you in #330 ,Avatar define these skeletal parent-child relationships, Avatar sets the father of these bones to root, AssetStudio just exports according to these data.
