### ISSUE TITLE
MonoBehaviors are blank on Windows IL2CPP?

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#337]
A game I mod has been ported to Windows and is compiled in IL2CPP. When I try to open the resources.assets, it asks for an Assembly folder. No matter what folder I select in the game's directory, the MonoBehaviors contain no content. Looking through the file in a text editor though and using the content that's in the Android version as a reference, the MonoBehaviors clearly contain content. What do I do and can this be fixed?

**Comment by Perfare** [comment]
Use my other project [Il2CppDumper](https://github.com/Perfare/Il2CppDumper) to generates dummy dlls, When asked the Assembly folder, select the dummy dlls folder.
