### ISSUE TITLE
Lost UVs

### ISSUE THREAD

**Issue by Supurreme** [Perfare/AssetStudio#338]
When attempting to export the models from the game Little Witch Academia - CoT the mesh and bones are converted successfully but the UV maps are totally lost. it seems to be this way with all models in the game

**Comment by Perfare** [comment]
Please upload the game file to me.

**Comment by Supurreme** [comment]
here are some samples: https://sta.sh/0coggtdcqko

**Comment by Perfare** [comment]
I tested the file you provided, all UVs are work fine.

**Comment by Supurreme** [comment]
really? it must be something on my end then because they always end up like this
![image](https://user-images.githubusercontent.com/42794233/50507872-494c2f80-0a4d-11e9-8e7e-e1fb06ec80a0.png)
