### ISSUE TITLE
Yet another suggestion: Ability to see the Path ID of all assets

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#339]
I believe there should be a way to see what the Path ID of an asset is. Now yes, I know if there are multiple assets with the same name you will be able to see the Path ID of the copies, but the ability to see the Path ID should be available on any asset, possibly in the name or added as a section in the asset list along with Name, Type, and Size. This would be convenient because some other programs that analyze and modify Asset Bundles do NOT display the name of assets like MonoBehaviors, and they are all just "unnamed asset", and the only way to locate particular assets in an Asset Bundle in these programs is their Path ID.

**Comment by MichaelPriebe** [comment]
Thank you for your work :)

**Comment by Perfare** [comment]
Added in versions after 0.14.12.
