### ISSUE TITLE
Some types of assets are not shown in Asset List

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#340]
Looking at a .assets file in UABE, I see there are 29 types in this assets file:
Animation, AnimationClip, Animator, AudioClip, AudioSource, Avatar, CGProgram, Canvas, CanvasRenderer, GameObject, Material, Mesh, MeshFilter, MeshRenderer, MonoBehavior, MonoScript, ParticleSystem, ParticleSystemRenderer, PreloadData, RectTransform, Shader, SkinnedMeshRenderer, SortingGroup, Sprite, SpriteAtlas, SpriteRenderer, TextAsset, Texture2D, and Transform.

In AssetStudio, only 10 of those 29 types are shown:
AnimationClip, Animator, AudioClip, Font, Mesh, MonoBehavior, Shader, Sprite, TextAsset, and Texture2D.

Why aren't the other 19 showing?

**Comment by Perfare** [comment]
No, AssetStudio doesn't need these things and they can't be exported to resource file.
