### ISSUE TITLE
Super Mario Run (CDN) asset .stir minor assetbundle encryption

### ISSUE THREAD

**Issue by DanteMele** [Perfare/AssetStudio#342]
I know there's a way to decrypt these files with .stir in the name to plain Unity3D assetbundles one at a time  with this script: "https://gist.githubusercontent.com/Treeki/b26c3668014cb408ce092243e7eeed33/raw/5b3747f436b035a16bdc9f6ed46cb312449e552a/unstir.py" but can anyone make up a way to decrypt all these files in a single folder with one command or add support for .stir compressed assetbundles? http://www.filedropper.com/smrstircompressed

**Comment by Perfare** [comment]
About decryption problem, you can't get any help here, I suggest you go somewhere else.
