### ISSUE TITLE
FBX Import Issues

### ISSUE THREAD

**Issue by MARK2580** [Perfare/AssetStudio#343]
Hello. 
I have already tried many times to export character models from various Unity games using your program, but I constantly receive warnings in 3ds max when importing FBX.

**Incomplete BindPose [nodes parents]**
`The following parent and/or ancestor node(s) is/are not part of the BindPose definition.`

**Skin Modifers Import (0)**
```
The Initial position (or Initial Pose) of the skinned objects is missing. 
The plug-in will create a pose automatically but running the 
'Assume Skin Pose' command may create unexpected results.
```

How can I fix this? I tried different versions of FBX, binary or ASCII, even different versions of 3ds max. Always the same.

**Comment by Perfare** [comment]
Only these information can't know what the problem is.
But if it's just a warning, consider neglecting it.

**Comment by MARK2580** [comment]
Unfortunately, this warning is displayed not in vain, the center of the model is heavily biased, and the morpher modifier is completely broken when trying to export.

**Comment by Perfare** [comment]
Need source asset file and fbx file you exported.

**Comment by MARK2580** [comment]
I apologize for not answering for a long time. Here are the original archives from the game and the resulting FBX. Actually, in the FBX itself, the morphs work fine, but it is clearly noticeable that the model is biased and after exporting to the format I need, everything breaks down completely (most likely due to the notification of the displaced center and another)
Look in the archives for a model named Vickie
[https://mega.nz/#!QJwREQAL!qRKiy0Q2fSzwfdvRn5XmUp5okDjiSFw-WINNyibXdmM](url)

**Comment by Perfare** [comment]
BindPose warning has been fixed. The center problem is not the cause of AssetStudio, the Transform information in the source file is like this.
