### ISSUE TITLE
Stuck on export all split and crash on individual export

### ISSUE THREAD

**Issue by 09williamsad** [Perfare/AssetStudio#344]
Hello

I am trying to extract assets from the Unity game Warhammer 40,000: Mechanicus.

After loading the folder (or files) if I use "Model > Export all objects (split)" then it will get stuck on the file "TechpriestModel.fbx", the program does not become unresponsive or crash, it just continues to use CPU and RAM but does not make any progress.
If I try to export this model individually then I get this error, this happens with a few of the models objects: 
![capture](https://user-images.githubusercontent.com/23011550/50739480-ee4ad300-11d8-11e9-8c7e-e9d05cf729e4.PNG)

Troubleshooting tried:
Running as admin.
Closing all other programs except antivirus.
Loading individual asset files.
Exporting all other files in the asset file, all others work without issue.
Versions x64.v0.12.40, x64.v0.11.31, x64.v0.10.0.88 and v0.12.37.

However UnityStudio.x64.v0.9.0 is able to export the model so I do not think it is a file problem unless it is ignoring the error.

This one model would not be a major problem but it stops the "Export all objects (split)" process and I find that easier than exporting the files individually, espically as there are other assets in the same file.

File here https://mega.nz/#!aHYVCCiJ!HrMNe3abvA97BVeQE8PNn6KRffoyOZ_YxOuR4M8ucME

**Comment by Perfare** [comment]
TechpriestModel contains a lot of things, and it takes a while for AssetStudio to export it.
The error on the picture has been fixed.

**Comment by 09williamsad** [comment]
> 
> 
> TechpriestModel contains a lot of things, and it takes a while for AssetStudio to export it.
> The error on the picture has been fixed.

How long should it take?
I am trying it again now, it has been around 5 mins and the progress bar has not moved while unity studio 0.9.0 exports it in seconds.

**Comment by Perfare** [comment]
Go to the folder to view, when the fbx file is generated, the export is actually completed. As the progress bar does not move, it is a problem of fbx sdk, it takes a very long time to clean up the memory.

**Comment by 09williamsad** [comment]
> Go to the folder to view, when the fbx file is generated, the export is actually completed. As the progress bar does not move, it is a problem of fbx sdk, it takes a very long time to clean up the memory.

I can see that the textures export without issue, its just the fbx that does not export/finish as it is not in the folder.
Other than waiting an unknown amount of time is there any way around this? (other than unity studio 0.9.0)
