### ISSUE TITLE
The mesh exported may be not correct

### ISSUE THREAD

**Issue by yuan227301** [Perfare/AssetStudio#347]
The mesh opened in Unity 2018.2.11f1 looks like it's been lost some surface when looked through behind.
![image](https://user-images.githubusercontent.com/18180849/51172839-14662680-18ef-11e9-9544-bcdfade6a56d.png)
![image](https://user-images.githubusercontent.com/18180849/51173550-9f93ec00-18f0-11e9-8ef2-7c18f9a1558b.png)
Here is the assetbundle and fbx file:

[GameObject.zip](https://github.com/Perfare/AssetStudio/files/2759112/GameObject.zip)

Will you please check it?

**Comment by Perfare** [comment]
This is correct. In model view, it used some shaders. you can export mesh to obj to confirm the specific situation.
