### ISSUE TITLE
Crash on open this files, please check

### ISSUE THREAD

**Issue by fanghti** [Perfare/AssetStudio#350]
please check this files, they crashed on open
https://www.mediafire.com/file/db74ml37tao47pt/Samplecfqq.rar/file

**Comment by Perfare** [comment]
invalid asset file.

**Comment by ngovandang** [comment]
Does that mean its not an Unity Asset?

**Comment by Perfare** [comment]
@ngovandang It is a Unity asset file, but it has some data that is different from the usual asset. cause unreadable.
