### ISSUE TITLE
UnityLz4

### ISSUE THREAD

**Issue by PriChama** [Perfare/AssetStudio#354]
I don't know if this format is old or new, but I found these files from a game "Garena Speed Drifters." They don't seem to load. Header is UnityLz4. I did manage to find a script to change into what looks like an actual AssetBundle format here; https://zenhax.com/viewtopic.php?f=9&t=7961&hilit=Unitylz4. I used it on one of the files provided. However it didn't work, it stopped at "read assets..." and crashed. It will open with AssetBundleExtractor though. (Author of that script says it doesn't work too, haha)

Just wondering if you could take a look at these, thanks! I also provided a few other samples. (That i didn't use the script on)
[sample.zip](https://github.com/Perfare/AssetStudio/files/2794460/sample.zip)

**Comment by Perfare** [comment]
UnityLz4 is not a unity format, the file processed by that script is also incorrect, even if UABE can load it, but data is wrong.
