### ISSUE TITLE
textures automatically to objects

### ISSUE THREAD

**Issue by runsrr** [Perfare/AssetStudio#359]
Is there a way to have the textures automatically added to the object when importing it into 3ds max?
When I import a scene which has a lot of objects they are imported un textured I would have to manually add the textures which can take a long time.

Is there a way to have the textures automatically applied to the object when exporting from AssetStudio?

**Comment by alphadrive** [comment]
AssetStudio does actually keep the textures linked to the objects when it can from what I've seen. It seems to fail more often when the object has a dynamic material or multiple skins, as well as when there're multiple textures associated with the one material (e.g. lightmaps, normal maps etc). It might be a good idea to upload a file so Perfare can test things if it's a resolvable issue.

**Comment by Perfare** [comment]
AssetStudio does actually keep the textures linked to the objects. However, in some cases, some programs cannot work and cannot fix this problem.
