### ISSUE TITLE
No animation data available for this model

### ISSUE THREAD

**Issue by brandondsantos** [Perfare/AssetStudio#361]
Hi, I'm trying to export an Animator from _Slender: The Arrival_, but, the Unity Editor doesn't import any AnimationClips. Did I do something wrong? I'd appreciate your insight on this. Thanks in advance!

![animatorselected](https://user-images.githubusercontent.com/29965024/52859720-6f13bd80-30fb-11e9-815b-31156785931d.PNG)
![noanimations](https://user-images.githubusercontent.com/29965024/52859722-6fac5400-30fb-11e9-8969-48e179dc4765.PNG)

**Comment by Perfare** [comment]
Sorry for replying you for so long, please upload the file to me, otherwise I can't check this problem.

**Comment by brandondsantos** [comment]
> Sorry for replying you for so long, please upload the file to me, otherwise I can't check this problem.

Hey, thanks for getting back to me. It's all good. So, I followed the Animator export instructions on the main page, yet it still results in this issue. I'd greatly appreciate it if you could solve and patch this issue. Thanks so much! 

All the best,
Brandon

[kate_mimxamo.zip](https://github.com/Perfare/AssetStudio/files/3015288/kate_mimxamo.zip)

**Comment by Perfare** [comment]
Although you don't provide source files, I judge from experience that these animations are humanoid animations.
AssetStudio cannot export humanoid animation.
You can use [UnityRipper](https://github.com/mafaca/UtinyRipper) to export.
