### ISSUE TITLE
Not exporting secondary UV Maps

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/AssetStudio#362]
Digimon World Next Order uses two uv maps one for the body, the other for the eyes, but only the body uv map is exported.

sample: https://mega.nz/#!NhAhxAIY!buqrb0aDqJlKLPwYmhDXnDgAfnZ0XIz-uRpve2d7IsI

**Comment by Perfare** [comment]
According to my research, the second UV in Unity is only used for light maps, not eye map. In this game it uses other ways to control eye maps.

**Comment by KekMcGee** [comment]
The game does use a secondary uv map for eyes, however they must also be controlled by another thing as the uv for the eye isn't scaled to the default eye. unless this uv isn't scaled right when ripped with UABE. Main UV Map: https://i.imgur.com/2mXSw7G.png Secondary UV Map: https://i.imgur.com/iUihZeE.png . If it isn't because it's ripped broken, they must have some UV scaling params.(which I think I just figured out) https://i.imgur.com/OHdgxlZ.png
