### ISSUE TITLE
Shape keys not exporting properly when two materials present on one model

### ISSUE THREAD

**Issue by Eutow** [Perfare/AssetStudio#364]
Im having trouble exporting a model properly with the shapekeys intact on both sides. The model contains two materials for both halves, and only the right side gets working shapekeys, while the left side gets keys that are garbage or otherwise do not make sense or function at all. Id like to keep the model private from others, but I can send you it through E-Mail or an alternative method if you would like to take a look.  Thanks.

**Comment by Springtraph** [comment]
Have you tried:
- Exporting each individual elements seperately
- Using different tools to preview the said model's shape keys

**Comment by Eutow** [comment]
Im not sure what you mean by exporting things seperately, since this is a fully rigged model with a full armature. However, I know the shape keys are working, because I can load the asset bundle into unity, but I cannot make changes to it due to the nature of what it is. Essentially I loaded the asset bundle into a live view, and I can make any changes to it, but they cannot be truely saved. Again this is because of where the model is from, and why I need to extract it.

**Comment by Springtraph** [comment]
Can you send the model to sptemp376@outlook.com so I can recreate the issue?
