### ISSUE TITLE
error 0x8007000B when trying to preview/extract certain Texture2D

### ISSUE THREAD

**Issue by Matezoide** [Perfare/AssetStudio#366]
I cant find anything on this issue, but for some reason, there are several Texture2D files that i simply can not extract or even view. What can i do? I'm on Windows 10.

**Comment by UniqueUname** [comment]
Please provide related files so perfare can reproduce the issue

**Comment by Matezoide** [comment]
I am not able to check right now, but t was able to stop the issue by downloading a different version of the program. I'll get the related files asap.

**Comment by Matezoide** [comment]
Sorry for taking so long. This is the full error message.

https://imgur.com/a/VOVGXaf

This only happens on the x64 version. The error message when trying to preview is the exact same, except the error is 0x8007000B instead of 0x8007007E
