### ISSUE TITLE
Jittery/Unsteady animations after export

### ISSUE THREAD

**Issue by KindaDev** [Perfare/AssetStudio#369]
Is there any plan or a way to fix this? So far i tried with 6 different games and each time after exporting some character models with animations they're all messed up after importing (feet flying around) to 3ds max with this error "The following parent and/or ancestor node(s) is/are not part of the BindPose definition." Animations export is a huge step but if they won't work correctly it kind of makes it pointless.

Here are some samples from 7 different games, asset + exported fbx
https://clicknupload.org/drldfzd06aak
https://www16.zippyshare.com/v/fYAu1mTt/file.html
https://sendit.cloud/kojo6iebbcne
http://uppit.com/hg3j2ow0sboa
https://ddl.to/irau8dc7dd5r
https://www.file-up.org/ud7v6hmxkvzs

**Comment by KindaDev** [comment]
12 games now, same thing, such a shame :(

**Comment by Perfare** [comment]
Fixed the BindPose issue in the new version, but not sure if it has been completely repaired.

**Comment by KindaDev** [comment]
Yes i just checked some models, seems like the "floating feet issue" is still there sadly, but the warnings while importing are gone. Do you plan to investigate it any further? In current state animations aren't very usable :( I'm not an expert so i can't guess what causes that feet floating problem, but it would really be a waste to leave it like that, because it almost works.

**Comment by KindaDev** [comment]
I've noticed something else now
![bug](https://user-images.githubusercontent.com/48205519/53957030-9861b100-40dd-11e9-8e63-2fb74b770a73.png)
Squashed head and twisted fingers

here are samples asset + fbx
[orc.zip](https://github.com/Perfare/AssetStudio/files/2941220/orc.zip)

**Comment by Kendaman** [comment]
I wonder why you don't reveal any game titles. I think I can not do enough testing.
Usually, this kind of "sliding / floating" occurs when the reflection of the scaling ratio is wrong.

**Comment by KindaDev** [comment]
Any mobile unity game, happens in 99% cases. Game titles are all chinese/korean and i provided enough samples from various games to test.

**Comment by Kendaman** [comment]
It does not occur at least in the games I have tried. KOF ALLSTARS and Dragonball Legends etc. 
What game is the last orc you presented? I want to try to see if the same phenomenon occurs with other models.
I can not say for sure, but it seems that there is a problem in reflecting the ratio rather than a tool failure. It has nothing to do with Unity, but there was a similar problem with FF14 before. It was solved by Xentax when I done, but a lot of verification is needed to check the scale ratio.

**Comment by KindaDev** [comment]
I dont have most of the names, because i don't need them, but i uploaded more samples from this game
[more samples.zip](https://github.com/Perfare/AssetStudio/files/2961544/more.samples.zip)

Also i don't think there is a need to upload samples from this certain game, as every sample i uploaded previously has exactly the same problem after exporting.

**Comment by Kendaman** [comment]
No need to upload, just the title. now, I understand that this game is "Darkness Rises".
Anyway, I will try to see if the same problem occurs and I will try fix it using animation software.

At least, I think Perfare has done enough work. The format is slightly different depending on the game, and it is impossible to support all of them.

**Comment by KindaDev** [comment]
I've tried about 30 games now since discovering this tool, same problem in all of them, so i think its a matter of how it exports cetrain things, its 30 games, if it was 5, ok not supported format or whatever, but 30? Seems like a common problem. I've also uploaded samples from 7 different games, so i think its enough to figure out what that thing is exactly that causes "sliding".

**Comment by Perfare** [comment]
I did see some problems with the model, but I am sorry I can't fix it.

**Comment by KindaDev** [comment]
It's not about the model, it's about unsteady/floating animations on every sample i provided here, will you do something about it or it won't be fixed also?

**Comment by Perfare** [comment]
@KindaDev This problem is beyond my ability.

**Comment by KindaDev** [comment]
That's sad to hear, well maybe someday, somehow you will get it fixed.

**Comment by KindaDev** [comment]
Looking for a few mobile game examples with working animations, no swinging/floating etc. So far i tested around 70 games and this bug occurs in every single game, so if someone can give me a few examples of actually working game animations after export i'd be grateful.

**Comment by Perfare** [comment]
After so long, the export model has become more complete. After my testing, several of the problems mentioned above have been improved. You can download the new version of the test. If you have any questions, please open a new issue.
