### ISSUE TITLE
Export to BMP doesnt work

### ISSUE THREAD

**Issue by Gta5KoRn** [Perfare/AssetStudio#371]
Export to BMP doesnt work. The tool still exports to PNG.

**Comment by MARK2580** [comment]
I confirm, I also wanted to write about it. In any case, only png is exported.

**Comment by Perfare** [comment]
Currently exporting fbx can only export png images at the same time. In fact, whether it is exporting png or bmp texture data is the same.

**Comment by Gta5KoRn** [comment]
png or bmp texture data is NOT the same. BMP has the alpha channel and png not (its integrated in the RGB channel).

**Comment by Perfare** [comment]
@Gta5KoRn Png also has the alpha channel.

**Comment by Gta5KoRn** [comment]
> 
> 
> @Gta5KoRn Png also has the alpha channel.

sorry, but where? (Same texture extracted as BMP format [with AssetStudio.x64.v0.11.15] has the alpha channel)
