### ISSUE TITLE
no file was loaded

### ISSUE THREAD

**Issue by toddtom** [Perfare/AssetStudio#372]
博主，发现一个问题，我直接从PC上下载的apk，可以加载ab资源，但是如果是通过模拟器或者手机下载的apk，再传输到pc上的话，那么这个ab资源就无法load，并且提示no file loaded，麻烦博主查看一下是什么原因，顺便修复一下这个bug,感激不尽。PS：C++的代码我不是看的很懂，自己人用英文交流看着费劲，我就打中文了，请原谅我这么LOW

**Comment by Perfare** [comment]
99%是加密过的或者根本就不是U3D的文件
