### ISSUE TITLE
Power Rangers: Battle for the Grid [Switch]

### ISSUE THREAD

**Issue by Demonslayerx8** [Perfare/AssetStudio#377]
Bones are not exporting with the models at all, nor will animations. From what I see, bone names are stored in the main file for said character, and meshes in another. I can share more files if needed
[Green Ranger.zip](https://github.com/Perfare/AssetStudio/files/3012287/Green.Ranger.zip)

**Comment by Demonslayerx8** [comment]
Any updates, or shall I send more files?

**Comment by Perfare** [comment]
I am busy recently, I will check this issue when I am free.

**Comment by Perfare** [comment]
I have confirmed the problem and thought of a solution, but the two files are not related to each other, so it will be very troublesome.

**Comment by Demonslayerx8** [comment]
Gotcha. Will be waiting patiently.

**Comment by Demonslayerx8** [comment]
Checking in for progress/updates.

If nothing yet, then I'll wait till PC version is released this summer, but pretty sure same issue lays there too, maybe.

**Comment by Perfare** [comment]
I am sorry to have kept you waiting, and now the problem has finally been solved.
After the 0.13.5 version, load both files at the same time, then select them in the scene hierarchy
![QQ截图20190717125707](https://user-images.githubusercontent.com/12952226/61348225-6bdf5200-a892-11e9-9485-4120414f7654.png)
and
![QQ截图20190717125713](https://user-images.githubusercontent.com/12952226/61348230-6f72d900-a892-11e9-8cd3-02f1b5c29037.png)
Use Model - Export selected objects (merge) or Export selected objects (merge) with AnimationClip will be successfully exported.

**Comment by Demonslayerx8** [comment]
Awesome, works like a charm!
