### ISSUE TITLE
Texture2D无法导出，使用UABE可以导出

### ISSUE THREAD

**Issue by spdv123** [Perfare/AssetStudio#379]
AssetsStudio提示```Nothing exported. 1 assets skipped  (not extractable or files already exist)```，Texture2D文件可以预览，可以通过UABE导出

错误文件：
[error_file.assetsbundle.zip](https://github.com/Perfare/AssetStudio/files/3025011/error_file.assetsbundle.zip)

**Comment by Perfare** [comment]
测试没有任何问题，你导出的文件夹已有相同文件
