### ISSUE TITLE
Is there a cross-platform plan for macOS?

### ISSUE THREAD

**Issue by feicong** [Perfare/AssetStudio#38]
i compile source code with VisualStudio for macOS. but failed.
c# core tips missing ManagedFbx and System.Deployment Refecrences.

**Comment by Stellarspace** [comment]
@feicong You can build this program on macOS using Visual Studio for Mac with relatively the same steps as above, but you won't be able to run it natively. It's missing the ManagedFbx library because the CSPROJ file doesn't list the library properly. System.Deployment is included in .NET Framework 4.0, but not in Mono for some reason. You'd have to take it from Windows and put it on your Mac. Once again, you won't be able to run the program or use the program, so I don't even know why you bother.

**Comment by Perfare** [comment]
No plans for the time being, I don't have a macOS computer and lack of programming in macOS knowledge

**Comment by Sn0wBiT** [comment]
This is ManagedFBX library you are using ? https://github.com/returnString/ManagedFBX
If we could build this on Mac maybe we could run it.

**Comment by Perfare** [comment]
@Sn0wBiT This is it https://github.com/ordigdug/ManagedFBX

**Comment by Stellarspace** [comment]
It's already included in the source! You don't have to build the library. You can build Unity Studio on macOS using Visual Studio, I already tested it, but the syntax is different. https://www.mono-project.com/docs/gui/

**Comment by Stellarspace** [comment]
<img width="1320" alt="screen shot 2017-09-30 at 8 35 47 pm" src="https://user-images.githubusercontent.com/17728506/31050659-19ed5a0e-a61f-11e7-938d-bb6a8cb24068.png">
<img width="220" alt="screen shot 2017-09-30 at 8 35 53 pm" src="https://user-images.githubusercontent.com/17728506/31050660-1bbe74c6-a61f-11e7-9c23-b79b91ae5834.png">
<img width="212" alt="screen shot 2017-09-30 at 8 36 05 pm" src="https://user-images.githubusercontent.com/17728506/31050661-1cde55a6-a61f-11e7-9a77-3c3a3885f413.png">

Only if it worked...

**Comment by warleyc** [comment]
I tried to use virtualbox with a official windows 10 image on my mac and I installed the requirements but the program does not run, and there is no error message.

**Comment by fireundubh** [comment]
@feicong One of the main challenges of OS X compatibility is that AssetStudio makes use of a number of Windows libraries for features such as font rendering, as well as third-party dependencies that may or may not be OS X-compatible. AssetStudio could possibly be run through Wine.

@warleyc That error tells you what's causing the error (Windows Security Center) and how to solve it (Component Services administrative tool.)

**Comment by aidoTank** [comment]
> It's already included in the source! You don't have to build the library. You can build Unity Studio on macOS using Visual Studio, I already tested it, but the syntax is different. https://www.mono-project.com/docs/gui/
could you please  share your project? or  share how to deal the C++ library?

**Comment by aidoTank** [comment]
> It's already included in the source! You don't have to build the library. You can build Unity Studio on macOS using Visual Studio, I already tested it, but the syntax is different. https://www.mono-project.com/docs/gui/

could you please share how did you deal the C++ library?
