### ISSUE TITLE
Problem with mesh import

### ISSUE THREAD

**Issue by kontrq** [Perfare/AssetStudio#380]
When importing bundle files, model polygons are glued together or not imported at all.
![изображение](https://user-images.githubusercontent.com/36162440/55386091-61918600-5537-11e9-94d4-393a88093f45.png)
[asset.zip](https://github.com/Perfare/AssetStudio/files/3032913/asset.zip)

**Comment by Perfare** [comment]
This is not a problem with AssetStudio, this mesh is exactly what you see.

**Comment by kontrq** [comment]
There are a lot of polygons in the object, maybe there is an opportunity to increase the memory for importing files?  
uabe allows to export this object in obj, without gluing polygons.
