### ISSUE TITLE
Not exported correctly Texture2D.

### ISSUE THREAD

**Issue by mltdlo** [Perfare/AssetStudio#381]
When I try to export some Texture2D assets, it becomes weird:
![hitokoma_110](https://user-images.githubusercontent.com/49200206/55413262-f16d1980-55a3-11e9-86de-bef9b5653a09.png)

If use 'mikunyan' of Ruby library, can export correctly:
![hitokoma_110](https://user-images.githubusercontent.com/49200206/55413245-e9ad7500-55a3-11e9-8e62-c7d93aca8092.png)
https://github.com/Ishotihadus/mikunyan

But I want to export using Asset Studio. Thank you in advance.

The link of unity3d file is here:
[hitokoma_110.zip](https://github.com/Perfare/AssetStudio/files/3034603/hitokoma_110.zip)

**Comment by Perfare** [comment]
Fixed.
