### ISSUE TITLE
Error when attempting to view/extract Texture2D and Sprite (Unity 2018.3.7f1)

### ISSUE THREAD

**Issue by BowDown097** [Perfare/AssetStudio#382]
Whenever I try to view or extract a Texture2D or Sprite on an Asset Bundle, version being Unity 2018.3.7f1, each producing different errors, but similar. First picture is the error when viewing/extracting a Sprite, second is the error when viewing/extracting a Texture2D.
![image](https://user-images.githubusercontent.com/42720004/55461540-80c8fb80-55a9-11e9-9659-243f300bef5c.png)
![image](https://user-images.githubusercontent.com/42720004/55461575-99391600-55a9-11e9-92a2-6a01422371da.png)

Will provide Asset Bundle if needed.

**Comment by Perfare** [comment]
install 
- [Microsoft Visual C++ 2013 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=40784)
- [Microsoft Visual C++ 2015 Redistributable](https://www.microsoft.com/en-us/download/details.aspx?id=53840)

https://github.com/Perfare/AssetStudio#requirements

**Comment by BowDown097** [comment]
Ah, ok. That makes sense. I just got a new laptop today for modding so I was assuming that I was missing something.
