### ISSUE TITLE
I can not open libfbxdk.lib...

### ISSUE THREAD

**Issue by WanBenLe** [Perfare/AssetStudio#383]
I am a greenhand...
I can not open libfbxdk.lib...
1.I put fbbxsdk.h and other FBX file to
D:\VS2017\VC\Tools\MSVC\14.16.27023\include
2. copy libfbxsdk.dll  and 3 lib files(
x86 and x64 from
FBX\lib\vs2015\x64\release & FBX\lib\vs2015\x86\release
) 
to 
AssetStudio-master\AssetStudioGUI\Libraries\x86
and
AssetStudio-master\AssetStudioGUI\Libraries\x64
then I build solutions and show Error"can not open file libfbxdk.lib"
Can you help me?
Thanks.

**Comment by Perfare** [comment]
install [FBX SDK](https://www.autodesk.com/developer-network/platform-technologies/fbx-sdk-2019-0)
https://github.com/Perfare/AssetStudio#build

**Comment by WanBenLe** [comment]
Okay,another question ,can I export .resS file  such as resources.assets.resS?
Thanks.
伏地膜dalao.

**Comment by Perfare** [comment]
.resS用于存放同名assets里的大数据，需要依靠assets才能读取，不能单独打开
