### ISSUE TITLE
Facial expressions dont work

### ISSUE THREAD

**Issue by Thelittlegoomba** [Perfare/AssetStudio#384]
Ive tred a couple different .vrca files, and all of them export with broken shapekeys/visemes. Im unsure if this is just me not doing it right, or if it is a bug

**Comment by alphadrive** [comment]
Possibly related to #248 , which still appears to be being worked on.

**Comment by gcovers** [comment]
Hi, I have the same problem with morphs. Just load one with errors and not everyone else. The example character is from the Idolm @ ster Million Live game.

![Blender](https://user-images.githubusercontent.com/55722432/65819876-17dcdc00-e1f8-11e9-9c9c-beaab8475dba.png)
