### ISSUE TITLE
Separating parts to actual objects on FBX export

### ISSUE THREAD

**Issue by Gta5KoRn** [Perfare/AssetStudio#385]
Is it possible to make a setting to separate object parts to actual objects and not separated by material? For example doors, bonnet, body etc

**Comment by Thelittlegoomba** [comment]
On that note, Is there a way to stop it from seperating the mesh in general?

**Comment by Perfare** [comment]
@Gta5KoRn @Thelittlegoomba I'm sorry I don't quite understand what you said. Can you provide some sample files and describe it in more detail?
