### ISSUE TITLE
Sprites export cropped

### ISSUE THREAD

**Issue by Fartoviii** [Perfare/AssetStudio#386]
I wanted to export some sprites from cuphead. In the file preview and as well as when they're extracted, though, the sprites are a bit cut. I tryed to use 0.11.25 and latest version (0.12.49) but this not worked.
![111](https://user-images.githubusercontent.com/49483039/55894185-dd4c9c00-5be3-11e9-9e3e-68c7c7c3271c.JPG)

**Comment by Perfare** [comment]
Please upload the file to me.

**Comment by Fartoviii** [comment]
https://drive.google.com/file/d/17Q1E_NPumecbbJkcxNUNxXMPz_9e9Y4w/view

**Comment by Perfare** [comment]
Should have been fixed.
