### ISSUE TITLE
Zepeto, some model have bones, some doesn't, although ingame seems to has.

### ISSUE THREAD

**Issue by SmezMorePrakezz** [Perfare/AssetStudio#387]
I'm trying to export a cached model from Zepeto, a social app where you can make your 3D avatar and dressed them up, and interact with others (like Miitomo).

The process is when I load a game, when the game request model from Zepeto's servers, it's gonna be downloaded to Android\data\me.zepeto.main\cache\zepeto\assets\[random alphabet and numbers] Each file have no extensions and can be either PNG or Unity file(it has "UnityFS" header) I filtered all Unity files and load into the program. 

The problem is some model don't have bones when export to FBX, but in the game, it looks like it has. 

So the question is, is the model file that doesn't display bones, is it actually have no bone or the program can't find it.

[test file.zip](https://github.com/Perfare/AssetStudio/files/3093008/test.file.zip)

![image](https://user-images.githubusercontent.com/34295880/56340707-e5f13380-61dc-11e9-845b-5bc56ef436b2.png)

P.S. There's some model that seems to have physics eg, hair. And also, there's a base model in game's main APK that seem to have shape keys that I can't extract.

**Comment by Perfare** [comment]
May be related Animator or Avatar in other files, but at least the content in this file is what you see.

**Comment by mofish9** [comment]
@SmezMorePrakezz Hi, the latest Zepeto version seems to encrypted these cached assets and none of these files start with "UnityFS". Do you still know how to decrypt these cached resources? Thanks.
