### ISSUE TITLE
Exporting wheels model from CSR2 is not correct :(

### ISSUE THREAD

**Issue by ForsakenWorld** [Perfare/AssetStudio#388]
Hi! When I try to export wheels from CSR2's car assets, it exports as "4 wheels in one object", and I need to detach them manually, but in the game assets I see "stub" meshes, probably used by game to auto-detach (i don't know, but it might be). These stub meshes are unexportable. Can you add the feature to extract separated wheels? If you need some assets as example - I can send it to you.

**Comment by Perfare** [comment]
Sorry, AssetStudio does not add any such automatic editing features.
