### ISSUE TITLE
Cuphead Sprite Atlas Sprites not loading or exportable

### ISSUE THREAD

**Issue by CelestialAmber** [Perfare/AssetStudio#389]
AssetStudio fails to successfully load the individual sprites from Sprite Atlases from the latest version of Cuphead.

**Comment by CelestialAmber** [comment]
I also tried building an AssetBundle with a Sprite Atlas in 2018.3.11f1, and AssetStudio was able to load and view the Sprites.

**Comment by CosmicDreamsOfCode** [comment]
I tried the new Switch version of the game too and i can confirm the issue also happens there too, so it isn't just the PC version.

**Comment by Perfare** [comment]
Can you upload the failed file to me?

**Comment by CelestialAmber** [comment]
[atlas_title.zip](https://github.com/Perfare/AssetStudio/files/3119432/atlas_title.zip)

**Comment by Perfare** [comment]
Should be fixed in v0.12.58.

**Comment by CelestialAmber** [comment]
The sprites now work in the AssetBundles themselves, but when trying to load them from asset/resx files, the files arent able to get access to the assetbundles, and the Sprite files don't work. They also seem to replace the sprite files in the AssetBundles when loading everything.

**Comment by Perfare** [comment]
I am sorry that I did not understand. Can you upload the relevant files and explain in detail?

**Comment by CelestialAmber** [comment]
No, it's fine! The initial problem was the atlas sprites not loading at all.
What I mean is that the sprites in the sharedAssets files reference the Sprite Atlases  in the AssetBundles instead of including them in their respective sharedAssets files. However, AssetStudio seems to not be able to locate the needed Sprite Atlas through not being able to detect whether the sharedAssets file would need them or not.  As a result, when trying to load the game folder or the sharedAssets file itself, the sprites fail to load that are inside sharedAssets/resources, while the ones that are in the AssetBundle work.
[files.zip](https://github.com/Perfare/AssetStudio/files/3131008/files.zip)

**Comment by Perfare** [comment]
These Sprites don't specify the corresponding SpriteAtlas, so AssetStudio can only handle it when SpriteAtlas is loaded.
