### ISSUE TITLE
Textuse physical size is incorrect (?)

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#391]
I'm trying to find out precise resource size.

I have RGB24 texture inside the game IPA the size of which is 2 097 309 bytes (around 2mb):

![image](https://user-images.githubusercontent.com/24209966/56650689-3c082000-6690-11e9-822f-e0a87b596644.png)
here is it:
![image](https://user-images.githubusercontent.com/24209966/56650738-52ae7700-6690-11e9-948f-94e5698b95de.png)

when I export it I'm getting DDS texture which size is 2.66 Mb (2 796 348 bytes).

So, 2 097 309 bytes as shown in AS against 2 796 348 bytes in windows explorer. Can you explain where is the true?

also can you make an option to export original RAW resources? right now type Sprite exported as PNG and some Texture2D files exported as PVR or DDS. It's confusing what is what :)

Thank you for you hard work on this tool!

**Comment by Tosyk** [comment]
also, what is sprite? some info? script?
some full color graphic with weapons and with alpha channel Sprites are 1024*1024 but AS show it size as 12kb.

**Comment by Perfare** [comment]
First, the size of the Asset List is the size of the asset, not the size of the resource.
Sprite does not contain images, he stores information how to cut pictures from the corresponding Texture2D.
Second, when AssetStudio exports the image, it will be converted to BGRA32 format. So the size of the exported image will grow bigger.

**Comment by Tosyk** [comment]
thank you! things makes more sence now!
one more thing: size of each asset/texture2d/anything else is actual size in IPA as shown in AS? or it is calculated somehow?

I'm making game and choosing best compression methods for the resources
