### ISSUE TITLE
Preview not Available

### ISSUE THREAD

**Issue by FinnGamerUNL** [Perfare/AssetStudio#393]
I saw Fartoviii's issue with the cropped sprites (https://github.com/Perfare/AssetStudio/issues/386) and as I saw it fixed I tried to check on the Cuphead sprites, but it says Preview not available and I can't export them.

**Comment by Perfare** [comment]
Please upload the file to me.

**Comment by Frikjumno** [comment]
when I have opened my asset files from a game in assetStudio I want to be able to see the texture, but it is not visible, but when I open asset files from a game made in 2019 I see the texture but when I take a file that has been made in 2020 or 2021 I do not see the texture, what can I do or can you help me?
![image](https://user-images.githubusercontent.com/89388676/130432734-8c922158-a5eb-4aeb-8de8-b4c36b1068a9.png)
