### ISSUE TITLE
Some animations are not working.

### ISSUE THREAD

**Issue by kimgentius** [Perfare/AssetStudio#394]
Excuse me, I have some problem.
I exported models from dragalia lost, but some character's animations are not working.
I've tried many things but nothing worked.

Here is examples of success and problem : https://mega.nz/#F!4U4W0aoK!mEVGvHOOKuqJvRs3DbuVVg
(exported FBXs and original files are included.)

Thank you.

**Comment by Kendaman** [comment]
Maybe I can solve this problem. I have always focused on dragalia lost,
but I can not start it with the emulator and I can not download resources.

Brunhilda was able to animation in my environment (mesh).
I'm very interested these resources. If possible, can you email me once?

devyarou@gmail.com

Thanks.

**Comment by Perfare** [comment]
Should have been fixed

**Comment by kimgentius** [comment]
> Should have been fixed

Thank you very much!!
