### ISSUE TITLE
Crossfire Mobile Assets Won't Load

### ISSUE THREAD

**Issue by kim-sama** [Perfare/AssetStudio#396]
When I try to load CFM assets it says "No file was loaded"

Here are the files I'm trying to open: https://drive.google.com/open?id=1ynU0gh5B1YDRNrWk2CXo2zFl2QV2xtOh

**Comment by Sn0wBiT** [comment]
Where did you download full Crossfire mobile source? Can you give to me?

**Comment by kim-sama** [comment]
@Sn0wBiT I installed it on a android emulator and I copied them

**Comment by Perfare** [comment]
This game uses a custom asset layout so AssetStudio can't handle it.
