### ISSUE TITLE
Unity 2018.3.7

### ISSUE THREAD

**Issue by nbakulev** [Perfare/AssetStudio#399]
Not working properly with Unity up to 2018.2 am i right?
I'm trying to extract some assets from game build on Unity 2018.3.7 and it just crashes

**Comment by Perfare** [comment]
Should be supported, upload the file to me, I will check the error.

**Comment by nbakulev** [comment]
Please see this file https://gofile.io/?c=L5Ucns

**Comment by Perfare** [comment]
This is a very special case, I have fixed it, but maybe the code still needs improvement.

**Comment by nbakulev** [comment]
Thanks!
