### ISSUE TITLE
Unity meshes do not always use 16-bit indices anymore

### ISSUE THREAD

**Issue by naikrovek** [Perfare/AssetStudio#403]
https://github.com/Perfare/AssetStudio/blob/master/AssetStudio/Classes/Mesh.cs#L439

This isn't necessarily true anymore, though it is true by default on new meshes.  There is a way to specify that 32-bit indices be used if that is desired/required:
https://docs.unity3d.com/ScriptReference/Mesh-indexFormat.html 

I don't know if this is specified in the .asset file anywhere or if you are just expected to change to a 32-bit index if more than 65535 indices are present.

**Comment by Perfare** [comment]
In the asset file, m_IndexBuffer is the index information of all the submesh. one mesh can have multiple submesh. The index information of each submesh starts from 1.
