### ISSUE TITLE
export animator and multiple animation clip in 1 fbx file

### ISSUE THREAD

**Issue by Mejax** [Perfare/AssetStudio#404]
is it possible? my current work, have a lot of animationclip (and a single animator) in a single unity3d file. kinda tiring to work on each animation clip and export them one by one
[md_chr0189_2006_hq.zip](https://github.com/Perfare/AssetStudio/files/3233488/md_chr0189_2006_hq.zip)

enclosed is a example of the unity3d file i am saying. pardon me if it is already implemented

**Comment by Stellarspace** [comment]
The program has weird wording, so I don't know. I tried exporting and it didn't export the 3D Models with Normals.

**Comment by Perfare** [comment]
Using "ctrl" you can select multiple animationclip to export at once.
