### ISSUE TITLE
Missing Textures

### ISSUE THREAD

**Issue by Grendor** [Perfare/AssetStudio#406]
For some odd reason, on a few series of packages from more recent games, currently experimenting with those of 'Ghostbusters World', there's a bizarre case of some otherwise-present textures not appearing in AssetStudio at all. In-game and through material listing they are present or referenced, but within AssetStudio it seems not to be able to find them to be listed. In Ghostbusters World I've noticed that some of the specific textures also have PVR-based errors when extracting. The notable textures I've been able to find references of existing but not being loaded are the 'chairman' boss's diffuse texture, the Plague Doctor Ghost's entire set, and others are just flat out not present in the asset listing of AssetStudio and are therefore unable to be extracted.

**Comment by Perfare** [comment]
For PVR errors, you need to install the software in https://github.com/Perfare/AssetStudio#requirements.
Problem with image not found, I can be sure that it is not a problem with AssetStudio and cannot help you.
