### ISSUE TITLE
Can play but cannot export  AudioClip correctly

### ISSUE THREAD

**Issue by SwingCosmic** [Perfare/AssetStudio#407]
v0.12 x64，在解包某app时，可以正确预览AudioClip，但是导出文件全部是只有16Bytes的损坏的.m4a文件，文件内容大致这样：

`(random 4 bytes) | 00 00 00 00 | 00 00 00 00 | 01 00 01 00`

![isekai err](https://user-images.githubusercontent.com/20746516/59104084-2cece100-8963-11e9-920f-fe9439e821e0.png)

旧版本Unity创建的bundle(e.g. 2017.2)可以正确提取出.wav文件

**Comment by Perfare** [comment]
上传assets文件给我
