### ISSUE TITLE
Fbx export problem.object reference not set

### ISSUE THREAD

**Issue by Legendld** [Perfare/AssetStudio#410]
![Untitled](https://user-images.githubusercontent.com/42944297/60357224-5da8bf00-99d3-11e9-855d-ac7c1d0190d7.png)
this happens with all the models.
here is a link to the game 
https://mega.nz/#!qFFzgYIC!k5kZZEswuTu5Goof-KUPKCRn43MRa862WCN2rHYNhps

**Comment by YuRaNnNzZZ** [comment]
It's an issue with non-ASCII characters in the object name. I've tried to export an object with chinese string in the name, got the exactly same error.
![](https://yurie.thigh-high.club/2jr5ljnl.png)

**Comment by Perfare** [comment]
@Legendld @YuRaNnNzZZ I have fixed this error and can now handle non-ASCII encoding normally.
