### ISSUE TITLE
Load file doesn't load anything

### ISSUE THREAD

**Issue by fl1k** [Perfare/AssetStudio#412]
Title ^
game -> rust, assets.bundles file

**Comment by Perfare** [comment]
Confirm that the file contains "Unity" at the beginning and is not encrypted.

**Comment by YuRaNnNzZZ** [comment]
I think it's just the fact that the bundle is almost 4 GB in size that makes it very slow to open (up to the point that it looks like it's stuck)
The first 128 bytes indeed shows that this is a valid Unity package and is not encrypted in any way:
```
C:\Program Files (x86)\Steam\steamapps\common\Rust\Bundles\shared>head -c 128 assets.bundle
UnityFS    ♠5.x.x 2019.1.4f1     р4▲┐   o   Ы   C▲ ☺ P☺р4▲♀♦ h @   ♥ш↔;?↑"   ♦CAB-1506069bc9d373063cdcd07b62f336b51 P ?ю?и 9
```

And the file opens without any problems (even though it takes some time to decompress and eats a lot of RAM):
![](https://yurie.thigh-high.club/z0oe7nzz.png)

**Comment by fl1k** [comment]
Worked after reinstalling tho, prob the fact my RAM was full at the time ..
