### ISSUE TITLE
Crash when load folder

### ISSUE THREAD

**Issue by MikoAmoy** [Perfare/AssetStudio#413]
Tried to open the files from Little Witch Academia : Chamber of time (Especially the ress bundle)
but asset studio crashes when read the data. (Through the load folder option) 
the load file option for ress bundle didn't work.
Hope there's a solution.

**Comment by Perfare** [comment]
Upload the file to me.

**Comment by MikoAmoy** [comment]
it's too big sadly.

**Comment by Perfare** [comment]
If you don't upload a file to me, I can't check why the error occurred.
By the way, if the load file doesn't work, it means the file is invalid Unity file.
