### ISSUE TITLE
Allow exporting data without conversion

### ISSUE THREAD

**Issue by Missingmew** [Perfare/AssetStudio#414]
While im thinking of this specifically for audio, this could be expanded to be an option for all supported data types.
Instead of converting audio to pcm wave files by default, adding an option to keep them in their original format (e.g. as ogg vorbis) to avoid bloating up file sizes and possibly prevent additional loss when reencoding them.

**Comment by Perfare** [comment]
Will consider support, but it takes time to research the relevant code.
