### ISSUE TITLE
Error exporting models

### ISSUE THREAD

**Issue by JosephKnight12** [Perfare/AssetStudio#415]
![image](https://user-images.githubusercontent.com/30190759/61542475-4162d580-aa07-11e9-8c2f-dc810737c048.png)
it does not allow to export the file, and the program is closed when closing the message
the game is Idolmaster Starlight Stage

**Comment by Perfare** [comment]
Have you installed the [requirements](https://github.com/Perfare/AssetStudio#requirements) software and unzipped all the files?

**Comment by JosephKnight12** [comment]
yes, the three programs but I don't know if it is a program or computer error

**Comment by Perfare** [comment]
This is a .net error is not a program error, it may be your computer error.
