### ISSUE TITLE
export raw data to file

### ISSUE THREAD

**Issue by Fractal-Idea** [Perfare/AssetStudio#416]
i export MonoBehaviour asset, it saved as txt file, show detail info of the asset
can this tools export asset as raw file ?
i need raw file and convert it to custom format

**Comment by Perfare** [comment]
Supported.

**Comment by Fractal-Idea** [comment]
导出的文件含有不属于文件内的额外信息字节

预览窗口中显示文件大小 int m_size = 577
导出的 raw 文件大小是 680

通过 HexView 查看，
头部多了 asset 的文件信息：m_FileID m_PathID m_Enabled m_PathID m_Name 等
尾部多了 asset MD5 信息字节

可以只导出 文件原始内容，不包括这些 asset 的额外信息字节么？

**Comment by Perfare** [comment]
@Fractal-Idea 导出的就是asset的原始数据，并没有做任何加工，你认为不需要的数据请自行裁剪
