### ISSUE TITLE
Bones Aren't Exporting as Armatures

### ISSUE THREAD

**Issue by pessimistpancake** [Perfare/AssetStudio#417]
So, I was trying to export things from Dragalia Lost, but when I export the armatures, they export as these things instead of bones.
![Capture](https://user-images.githubusercontent.com/53163318/61606130-aa13a300-abfd-11e9-867f-82710b5d7650.PNG)
It still has an animation and I can play it, but the mesh doesn't move, only the bones(?)
The mesh has no vertex groups either... is this just something that happens in this specific game?

**Comment by Perfare** [comment]
What version of AssetStudio are you using? This problem is the same as #394  and has been fixed.

**Comment by pessimistpancake** [comment]
I'm using 0.13.5- maybe this error could have just been my fault somehow?

**Comment by Perfare** [comment]
Upload the relevant file to me, I will check the error.

**Comment by pessimistpancake** [comment]
Thank you, here's the model. 
[c100001_01.zip](https://github.com/Perfare/AssetStudio/files/3425476/c100001_01.zip) 
Or do you want me to upload the asset files as well?

**Comment by Perfare** [comment]
Need original asset file.

**Comment by pessimistpancake** [comment]
Right- here you go.
https://drive.google.com/file/d/10i8FoIECKliijuSg4wWEUYp9Uhx-MEYF/view?usp=sharing
I apologize, it's a pretty big file...

**Comment by Perfare** [comment]
It looks like everything is ok.
[c100001_01.zip](https://github.com/Perfare/AssetStudio/files/3437710/c100001_01.zip)

**Comment by pessimistpancake** [comment]
When I try to import the model you sent into Blender, it just gives me an error. Could the problem be that I'm using Blender? Maybe I should try an alternative.

**Comment by Perfare** [comment]
Thanks for your feedback, I found this error and fixed it, now Blender can import it normally.
[c100001_01 #248719.zip](https://github.com/Perfare/AssetStudio/files/3438046/c100001_01.248719.zip)

**Comment by pessimistpancake** [comment]
Okay, it seems to work perfectly now- thank you so much!!
