### ISSUE TITLE
Unity Version 2.5.5b4

### ISSUE THREAD

**Issue by bc15kle** [Perfare/AssetStudio#418]
Hello, when opening bundle from that version, AS crashes without warning and when opening a small bundle, there's no tree structure and can't see the texture 
![image](https://user-images.githubusercontent.com/42741373/61750342-d0784080-adad-11e9-8d1c-865b30c4123a.png)

**Comment by Perfare** [comment]
Upload the file to me.

**Comment by Perfare** [comment]
I am very sorry that I cannot consider supporting this file. The reason is #419

**Comment by bc15kle** [comment]
I understand, it's from a unity version that was never released to the public.
