### ISSUE TITLE
Program crashing when trying to load an asset bundle

### ISSUE THREAD

**Issue by ExtraOrdnary** [Perfare/AssetStudio#419]
Hello, whenever I try to load a bundle, the program crashes, would you be able to help me with that?

Here's the bundle
https://drive.google.com/open?id=1x6W33VF53-yzoSff8D_fafaihnTPJMqr

**Comment by Perfare** [comment]
This is a very early unity file, Its file header m_Version = 6 means it belongs to a version between 2.1 and 2.6. But what version is very difficult to identify. I am very sorry that I cannot consider supporting this file.
