### ISSUE TITLE
What no support export animclip?

### ISSUE THREAD

**Issue by DoraemonMiku** [Perfare/AssetStudio#420]

**Comment by DoraemonMiku** [comment]
啥时候支持导出动作数据(AnimClip)啊

**Comment by Perfare** [comment]
早就支持了，希望你能先看看README

**Comment by DoraemonMiku** [comment]
但是我导出不了不造为啥

**Comment by DoraemonMiku** [comment]
输出的信息：1 assets skipped,not extractable or files already exist。 跳过资源，不可导出？文件是亡者农药的assetbundle。
https://share.weiyun.com/5fWTs97
