### ISSUE TITLE
一个问题，

### ISSUE THREAD

**Issue by DoraemonMiku** [Perfare/AssetStudio#421]
导出资源的AnimClip时候输出的信息：
1 assets skipped,not extractable or files already exist。 
导出动作的时候总是会跳过，导出目录是没有同名文件的。
源文件是亡者农药的assetbundle。
https://share.weiyun.com/5ObanR8

**Comment by Perfare** [comment]
请先看README.md，AnimationClip无法单独导出
另外只支持Legacy和Generic的AnimationClip
