### ISSUE TITLE
little witch academia chamber of time export issue

### ISSUE THREAD

**Issue by Arymond** [Perfare/AssetStudio#422]
https://cdn.discordapp.com/attachments/600793966853488642/604319645272506381/diana_uniform_model

weights seem to be assigned to the wrong bones when imported in to blender.

**Comment by Perfare** [comment]
I tried to fix this problem, try using the latest version.

**Comment by Arymond** [comment]
i was not able to build.

**Comment by Perfare** [comment]
Download from here https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

**Comment by Arymond** [comment]
thank you works now.
