### ISSUE TITLE
[Suggestion] Point Filter for Sprite Exports

### ISSUE THREAD

**Issue by kaizokujin** [Perfare/AssetStudio#423]
Sorry if I missed this feature, but I think it would do wonders for preserving the sharpness of sprite assets with dimensions that have decimal values.
Bilinear blending is less than ideal.
![Hero_116_idle01](https://user-images.githubusercontent.com/53464218/62107389-52f47a80-b25c-11e9-9a7f-7e0b8b87949d.png)
![Hero_116_idle01](https://user-images.githubusercontent.com/53464218/62107394-57209800-b25c-11e9-8d6c-4298c634a9b2.png)

**Comment by kaizokujin** [comment]
Nevermind this, I looked at:
[https://github.com/Perfare/AssetStudio/commit/558adb0b66692412fa90252d7845d158bc91c83f](url)
Reverting the lines of code changed in that commit in the current build had the effect on the sprite exports I desired.

**Comment by Perfare** [comment]
Can you provide the source assets file? I want to do some research.

**Comment by kaizokujin** [comment]
I hope you don't mind a mega link. The compressed file was a little over github's max attachment size.
https://mega.nz/#!KtR2kYiQ!-Wi4GkPSd-SsN7qmCijvR_M78F7DWZN85_jDyQwjpvw
It will need to be extracted again to be viewed by your project. 
I'll be getting rid of the file when you're ready.

**Comment by Perfare** [comment]
@kaizokujin Already got it, thanks.
