### ISSUE TITLE
Why does the picture become lumpy when you extract the sprite?

### ISSUE THREAD

**Issue by Myodan** [Perfare/AssetStudio#424]
Why does the picture become lumpy when you extract the sprite?

I want to extract dot image.

Original: ![](https://imgur.com/9wdavmn.png“Original”)Export: ![](https://imgur.com/TLZD0Aj.png“Export”)

**Comment by Perfare** [comment]
I have received this feedback #423 and I will fix it later.

**Comment by Myodan** [comment]
Oh! Thank!

**Comment by Myodan** [comment]
Oh! Thank!

**Comment by Perfare** [comment]
Fixed, try to use the new version。
