### ISSUE TITLE
Unable To Open .resS File In Rust Game

### ISSUE THREAD

**Issue by quantumvenom** [Perfare/AssetStudio#427]
I was able to open a bundle using asset studio revealing three files in the _unpacked file which I will attach here, however I cannot open the RESOURCE or the RESS file inside

**Comment by quantumvenom** [comment]
https://drive.google.com/file/d/1d9EJ_2JxvuyPW6fK5DAp9aT8NOGhsdcH/view?usp=sharing

**Comment by Perfare** [comment]
The .resS file only stores data of the same name assets file, AssetStudio can read it when you open the same name assets file.

**Comment by quantumvenom** [comment]
but the assets file is nowwhere to be found

**Comment by Perfare** [comment]
According to your description, you are loading a bundle file. Because the bundle contains more than 4g files, AssetStudio will first extract the files to the local for easy reading. If you want all files, use File-Extract file or File-Extract folder.
