### ISSUE TITLE
Crashes When Trying To Open Unpacked Bundle, No Error Message/Code

### ISSUE THREAD

**Issue by quantumvenom** [Perfare/AssetStudio#428]

**Comment by quantumvenom** [comment]
Trying to open a assets file size:1.2GB asset studio just shuts down

**Comment by quantumvenom** [comment]
https://drive.google.com/open?id=1UlJyMdgRtcz2HnrFsMZFaKYrohm8WlOp here is the bundle I am trying to open

**Comment by XackuKekandos** [comment]
same problem
