### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by rouningjun** [Perfare/AssetStudio#430]
作者你好:
    我好像在其他论坛看过你的文章，貌似你是个中国人，我就不用英文说软件的问题了。
电脑系统:win10
软件版本:0.13.x(都存在这个问题)
解包文件类型:level 
问题描述:当我打开单个level进行解包时里面可以解出上百个模型， 模型都正常显示不存在任何问题。但，我进行输出时，只能输出很小的一部分，不知道是不是软件只能输出较小的模型，大一点内存的模型不能进行导出。
如果需要文件我可以提供。

**Comment by Perfare** [comment]
一个object可以包含多个mesh，如果你要所有mesh请直接在Asset List导出

**Comment by rouningjun** [comment]
好的谢谢作者
