### ISSUE TITLE
Normals Issue : The Models Exported Are Without Normal & Lighting Can't be Baked In Unity

### ISSUE THREAD

**Issue by Hexa566** [Perfare/AssetStudio#436]
Hello , i am currently facing the issue that the models are without normals and baked lighting didn't work with them , is there any workaround for this ?

[https://www.dropbox.com/s/ql9tpvfvfxmtqzb/map_tunisia.zip?dl=0](url)

**Comment by Perfare** [comment]
add normals in blender or max.
