### ISSUE TITLE
Contra: Return ERROR

### ISSUE THREAD

**Issue by Contra6** [Perfare/AssetStudio#437]
Hello people. Help please i use your programm AssetStudio but no works for **[Contra](https://apkpure.com/garena-contra-returns/com.garena.game.hdltw)** :(
I looked inside the files some work, some don't
**outofres** - I think there is stored heroes 3D model
**leveldynamic** - LVL 
https://yadi.sk/d/SuWpnnW_EyvIog
Still if open assets, that's some texture not show or cannot export.
Thank you for your attention. Waiting your help. 
P.S: I want hero Fang :) and not only

**Comment by Contra6** [comment]
Hello hows it going?? :( Really no one help?

**Comment by Contra6** [comment]
Is there anyone alive? Give a sign of life....

**Comment by Perfare** [comment]
These file contain an abnormal AnimationClip, I updated AssetStudio to skip these assets, other assets can now be exported normally.
