### ISSUE TITLE
How to extract only AudioClips?

### ISSUE THREAD

**Issue by rayman3003** [Perfare/AssetStudio#438]
I want to extract only AudioClips from assets. Bcuz extracting all assets is too much time-consuming. I choose AudioClip from "filter type" But it won't select any AudioClip from opened assets.

Could someone please show me how to extract only AudioClip out of assets?

**Comment by Perfare** [comment]
Use the 'Filter Type' to select AudioClip, then use Export-Filtered assets to export.

**Comment by rayman3003** [comment]
> 
> 
> Use the 'Filter Type' to select AudioClip, then use Export-Filtered assets to export.

Thank U.
