### ISSUE TITLE
How to make use of TextureConverterWrapper in .NET Core

### ISSUE THREAD

**Issue by Cynthion** [Perfare/AssetStudio#439]
Dear Perfare

Thanks for the awesome tool, it's working fine! This is not an issue item with your project, but rather would I like to ask you (or some savvy community guys) whether you could give me some guidance or put me in the right direction.

For my project, I would like to convert DXT1 textures into Bitmap and finally into PNG. In AssetStudio, you make use of your own TextureConverterWrapper.dll which (I guess) then makes use of the Qonvert() function of Qualcomm's TextureConverter.dll. Unfortunately, in my .NET Core project I seem not to be able to just use DllImport() your TextConverterWrapper.dll. The DLL is not found, although it's in the same output directory. It also doesn't work if I compile my project with x64. I wonder whether it has something to do with .NET Core since your AssetStudio solution and source code is working fine for me on my machine.

I know it's a lot to ask, but I'm helpless after surfing the Web for days to find a solution :-)

- Where does your TextureConverterWrapper.dll come from and how could I build it on my own by using the TextureConvert.dll? I already found the TextureConverterWrapper.cpp code in #401, but I'm new in C++ and would not know how to find/link/load the stuff from TextureConverter.dll (like TQonvertImage or Qonvert function). I'm lacking the header file and also don't know how to setup the C++ project in order to compile above .cpp code.

- In your code, where do the TextureConverter.dll and TextureConverterWrapper.dll come from? I don't find any hints in your VS solution, but they finally appear in the output directory when building.

- Would you know another conversion method that I could use (with plain C#) to convert Unity Texture2D assets on DXT1 format? Or doesn't that work because the Texture2D format of Unity is special?

Thank you for your help, any tip or guidance is much appreciated! :-D

**Comment by Perfare** [comment]
You can easily find a .net library that supports DXT1 on github, like this one.
https://github.com/dlemstra/Magick.NET
