### ISSUE TITLE
.bytes files partially loaded

### ISSUE THREAD

**Issue by 09williamsad** [Perfare/AssetStudio#440]
AssetStudio: v0.13.24 64 bit with default settings
Game: Jojo Diamond Records v3.12.0
Game files: https://mega.nz/#F!7CgwgCyY!esctFS03loOgjujjmdZ9-A
Platform: Android
Data file type: .bytes

Issue:
When loading the game files through AssetStudio only some assets are loaded and exportable, however the presence of animation clips without animators, textures without models, models without textures, animations without models etc indicate that they are present in the game files.

For example, characters have 4 digit numbers IDs which can be used to find their meshes, animation clips, textures, animators etc.
Animations are the ID followed by other details and animators are "e_mod" followed by the ID.
For 5120 there are animation clips but no textures, meshes or animators.
![image](https://user-images.githubusercontent.com/23011550/66274422-72b8a800-e876-11e9-8f0a-20b36a612441.png)

Animations are valid as exporting them with another animator for a simular rig works, most of the rigs appear to be standard Unity humanoid. 
Animations for 5120 https://mega.nz/#!bDRREaSA!eqMsmjEDjJr4kQYUjvNGQv9_Bc-NxOIX-xh3rgizlKk

**Comment by Perfare** [comment]
Using the File-Load folder to load a file, AssetStudio will only read the file completely and not just read a part. If you can't find the data you want, I can't help you.
