### ISSUE TITLE
Failure to export model animation file correctly

### ISSUE THREAD

**Issue by scc172fly** [Perfare/AssetStudio#441]
Why are some of the animations I exported missing? How can I solve it? Thank you!

**Comment by scc172fly** [comment]
Hello, this is my resource. [https://pan.baidu.com/s/1zmJeeSJS9ZBcV1Z9u0Zw6g](url) Extraction code：wt28

**Comment by Contra6** [comment]
Nohow. Here no one answers. They alive or no...

**Comment by oqeedoki** [comment]
The studio sees and starts loading the structure but crashes, possibly a new version of the unit.

Resources
[https://cloud.mail.ru/public/5yeD/GkiM26cvq](url)

**Comment by Perfare** [comment]
The file you provided does not include Mesh and AnimationClip, you need to load the related files together.
