### ISSUE TITLE
Ability to see Asset Location

### ISSUE THREAD

**Issue by Jordan9232** [Perfare/AssetStudio#444]
Currently when viewing assets all you see in the grid is the name of the assets, although with data I have I know that certain assets have a path. 

Is there a way to view what the full path is? I have a assets like game_icons/`<name>` but all of them just show `<name>` without the game_icons/.

I can verify this by opening up the .assets file in notepad and while most of it is gibberish, there is data in there where I can indeed see the path.

**Comment by Perfare** [comment]
Check Options-Display asset original name.
