### ISSUE TITLE
Export Sprite throw an exception

### ISSUE THREAD

**Issue by peaceshi** [Perfare/AssetStudio#445]
Export Sprite:限定icon #18947 error

外部组件发生异常。

   在 AssetStudio.NativeMethods.DecompressPVR(Byte[] data, IntPtr image)

   在 AssetStudio.Texture2DConverter.PVRToBitmap(Byte[] pvrData) 位置 C:\projects\assetstudio\AssetStudioUtility\Texture2DConverter.cs:行号 933

   在 AssetStudio.Texture2DConverter.ConvertToBitmap(Boolean flip) 位置 C:\projects\assetstudio\AssetStudioUtility\Texture2DConverter.cs:行号 823

   在 AssetStudio.SpriteHelper.CutImage(Texture2D m_Texture2D, Sprite m_Sprite, RectangleF textureRect, Vector2 textureRectOffset, SpriteSettings settingsRaw) 位置 C:\projects\assetstudio\AssetStudioUtility\SpriteHelper.cs:行号 34

   在 AssetStudio.SpriteHelper.GetImageFromSprite(Sprite m_Sprite) 位置 C:\projects\assetstudio\AssetStudioUtility\SpriteHelper.cs:行号 28

   在 AssetStudioGUI.Exporter.ExportSprite(AssetItem item, String exportPath) 位置 C:\projects\assetstudio\AssetStudioGUI\Exporter.cs:行号 269

   在 AssetStudioGUI.Studio.<>c__DisplayClass13_0.<ExportAssets>b__0(Object state) 位置 C:\projects\assetstudio\AssetStudioGUI\Studio.cs:行号 450

**Comment by peaceshi** [comment]
I can't upload the file or zip. so use dropbox 
https://www.dropbox.com/s/5txuzhhzmw0pnry/atlasclips_research.7z?dl=0

**Comment by Perfare** [comment]
你发的文件测试没有任何问题

**Comment by exe19890522** [comment]
excause me,could you add this function:when i export the mesh , also will export the texture2d in a folder which namee with the mesh's name.

**Comment by peaceshi** [comment]
maybe the reason is the program use to many memory. the program has been used more than 16GB memory. and windows tells system do not has enough memory. the program throw this exception at the same time.

**Comment by Perfare** [comment]
AssetStudio在读取bundle类文件时会在内存中解压，如果你不想AssetStudio占用太多内存，先使用File-Extract folder在本地解压bundle，然后再读取
