### ISSUE TITLE
High RAM usage on loading more 2GB+ files?

### ISSUE THREAD

**Issue by ngovandang** [Perfare/AssetStudio#446]
Please check this
I tried to load a folder with 1150+ files its up to 2.5GBs
with 32 bit version it crashes after awhile loading
with 64 bit version it makes my RAM usage to 5GBs, its really to much
This was not happen before, please fix this if possible

**Comment by Perfare** [comment]
According to your description, these 2gb files are bundle files. The bundle file is a compressed file. When AssetStudio reads them directly, it will be decompressed into memory, so 5gb is actually the size after decompression.
If you don't want AssetStudio to take up too much memory, use the File-File-Extract folder to extract the bundle flie to your hard drive, then use AssetStudio to read the decompressed file.

**Comment by ngovandang** [comment]
@Perfare  yes, I sure I have extracted all of them, but loading them my RAM still up to 5GB, I used Studio ver 10 and RAM is not that huge
I dont know what is the problem

**Comment by Perfare** [comment]
Sorry, I don't think there is such a problem. The code has been checked many times and there is no memory overflow.
