### ISSUE TITLE
crash during export textures from ReCore

### ISSUE THREAD

**Issue by anrej0705** [Perfare/AssetStudio#448]
Hi, i`m use Asset Studio 0.13.25 for that export textures from ReCore game(build 911).
I tried export any texture into .tga/.png format from sharedassets bundle file, they exporting 
without UV or they export corrupted texture file or application quiet crash during export. I 
try to unpack asset as a result, i received one big(7.2Gb)file which is not readable in any 
ripping applications
As well, Asset Studio crash if i select texture to view
Also, app successfully export .fbx files(luna_*, kai_*, etc.)
as sample, link to corrupted texture:
http://www.mediafire.com/file/52maxz26751kenx/Luna_Exosuit_c-CAB-591d2d4b5f5d82c3fd778285a01aa858-9123433687010849057.tga

How i can rip texture from this game?
![image](https://user-images.githubusercontent.com/56804640/67458658-718dc600-f63f-11e9-9aad-2a66b0b2d9b9.png)

**Comment by anrej0705** [comment]
links to some asset files(i had a problem with this files):
https://yadi.sk/d/UC1R1Zuos8bI3A - sharedassets.manifest
https://yadi.sk/d/MLr-IvZLXGD1-w - sharedassets, weight 4.08 Gb

**Comment by Perfare** [comment]
The version of this asset file is 5.4.0b14, beta version is not supported.

**Comment by anrej0705** [comment]
Will you add support for this version of the format in the future?
