### ISSUE TITLE
Сontra Error only Texture

### ISSUE THREAD

**Issue by Contra6** [Perfare/AssetStudio#449]
Again Hi. Want say thanks big for help. Model without problems open. But there is 1 problem half **texture** does not show. Thank you again for help [Link](https://yadi.sk/d/bK4-uPQzcQ_FWw)

**Comment by Perfare** [comment]
The game uses a custom file structure, and those wrong files cannot be read.

**Comment by Contra6** [comment]
OK, I will check later and will post, which ones don't work
