### ISSUE TITLE
Texture UNKNOWN(Check please)

### ISSUE THREAD

**Issue by Contra6** [Perfare/AssetStudio#452]
Hi, I wrote in the last topic [Error only Texture](https://github.com/Perfare/AssetStudio/issues/449)
Download to make sure. I've come very a long way. Can you fix it?.
[Texture UNKNOWN](https://yadi.sk/d/lItXj9Zkz19k6A)
I even simplified help you in finding the error. Thanks

**Comment by Perfare** [comment]
The game uses a custom file structure, so those files cannot be read.

**Comment by Contra6** [comment]
Really is there no solution? Very sorry... I'm stumped. I don't know who to turn to for help.
