### ISSUE TITLE
Asset Original Name not being loaded correctly for certain assets

### ISSUE THREAD

**Issue by kerzyte** [Perfare/AssetStudio#456]
Bundle found here: https://game305456.konggames.com/gamez/0030/5456/live/StreamingAssets/WebGL/maingametextures

When loading this bundle with the "Display Asset Original Name" option checked, 43 assets are not correctly displayed. These names all start with "sactx-".

**Comment by Perfare** [comment]
These assets do not contain path data, so only the asset name is displayed.
