### ISSUE TITLE
Some files not read/loading from Honkai Impact 3rd

### ISSUE THREAD

**Issue by Namwin** [Perfare/AssetStudio#457]
I've been using AssetStudio with Honkai Impact 3rd to grab sprites and images to put on the wiki for a while and it's worked without problem until now. With the recent update, some files don't load for some reason. It's not all of them and I can still load some of them, so I'm not 100% sure what the problem is. Any help would be appreciated here, or if you can just pinpoint what exactly the problem is, maybe I can ask them to change it if possible.

Here's a link to a file:
https://drive.google.com/open?id=1day-L__aWVSaWBAPqFhL06xsKZ-IKS_6

**Comment by Perfare** [comment]
Honkai Impact 3rd file is encrypted.
