### ISSUE TITLE
File unreadable?

### ISSUE THREAD

**Issue by max20091** [Perfare/AssetStudio#459]
It seems the tool somehow can't read any contents in this file.
Can you check why the tool can't read this file?
(Also if you want to know where I get this file, it's from Honkai Impact 3rd CN PC version, this tool can read files in BH3_Data folder but not the one in Asb)
[21787307_2699926805.zip](https://github.com/Perfare/AssetStudio/files/3855648/21787307_2699926805.zip)

**Comment by Perfare** [comment]
#457
