### ISSUE TITLE
Suggestion: Load present assemblies and file location metadata files before loading assets

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/AssetStudio#461]
I'd like this because loading the assemblies (if present) before loading the asset data would help with retrieving the true filesystem of a game. I love this tool. Thanks so much.

**Comment by LolHacksRule** [comment]
Can metadata files outside the Unity data folder (JSON) with file locations be loaded too?

**Comment by Perfare** [comment]
Not quite sure what you want to do, you can manually select the folder location when AssetStudio loads the assembly.
