### ISSUE TITLE
Suggestion: export from an AssetBundle with the directory structure specified in the container

### ISSUE THREAD

**Issue by LudwigvonWu** [Perfare/AssetStudio#464]
Currently, when exporting assets from an AssetBundle the files are exported in a directory named after the SerializedFile name, which is definitely a sensible choice.
However, often the assets in the AssetBundle are part of containers that have their own directory structure specified, which allows a more intuitive placement of the exported assets. I think it would be nice to allow the option of recreating the directory structure using a specfied folder as root, with the assets exported at this point in the subdirectory having the name of the container.
 
E.g. CAB-1234 contains the Mesh B-LOD0 and the Texture2D B_alb as part of a container having the internal name and path assets/main/content/models/B.asset, the option would allow to specify a <path>, create the <path>/assets/main/content/models/B.asset directory, and then would export B-LOD0 and B_alb in said directory.

**Comment by Perfare** [comment]
`Options – Display asset original name` and `Do not group`
Should be what you want.

**Comment by lbmaian** [comment]
That didn't work. I checked Options->"Display asset original name" and selected Options->"Do not group", then Export->"All assets", and it dumped all files in the same folder.

Is AssetStudio even aware of containers in asset bundles? I can't find that info displayed anywhere in the program, not a column or anything.

**Comment by lbmaian** [comment]
@Perfare That didn't work. I checked Options->"Display asset original name" and selected Options->"Do not group", then Export->"All assets", and it dumped all files in the same folder.

Is AssetStudio even aware of containers in asset bundles? I can't find that info displayed anywhere in the program, not a column or anything.

**Comment by FlandreCirno** [comment]
For people who have the problem.
AssetStudio -> Options -> Export options -> Group exported assets by -> container path
Should put all assets in folders corresponding to their container path.
