### ISSUE TITLE
Problem read assets

### ISSUE THREAD

**Issue by MercyTsuyu** [Perfare/AssetStudio#466]
Hello i have issue i trying export models from honkai impact 3rd its not all see assets and make error, 2 picture i trying open texture its make that error.
![image](https://user-images.githubusercontent.com/45007476/69828326-83f5b380-122c-11ea-881d-d64cc2c05e34.png)

![image](https://user-images.githubusercontent.com/45007476/69828346-9e2f9180-122c-11ea-9cfa-dd2880b1a629.png)

**Comment by MilutinMujovic** [comment]
I just got the same issue for some reason.
Can't export models nor can I read files.
![Error](https://i.imgur.com/kU6aYJW.png)

**Comment by MercyTsuyu** [comment]
![image](https://user-images.githubusercontent.com/45007476/69830186-97a51800-1234-11ea-956d-7b225e53b995.png)
ok i try setup. aslo this same?

**Comment by MercyTsuyu** [comment]
no same :(

**Comment by MercyTsuyu** [comment]
All same i delete and setup.

**Comment by Perfare** [comment]
Honkai Impact 3rd file is encrypted.
#457

**Comment by MercyTsuyu** [comment]
oh no ._. now i dont know what do. anyway thanks.
