### ISSUE TITLE
Wasting RAM

### ISSUE THREAD

**Issue by masagrator** [Perfare/AssetStudio#468]
Is it possible to do something about loading all assets to RAM?
AssetStudio can take sometimes more than 12GB of RAM for one game before finalizing reading assets, when it can go down about 40%.

**Comment by Perfare** [comment]
This is indeed a problem, but I am not sure if I can find a good solution.

**Comment by fernandodarci** [comment]
Maybe buffering parsed filés and jeep just headers while importing?

**Comment by CNDY-RollingSky** [comment]
There's no problem in 12.x and 13.x. But diffferent in 14.x.

**Comment by Wufflatious** [comment]
you just simply have a potato computer

**Comment by masagrator** [comment]
> you just simply have a potato computer

Sorry that i don't have 32 GB of RAM.

**Comment by nandur93** [comment]
It's hang up and restart my PC several times until BSOD. I have 16 GB ram and trying to read 2GB game assets
