### ISSUE TITLE
DumpScript fails on wwise objects

### ISSUE THREAD

**Issue by tracktwo** [Perfare/AssetStudio#469]
Phoenix Point uses wwise audio and the script dumper will fail on any asset that has a field of certain wwise types. The root issue seems to be that these objects have a "valueGuidInternal" field of type byte[]. The dumper attempts to read this array by re-aligning the stream after each byte, but all the array elements are packed in the asset file with no padding between them.

I am unsure if the packing behavior is specific to these wwise types or would be the case for all arrays of byte (or boolean?). I have made a local change that skips alignment after reading a primitive type if the type is an array element, instead re-aligning after processing the whole array. This seems to work for Phoenix Point but I don't know if it will break other games.

**Comment by Perfare** [comment]
Reading MonoBehaviours is an unfinished feature and I will try to improve it when I have time.
