### ISSUE TITLE
Bug Mesh/Model

### ISSUE THREAD

**Issue by CerealYe** [Perfare/AssetStudio#470]
I was tried to rip ice scream 2's asset and i find rod kid's model in Asset List. but there's problem with rod kid's model, https://imgur.com/a/hnOC5Jd his model looks messup, his legs and arms looks flickering and terrible, he's covered in black glitches, his model looks even horrible. J.'s, Charlie's, Lis' and Mike's models looks all fine but rod kid's not. Perfare needs to fix this

**Comment by Perfare** [comment]
Please upload the file so I can check it.
