### ISSUE TITLE
Compiled Shaders

### ISSUE THREAD

**Issue by victti** [Perfare/AssetStudio#473]
Is it possible to decompile those? I want to decompile the shaders of a game I used to play but most of them comes into the compiled format. Is there a way around it?

Link for the game files if needed: https://drive.google.com/open?id=1s6nntePCZ4d77OfSXyCMe-B6pZuh1TZl

**Comment by Perfare** [comment]
Try to use [UnityRipper](https://github.com/mafaca/UnityRipper)
