### ISSUE TITLE
Animator not works for Contra Return

### ISSUE THREAD

**Issue by Contra6** [Perfare/AssetStudio#474]
Hi, you can verify, why not works? or is there a way to make it work?
Link [Animator](https://yadi.sk/d/BaJJAa5vzuOevw) Thanks
I even checked on old versions Contra 1.6.47.1653 until 1.13.53.2191 on following versions not wokrs. 
I don't know why and what is the reason?

**Comment by Perfare** [comment]
Please use File-Load folder to read these files.

**Comment by Contra6** [comment]
You didn't even look... :( Very sorry (2 months later)
