### ISSUE TITLE
Mesh Preview mesh collapsed on itself

### ISSUE THREAD

**Issue by cyee** [Perfare/AssetStudio#476]
I've noticed this bug in which the "Mesh" in the mesh preview appears distorted/collapsed and is black. (This also affects its respective Scene Hierarchy object). When I export it to another application (e.g Blender), it retains this distorted state. **Is there a possible fix for this**? Here is an instance of the bug: 
![bug](https://user-images.githubusercontent.com/15678171/72957184-891c3e00-3d57-11ea-90a5-b2fc8b61e894.png)

If things are unclear, I will try to address more details, if I have time.

(If you are wondering what game this is, its Subnautica:BZ)

**Comment by Perfare** [comment]
AssetStudio just reads the mesh data of the asset file and does not do any processing. If the other meshes of the game are no problem, it indicates that the mesh is what you see.
