### ISSUE TITLE
Some MonoBehaviours taking a long time to export

### ISSUE THREAD

**Issue by MichaelPriebe** [Perfare/AssetStudio#478]
I need to be able to export every MonoBehaviour, but some seem to read incorrectly, creating a huge file iterating over a list of thousands of invalid entries, is there any way to skip these files that take too long?

**Comment by MichaelPriebe** [comment]
https://github.com/DerPopo/UABE Exports all the MonoBehaviours quickly, but with many warnings, possibly the ones AssetStudio is having trouble with.

**Comment by Perfare** [comment]
Reading MonoBehaviours is an unfinished feature and I will try to improve it when I have time.
