### ISSUE TITLE
Strange mesh deform

### ISSUE THREAD

**Issue by KekMcGee** [Perfare/AssetStudio#48]
https://mega.nz/#!JsQEwT6R!O94dqnCcMh6tl-pMCYfBxSnQzVwVUQ5IBdf6hHqgE6Q

"Ravener_Standard_LOD00_rig"

Disabling skin deforms fixes it, but I'd like to keep the rigging and skeleton, which disabling deformers doesn't keep.

**Comment by Perfare** [comment]
sorry, there's nothing I can do about the problem

**Comment by Perfare** [comment]
Using the new model export function should have solved this problem.
