### ISSUE TITLE
How do you install AssetStudio?

### ISSUE THREAD

**Issue by asdfsheep** [Perfare/AssetStudio#480]
i've looked everywhere on the internet and most of the answers are just "read the readme and then load it in VS"

i have VS 2019 and all the requirements.

can someone give me a step by step guide on how to install AssetStudio?

thanks!

**Comment by asdfsheep** [comment]
wait is the AssetStudioGUI supposed to be it?

thanks!

**Comment by exe19890522** [comment]
why you need to install AssetStudio and vs?
just download the release file and unrar it and then open .exe file.

**Comment by asdfsheep** [comment]
> why you need to install AssetStudio and vs?
> just download the release file and unrar it and then open .exe file.

so whats the files used for? like the files located on the front page

**Comment by godskin** [comment]
stupid people
