### ISSUE TITLE
Not work Animation Clip

### ISSUE THREAD

**Issue by Contra6** [Perfare/AssetStudio#481]
Hi, can explain me what i do not so?
In 2 files
1.Texture+Mesh
2.Animation Clip
Not as not can get a model with bones in format FBX
Or just press export on Animation Clip and nothing not occur. What not so?
Link [Download](https://yadi.sk/d/Tr8xdhN7wWcmJw) Thanks.
Ah yes, too same regards with **Assassin's Creed: Rebellion**

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#how-to-use
AnimationClip can only be exported with fbx.

**Comment by Contra6** [comment]
Thanks, but i already figured out how.
