### ISSUE TITLE
Question with Windows 8 game

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/AssetStudio#482]
I want to datamine a game for Windows 8 but the game doesn't have the **Managed** directory in **Data**, the DLLs are in the root of the directory of the game (Extracted APPX/installed package). Luckily Sega left an internal compilation file called managedAssemblies.txt that lists them which helps me find them. Do I have to create a directory with them or can AssetStudio just find them when I locate the root of the game directory?

Unity Version: 4.7.2f1
Game: Sonic Dash
Developer: SEGA
Game Platform: Windows 8
Version: 3.6.4.0 (ARM/X86)
AssetStudio Version: 0.13.25.0

**Comment by Perfare** [comment]
The dll file will only be used when reading MonoBehaviour. When you click MonoBehaviour, you will be prompted to select the folder where the dll is located.
