### ISSUE TITLE
how to find the model's Texture2D ?

### ISSUE THREAD

**Issue by exe19890522** [Perfare/AssetStudio#483]
i unpack the apk file ande export the model,
but those are all without the Texture2D file'name;
how can i to find the right Texture2D file to use it in cocos creator?
normally ,i just export all Texture2D files and search them one by one.
does it have some quickly way??

**Comment by Perfare** [comment]
Under normal circumstances, the texture will be exported together when fbx is output. If not, it means that there is no texture bound on the material.
mesh does not output textures because mesh does not contain any texture information.
