### ISSUE TITLE
problems with fbx

### ISSUE THREAD

**Issue by feber12** [Perfare/AssetStudio#484]
Hi, first of all, I love your job for sure it took a long time.
I have to tell you that I had a problem with FBX conversion when importing to 3d max the Maya deforms it turns out that FBX has a problem with "gimbal lock" trying to fix the problem I did not find a solution, besides being able to convert it into FBX I also have the option of turn it into .MAX

**Comment by Perfare** [comment]
Thank you for your support. AssetStudio is only responsible for writing data from the asset file to fbx. I am sorry that I cannot answer the problems in using fbx.
