### ISSUE TITLE
debug build/mode?

### ISSUE THREAD

**Issue by Brian151** [Perfare/AssetStudio#486]
one of the webgl games which i play [i shall not discuss here] causes asset studio to just silently exit [i presume it's a crash] at the phase where the scene hierarchy is supposed to be constructed

this happens to both the original file from their server, AND the decompressed one asset bundle extractor INSISTS on creating in order to view these files...

UABE can read these files without any problem, so i'm real curious why asset studio can't... i could potentially see encryption going on, but i'd expect the textures to have been encrypted, and they most certainly are not. UABE doesn't try to re-build the scene, however... 

so, are there any special builds/flags that give technical details WHY a file caused a crash? i'd somewhat prefer to avoid publicly sharing the files or game in question for the time being. i haven't even downloaded all the files yet because it's a fairly large game, and so far, unity games just sit-around on the hard drive since i can't extract anything super USEFUL from them.

**Comment by Perfare** [comment]
The error is usually caused by an unsupported version or a custom format of the game, you can upload some files and let me check these errors.

**Comment by Brian151** [comment]
[example0001.zip](https://github.com/Perfare/AssetStudio/files/4264394/example0001.zip)

i have re-named this file 
from what i can tell, asset studio crashes when it tries to build the scene graph/tree

**Comment by Perfare** [comment]
I tested the file you provided and it loads normally.

**Comment by Brian151** [comment]
how new of a version did you test then?

**Comment by Perfare** [comment]
I always use latest build version
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

**Comment by Brian151** [comment]
i'll have to try that later, then
