### ISSUE TITLE
Unity 2019.3 support?

### ISSUE THREAD

**Issue by AlterShiki** [Perfare/AssetStudio#488]
I don't think those files are encrypted since they have the correct header and all but they're from unity 2019.3.f3 and AssetStudio is unable to open them, it says that AssetStudio only supports up to 2019.1 on the main page so I assumed that theres no support for 2019.3 but I could be very wrong

a few samples:
https://mega.nz/#!x4YEVaRb!mqnz_sIfYlsc3Ksc23qxlgCwOkzbGetQluqRWlC3DG8

**Comment by Perfare** [comment]
I will add support for 2019.3 this week.

**Comment by Perfare** [comment]
Completed.
