### ISSUE TITLE
Error loading Animation Clip

### ISSUE THREAD

**Issue by lazycodex** [Perfare/AssetStudio#490]
So, I can export *.fbx perfectly without animation. However, I can't export it with Animation Clips.

![GUIError](https://user-images.githubusercontent.com/28950876/75552157-0767b080-5a79-11ea-8b1d-bd29b36ffbe2.png)

When I load it with older version of AssetStudio, I got 'Array dimensions exceeded supported range.' These errors only happen while reading an Animation Clip.

This is sample files:
[samples.zip](https://github.com/Perfare/AssetStudio/files/4267226/samples.zip)

Also, there're dozen of Animation Clips in these files, but only 3 show up in Asset List. Is it something that can be fixed?

**Comment by Perfare** [comment]
The game uses a custom AnimationClip structure and cannot be loaded in AssetStudio.
