### ISSUE TITLE
How do you use the exported Monobehaviour text/ MonoScript dat files?

### ISSUE THREAD

**Issue by h1ddengames** [Perfare/AssetStudio#491]
For example:

PPtr<GameObject> m_GameObject
	int m_FileID = 0
	int64 m_PathID = 264
UInt8 m_Enabled = 1
PPtr<MonoScript> m_Script
	int m_FileID = 1
	int64 m_PathID = 526
string m_Name = ""

**Comment by Perfare** [comment]
Monobehaviour export is currently only for viewing.
