### ISSUE TITLE
There are some new assetbundle can not load

### ISSUE THREAD

**Issue by pgw00k** [Perfare/AssetStudio#492]
Currently,i found some assetbundles can not load anything by assetbundle,but i use winhex to check file,it looks like normal assetbundle,is it encryption?

there are some sample:
1. [sapmle1](https://github.com/pgw00k/unity3d-file/releases/download/1.1/cha_1011.zip)
2. [sample2](https://github.com/pgw00k/unity3d-file/releases/download/1.0/gdSample.zip)

**Comment by K0lb3** [comment]
There seems to be a problem with the compression of these bundles.
They use LZ4HC for the block data compression.

UABE throws an error because of the compression as well.

**Comment by Perfare** [comment]
These files should be broken or encrypted.
