### ISSUE TITLE
PathID for each file ?

### ISSUE THREAD

**Issue by Aceship** [Perfare/AssetStudio#496]
Are there any information of PathID of each file (especially on Asset List info)?
if possible , extract (selected or all) file with `PathID ` as filename ?

**Comment by Perfare** [comment]
Added in versions after 0.14.12.
Do not consider adding PathID to the export file name for the time being.

**Comment by Aceship** [comment]
Thanks for the update 👍 
some question, is it possible to make the pathID copy able from right click or something ?
since retyping it is a bit tiring

**Comment by suphamster** [comment]
Sorry for reviving old issue but it seems that in latest versions "extract (selected or all) file with PathID as filename" is not implemented right?
