### ISSUE TITLE
Hope to add file import function

### ISSUE THREAD

**Issue by mskgroup** [Perfare/AssetStudio#497]
I hope that the file import function can be added. Like UABE or UnityEX, the exported file can be modified and imported back.
希望可以增加文件导回功能，像uabe或者unityex那样，可以将导出的文件修改后导回

**Comment by 8silena8** [comment]
importing files is a necessary function UABE and unityEX cannot work with all assests files so importing function will be so helpful in AssestStudio

**Comment by mskgroup** [comment]
> importing files is a necessary function UABE and unityEX cannot work with all assests files so importing function will be so helpful in AssestStudio

yes!

**Comment by Perfare** [comment]
I'm sorry, but editing features will not be added at this time.
