### ISSUE TITLE
FBX bug - eyes

### ISSUE THREAD

**Issue by MagicLeonardo** [Perfare/AssetStudio#500]
I exported some animal animation models and the eyes of the models move incorrectly. Is it possible to refine fbx export?

**Comment by MagicLeonardo** [comment]
I've attached the necessary files:

[test.zip](https://github.com/Perfare/AssetStudio/files/4350674/test.zip)

**Comment by MagicLeonardo** [comment]
Hi,
Can you solve this **eye** problem? 

![eye](https://user-images.githubusercontent.com/62262155/90313397-827c3080-df0c-11ea-9d7a-a64d835f0eee.gif)

**Comment by MagicLeonardo** [comment]
I think the problem is the mesh size. The original model had 19,604 triangles, but the exposed one was only 5,344.

Is there a solution to this?

**Comment by Perfare** [comment]
This problem should be fixed now.
