### ISSUE TITLE
Fbx not exporting with uv2/lightmap on the model

### ISSUE THREAD

**Issue by LudoMako** [Perfare/AssetStudio#501]
I'm trying to rip the uv2/lightmap on models from million live theeather days, but new build doesn't seem to catch the 2nd uv once exported to fbx.
https://sta.sh/0snuqtt9huv here sample unity file
thank you so much for the tool

**Comment by Perfare** [comment]
Already in the plan, but there are many other things that need to be improved, I hope I can finish it as soon as possible.
Also, the attachment seems to have expired and cannot be downloaded.

**Comment by LudoMako** [comment]
> 
> 
> Already in the plan, but there are many other things that need to be improved, I hope I can finish it as soon as possible.
> Also, the attachment seems to have expired and cannot be downloaded.

It's not expired, if it gives you 404 it's either bugged or you don't have an account. Here's a mirror https://www.mediafire.com/file/ytd6ve5m1bae9oz/stage046_by_ludomako_ddsl50j.zip/file

**Comment by Perfare** [comment]
Multiple uv exports have been added.

**Comment by LudoMako** [comment]
Thank you so much!

Il lun 6 apr 2020, 13:30 Perfare <notifications@github.com> ha scritto:
