### ISSUE TITLE
Export models with skin modifier

### ISSUE THREAD

**Issue by romanpopulik** [Perfare/AssetStudio#503]
Just like in the title. Now I am able to export first person hands model, but without skin modifier.

**Comment by romanpopulik** [comment]
[bear_hands_skin.bundle.zip](https://github.com/Perfare/AssetStudio/files/4395751/bear_hands_skin.bundle.zip)

**Comment by zwrtron** [comment]
I'm having similar problem. The model I've tried gets exported with the Skin modifier and all animations, but when imported to 3ds Max, the animations loads correctly (bone movement) but the model (having a Skin modifier with linked bones) does not simply move according to bones - does not moves at all to be correct. Seems like the vertex weights are not properly exported or I am doing something wrong? If there will be interest I could provide sample file.

**Comment by Perfare** [comment]
The skin information of this file is not stored in SkinnedMeshRenderer, but is stored in a custom MonoBehaviour, and the GameObject does not contain hierarchical information, AssetStudio can not handle this file.
