### ISSUE TITLE
How to extract game with two data.unity3d files?

### ISSUE THREAD

**Issue by LolHacksRule** [Perfare/AssetStudio#504]
The game is Angry Birds Evolution, both the APK and OBB have data.unity3d files. How would I load both of them at once without manual extraction? Rename them temporarily?

**Comment by Perfare** [comment]
You can rename it and load it at the same time, but note that if these two bundle files contain assets with the same name, AssetStudio cannot load them at the same time, still need to load them separately.

**Comment by Perfare** [comment]
You can rename it and load it at the same time, but note that if these two bundle files contain assets with the same name, AssetStudio cannot load them at the same time, still need to load them separately

**Comment by LolHacksRule** [comment]
Ah ok I currently renamed the two unity3d files to load them in AssetStudio
