### ISSUE TITLE
why is there no exe file

### ISSUE THREAD

**Issue by Wufflatious** [Perfare/AssetStudio#507]
![ytgfd](https://user-images.githubusercontent.com/62799364/77824153-c955bf00-7100-11ea-8b47-c9d92e114578.PNG)

**Comment by exe19890522** [comment]
this the resources code not exe file.you can to this bulid page to dl the build .exe file. 
https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts

**Comment by exe19890522** [comment]
Because many people like to compile their own executable files, if you can't do it, why don't you download the compiled version directly? Don't all the authors provide download links for compiled files?

**Comment by Perfare** [comment]
Because you downloaded the source code, please download the compiled file from here https://ci.appveyor.com/project/Perfare/assetstudio/branch/master/artifacts
