### ISSUE TITLE
Some meshes not loading Correctly.

### ISSUE THREAD

**Issue by Arymond** [Perfare/AssetStudio#510]
https://cdn.discordapp.com/attachments/534536607001214986/693841463254974554/sharedassets1.7z

Most of the files where in the APK 

![image](https://user-images.githubusercontent.com/22692858/77852964-3cf5db80-7196-11ea-9b4b-74246a4c4c56.png)
mostly the Hair meshes some load correct?

**Comment by Arymond** [comment]
also a issue but less meaningful i cant seem to view assets with japanese names.

![image](https://user-images.githubusercontent.com/22692858/77853084-04a2cd00-7197-11ea-9129-62def1254ff4.png)

**Comment by Perfare** [comment]
The second problem should be that you don't have Microsoft Visual C ++ 2017 Redistributable installed.
https://support.microsoft.com/help/2977003/the-latest-supported-visual-c-downloads

**Comment by Perfare** [comment]
Fixed, please download the latest version.

**Comment by Arymond** [comment]
thank you mesh loads now. but the head no longer has Vertex Groups. and all the mouths have random seams down the front of the face (but not the chin?) making the vert counts inconsistent. for morph transferring. same game new file. (alt version)

https://cdn.discordapp.com/attachments/534536607001214986/694883241337028658/sharedassets1.7z

**Comment by Perfare** [comment]
No more bugs can be found, this mesh should look like this.
