### ISSUE TITLE
Cannot export animation clip :/

### ISSUE THREAD

**Issue by DenisaXxX** [Perfare/AssetStudio#513]
Hello, Perfare!

This tool looks very promising, unfortunately I am unable to export animation clips. Everything else exports fine, except for animation :( . When I try to export it writes "Nothing exported. 86 assets skipped (not extractable or files already exist). 
Could I please send you the files, so you can check yourself? Thank you.

Best regards,
DenisaXxX

**Comment by Perfare** [comment]
Please check https://github.com/Perfare/AssetStudio#how-to-use.

**Comment by DenisaXxX** [comment]
NoahZhuo created a branch that allows for animation export without needing to bind it to an animator, can you see if you can integrate this with the master branch? I think it would be highly useful.
https://github.com/Perfare/AssetStudio/pull/516

Thanks
