### ISSUE TITLE
Useless serial number in exported filenames

### ISSUE THREAD

**Issue by dtsdao** [Perfare/AssetStudio#514]
![screenshot](https://i.loli.net/2020/04/01/FeZlLdNwPXYb45a.png)

There wasn't any serial number like '#941' following the original filenames before v0.14.11, so I have to use previous version to let my scripts work as expected, but  AppVeyor cleans builds 6 month later. The old builds will be removed sometime.

It would be nice if you can fix this, or upload stable releases to another website.

**Comment by Perfare** [comment]
I modified the export logic, now only when there are files with the same path, will the unique number be added.
