### ISSUE TITLE
Possible to export animation clip without animator?

### ISSUE THREAD

**Issue by DenisaXxX** [Perfare/AssetStudio#515]
Hi!

Would it be technically possible, to just extract the skeleton with the animation without the bound animator mesh? The project I am trying to extract from has the animator inside "Streaming Assets" folder with .asset extension, and AssetStudio is unable to open it :/.

**Comment by NoahZuo** [comment]
Such feature has just been implemented in my branch.

**Comment by DenisaXxX** [comment]
Hello, when can we expect to see this feature working in a released version?

Best Regards,
Denisa

pi 3. 4. 2020 o 10:09 Noah Zuo <notifications@github.com> napísal(a):

**Comment by Perfare** [comment]
You can use `Model-Export selected objects with AnimationClip`

**Comment by DenisaXxX** [comment]
Hi Perfare,
When I try to do it the way you say, it says "No Objects can be exported".  The issue in my case is, that the animator mesh is inside streaming assets folder with .ASSET extension, and asset studio is unable to open it, thus I cannot export the animation clips. My question again is, would it be possible to just export the animation clip with the skeleton, without the animator mesh? I have tried NoahZuos branch, but it does not do the things it says it does, unfortunately.

**Comment by NoahZuo** [comment]
> 
> 
> Hi Perfare,
> When I try to do it the way you say, it says "No Objects can be exported". The issue in my case is, that the animator mesh is inside streaming assets folder with .ASSET extension, and asset studio is unable to open it, thus I cannot export the animation clips. My question again is, would it be possible to just export the animation clip with the skeleton, without the animator mesh? I have tried NoahZuos branch, but it does not do the things it says it does, unfortunately.

Would you mind sending me your file please? My email is: noahzuo@163.com

**Comment by Perfare** [comment]
@DenisaXxX You need to check object in the scene hierarchy, so AssetStudio can be exported according to the selected skeleton. In addition, you should upload it to me for files that cannot be loaded and let me check.

**Comment by DenisaXxX** [comment]
@Perfare  Please email me at denisagreguss@gmail.com and I will send you the files :).
Thanks

**Comment by DenisaXxX** [comment]
@Perfare Hello Perfare, here is the file that I cannot open, and most likely contains the animator skeleton for the player. I have been able to find and export only animations for NPCs. This file is located inside "/animationcache" folder and maybe uses some encryption.
http://www.filedropper.com/cantopeninas
