### ISSUE TITLE
Problems with UV (since last commit)

### ISSUE THREAD

**Issue by zwrtron** [Perfare/AssetStudio#520]
I'm having problems with UV maps since last commit (d259c7a5cded537d5b9846dc20f4ea5feb0f3d47). The UV of object (that supposed to have multiple UVs, probably) is broken. 

Some UVs are correct so I'm not sure where the problem might be laying but I'm sure that the problem was not present in previous version, please see following comparison (before means before that commit, after means after the commit - UV 1):
[https://i.imgur.com/XeIEtLr.png](https://i.imgur.com/XeIEtLr.png)

Is there also possibility you could share older builds of the program for such situations? Mistakenly, I've updated previous version without making a backup and now I cannot properly export models.

Sample:
[https://mega.nz/file/zW4h3LhS#itlONWYiJSB_HUR8iw9dbf2FsbzfOBNJaPj0CIT_nRA](https://mega.nz/file/zW4h3LhS#itlONWYiJSB_HUR8iw9dbf2FsbzfOBNJaPj0CIT_nRA)
* You have to import all assets from the archive and export first cabinet (Body_lodA) and there is problem with Interior_Geo_lodA object for example. This asset has also problem (ever since) with skin animations, event if that's not the point of this issue, fix would be greatly appreciated.

Thanks.

**Comment by Perfare** [comment]
Please try the latest version.

**Comment by zwrtron** [comment]
Yes this resolved the problem. Thank you.
Could you please take look on the animation problem in the file I've shared? There is problem that the parts of the geometry do not move with animation.
