### ISSUE TITLE
No problem here 

### ISSUE THREAD

**Issue by athor** [Perfare/AssetStudio#521]
Just a "thank you" sub =) Would have done this on your blog but i dont speak chinese at all.

Thank you for this amazing tool. I started dealing with 3D world, blender, unity & modding a year ago and could never have done anything without your work. 

Heres some of the few assets i could done or modify with it.
https://www.youtube.com/watch?v=nJD4fHj-4Do

Also made a full short fan art 12mn animation with all extracted assets.
https://www.youtube.com/watch?v=S1dWYAt--Rw

Asset studio - UABE - tinyRipper is the golden combo for modding

Regards.

Google trad =P
只是“谢谢”子=）本来可以在您的博客上完成的，但是我一点也不说中文。

谢谢您提供的出色工具。一年前，我开始处理3D世界，混合器，统一和修改问题，没有您的工作就做不到。

这是我可以完成或修改的一些资产。
https://www.youtube.com/watch?v=nJD4fHj-4Do

还制作了一个完整的简短粉丝艺术1200万动画，其中包含所有提取的资产。
https://www.youtube.com/watch?v=S1dWYAt--Rw

Asset Studio-UABE-tinyRipper是改装的黄金组合

问候。

**Comment by CNDY-RollingSky** [comment]
how can i use UABE to modify an ab?

it seems that my UABE cannot support Unity2017 or higher.
?????

**Comment by athor** [comment]
> 
> 
> how can i use UABE to modify an ab?
> 
> it seems that my UABE cannot support Unity2017 or higher.
> ?????

https://forums.7daystodie.com/forum/-7-days-to-die-pc/game-modification/tools/23262-unity-assets-bundle-extractor?22675-Unity-Assets-Bundle-Extractor/page44=

**Comment by Perfare** [comment]
thank you for your support!
