### ISSUE TITLE
Missing data in MonoBehaviour (Unity 2019.3.6f1)

### ISSUE THREAD

**Issue by mandrx** [Perfare/AssetStudio#522]
### **UISpriteData mSprites** section is missing on Unity 2019.3.6f1 *.unity3d files.

I've been using AssetStudio to decompile this one game data for almost every month. However, on the latest game update, the game developer started using Unity 2019.3.6f1. 

Texture and every other file can be decompiled without issue, but for MonoBehaviour files, there are some sections missing, notably **UISpriteData mSprites**.

Here are the file samples
- [item_1-2019.3.2f1](https://www.mediafire.com/file/uytczih41rv92nm/item_1-2019.3.2f1.unity3d/file) (Older file)
- [item_1-2019.3.6f1](https://www.mediafire.com/file/tx18zygmeeczrqu/item_1-2019.3.6f1.unity3d/file) (Latest Version)

Thank you in advance!

**Comment by Perfare** [comment]
Need dll file, please upload the Managed folder to me.

**Comment by mandrx** [comment]
It is actually an android game, I uploaded *.so files from **lib/armeabi-v7a** folder instead
https://www.mediafire.com/file/qezonxa9goom7z5/lib_armeabi-v7a_%5BROM_CN_CBT%5D.zip/file

**Comment by ciaoca** [comment]
2019.3.6f12 的也不能读取 MonoBehaviour 的完整数据，希望能支持，感谢

**Comment by Perfare** [comment]
I refactored the reading of MonoBehaviour, it should be able to read normally now, I noticed that this game is il2cpp, you need to use Il2CppDumper to convert to dummy dll before reading.

**Comment by Perfare** [comment]
@ciaoca 我最近完善了MonoBehaviour的处理，请下载最新版本，如果有任何问题请打开一个新的issue不要在别人的issue里回复
