### ISSUE TITLE
How can I translate it into Simplified Chinese or other languages?

### ISSUE THREAD

**Issue by CNDY-RollingSky** [Perfare/AssetStudio#524]
How can I translate it into Simplified Chinese or other languages?

to create a json or lang file(?)

Although it is easy to understand those words in the software,,,

**Comment by exe19890522** [comment]
> How can I translate it into Simplified Chinese or other languages?
> 
> to create a json or lang file(?)

this tool is easy to use ,just load files or a folder to load a game's package,then:chose the filter type at menu.and then  export filter assets at menu.

**Comment by CNDY-RollingSky** [comment]
that's OK, I originally thought it would be easy to add language options, if not, then forget it.
