### ISSUE TITLE
Suggestion: add "Uncompress an AssetBundle" as a separate function.

### ISSUE THREAD

**Issue by CNDY-RollingSky** [Perfare/AssetStudio#525]
When loading an ab file which is compressed, AS will uncompress it autoly and then unpack it to recources. However, sometimes I just want to uncompress and then to save but not to unpack. 

Why not add "Uncompress an AssetBundle" as a separate features?

Now I have to use another app to finishi my work. QwQ

**Comment by Perfare** [comment]
Use File-Extract file or File-Extract folder.
