### ISSUE TITLE
About multiple uv export

### ISSUE THREAD

**Issue by CitrusAqua** [Perfare/AssetStudio#528]
Some games do need multiple UV rather than 1 UV and 1 normal map.
Possibly add an option when exporting?

**Comment by Sneakyerz** [comment]
This issue is still on-going with Asset Studio. I'm testing with Metal Revolution which runs on Unity and the 3D models has multiple UV's but the program cannot export multiple UV's, only the first UV gets exported.

**Comment by Perfare** [comment]
A new option has been added to support this feature.
