### ISSUE TITLE
Normal Maps turn red when using

### ISSUE THREAD

**Issue by MLSp3nce** [Perfare/AssetStudio#529]
So I was trying to rip a few different games, then I noticed for some of the games the Normal Maps would go red. When I rip the same games with a different software, however, it would be the normal blue color that a Normal-Map should be. Not sure why but yeah. 
![image](https://user-images.githubusercontent.com/57275043/79175445-bc58f100-7dcb-11ea-93e0-7e9b8fdbb48a.png)

**Comment by REDxEYE** [comment]
This is Unity normal map optimization. To get normal Normal map move Alpha channel to Green channel and fill Blue channel with pure white

**Comment by Perfare** [comment]
The picture export code should not have the problem of mixing channels, as REDxEYE said, this is Unity normal map optimization.
