### ISSUE TITLE
Use unpacked files to save RAM and CPU

### ISSUE THREAD

**Issue by An00nymushun** [Perfare/AssetStudio#530]
When you use the Extract folder feature, it extracts every file locally,
so then if you want to use the Load folder option on the game directory, it will load the unpacked files and start extracting the default files in memory

You should add this to LoadFolder (after ProcessingSplitFiles I think)
```cs
.Where(x => Path.GetDirectoryName(x).EndsWith("_unpacked") || !Directory.Exists(x + "_unpacked"))
```
to only use the unpacked files if they exist

**Comment by Perfare** [comment]
I think it is better to let users set the save location of the extracted files.
I will add this feature later.
