### ISSUE TITLE
Error when trying to extract some assets from Boxboy + Boxgirl (Nintendo Switch)

### ISSUE THREAD

**Issue by Machow8** [Perfare/AssetStudio#532]
Hi,

When i try to extract some of the files, errors appear:

http://prntscr.com/s16iuh
http://prntscr.com/s16jgz
http://prntscr.com/s16jr7
http://prntscr.com/s16k0p
http://prntscr.com/s16kc2
http://prntscr.com/s16kjr
http://prntscr.com/s16ks2
http://prntscr.com/s16kzm
http://prntscr.com/s16lps
http://prntscr.com/s16lxb

And some more.

I extracted files directly from game's romfs folder via asset studio x64 v0.14.38.

When you can solve those iees, i'll be much more thankful. =]

**Comment by Perfare** [comment]
Upload all the files to me, but from the screenshot of the error report, the file mentioned in the picture is missing.

**Comment by Machow8** [comment]
Hello,

Here you go: i uploaded all game files i extracted from romfs: https://www.mediafire.com/file/33mahctsspfs6wl/BoxboyBoxgirlNintendoSwitch.zip/file

**Comment by Perfare** [comment]
I did not encounter any errors. Because there are sharedassets0.assets.resS in the file you provided, this error is impossible unless the file in your folder has been deleted.

**Comment by caninosvermelhos** [comment]
Hey perfare your tool is capable of importing text files changes? Im tryng to translate the game.
