### ISSUE TITLE
Shape keys on some models not exporting correctly

### ISSUE THREAD

**Issue by DodoGam3r** [Perfare/AssetStudio#537]
![unknown (5)](https://user-images.githubusercontent.com/12139275/80344169-6d996580-8867-11ea-9c13-d4d967b4a303.png)

Those two files: https://1drv.ms/u/s!AnybY5k-uzdzgflL50Zvz1SqHZdcrg?e=xCiXwX

**Comment by Perfare** [comment]
This problem should be fixed now.
