### ISSUE TITLE
ExportAnimations question

### ISSUE THREAD

**Issue by heimodao** [Perfare/AssetStudio#544]
void Fbx::Exporter::ExportAnimations(bool eulerFilter, float filterPrecision)
	{
		auto importedAnimationList = imported->AnimationList;
		if (importedAnimationList == nullptr)
		{
			return;
		}
         ...
       }
       1.为什么imported->AnimationList的tracklist元素的path是null？这种导出的animator是没有动画的。
       2.有些imported->AnimationList的tracklist元素的path都是非null，但是导出的animator会丢失部分动作动画。
        如何解决这两个问题，请大佬赐教，指导方向。

**Comment by heimodao** [comment]
private string GetPathFromHash(uint hash)
        {
            bonePathHash.TryGetValue(hash, out var boneName);
            if (string.IsNullOrEmpty(boneName))
            {
                boneName = avatar?.FindBonePath(hash);
            }
            if (string.IsNullOrEmpty(boneName))
            {
                boneName = "unknown " + hash;
            }
            return boneName;
        }
        public string FindBonePath(uint hash)
        {
            return m_TOS.FirstOrDefault(pair => pair.Key == hash).Value;
        }
-----------------------------------------------------------------------------------------------------------
        public GenericBinding FindBinding(int index)
        {
            int curves = 0;
            foreach (var b in genericBindings)
            {
                if (b.typeID == ClassIDType.Transform)
                {
                    switch (b.attribute)
                    {
                        case 1: //kBindTransformPosition
                        case 3: //kBindTransformScale
                        case 4: //kBindTransformEuler
                            curves += 3;
                            break;
                        case 2: //kBindTransformRotation
                            curves += 4;
                            break;
                        default:
                            curves += 1;
                            break;
                    }
                }
                else
                {
                    curves += 1;
                }
                if (curves > index)
                {
                    return b;
                }
            }

            return null;
        }
---------------------------------------------------------------------------------------
FindBonePath里的key和hash经常不相等，导致找不到路径。genericBindings数组大于m_TOS数组，导致genericBindings里的path在m_TOS找不到对应的path。
不清楚assetbundle的格式，所以不明白这个是不是正常情况。请大佬赐教。

**Comment by Perfare** [comment]
从你的描述来看就是你选的Animator或者Object跟动画不匹配，所以动画的path hash自然没法找到真正的path
