### ISSUE TITLE
request for older versions 

### ISSUE THREAD

**Issue by icandancelikecool** [Perfare/AssetStudio#545]
one of the system requirements for the new versions is having .Net Framework 4.7.2, expect i keep getting errors that prevent me from downloading 4.7.2. Can someone lend me 1.4 or 1.3?

**Comment by TheLounger** [comment]
You can find older builds [here](https://ci.appveyor.com/project/Perfare/assetstudio/history). Builds are kept for 6 months. [Here's](https://ci.appveyor.com/project/Perfare/assetstudio/builds/31761334/artifacts) build 0.14.38, which is the one right before the `update to .net framework 4.7.2` build (0.14.19).

**Comment by Perfare** [comment]
I’m sorry I don’t plan to continue to support lower versions of the .net framework.
