### ISSUE TITLE
Error exporting animations

### ISSUE THREAD

**Issue by swampatha** [Perfare/AssetStudio#547]
Hello, I seem to be having some issues exporting the animations. Within [this](https://github.com/Perfare/AssetStudio/files/4613194/a_9ea334b3_4f7ff863.zip) file, there contains an animator along with multiple AnimationClips, however when I select the Animator or the Animator + AnimationClips, it will not export using "Expert selected objects (split) + selected Animation Clips, saying "No object can be exported." Any help here?

**Comment by Perfare** [comment]
You need to use Export-Export Animator with selected AnimationClip
