### ISSUE TITLE
can't load models from WOG

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#548]
here's example
[nagant_m1895.zip](https://github.com/Perfare/AssetStudio/files/4617269/nagant_m1895.zip)
it's cached files from: C:\Users\<User>\AppData\LocalLow\Unity\Noble Empire_World of Guns\

**Comment by Perfare** [comment]
I did not encounter any problems with the files you provided.

**Comment by Tosyk** [comment]
weird, maybe AS was updated from that time. I will check, thanks
