### ISSUE TITLE
Unsupport texture

### ISSUE THREAD

**Issue by trandontu** [Perfare/AssetStudio#551]
i'm trying to get Call of duty mobile asset. Model is ok but texture can't preview and export. The sample below. Thanks for help
[xgO_sgOJfm$1w$1w_1Do.zip](https://github.com/Perfare/AssetStudio/files/4625965/xgO_sgOJfm.1w.1w_1Do.zip)

**Comment by Perfare** [comment]
The game has customized data structure and cannot be supported.
