### ISSUE TITLE
Exported fbx files appear corrupted

### ISSUE THREAD

**Issue by MisterPrawn** [Perfare/AssetStudio#552]
When I export certain models from the game "House Party", some of the character meshes appear out of whack. 
![image](https://user-images.githubusercontent.com/27305795/81970379-4c10db80-95d4-11ea-8f52-be95c370f4cf.png)

And to further solidify this issue, the models in question when previewed in AssetStudio look like this: 
![image](https://user-images.githubusercontent.com/27305795/81970640-b32e9000-95d4-11ea-959c-2ec4a3033526.png)

Here's the exported FBX in question. If the direct game files are needed, let me know. Thanks!
[CH_Dan.zip](https://github.com/Perfare/AssetStudio/files/4630198/CH_Dan.zip)

**Comment by Perfare** [comment]
I have fixed a similar bug, because you did not upload the source file so I can’t test it, but I think there should be no problem.
