### ISSUE TITLE
Release expired

### ISSUE THREAD

**Issue by networm** [Perfare/AssetStudio#553]
Artifacts older than 6 months are automatically deleted. For more details see Artifacts retention policy.

[Packaging artifacts | AppVeyor](https://www.appveyor.com/docs/packaging-artifacts/#artifacts-retention-policy)

We couldn't download artifacts older than 6 months. I think it's better to save it in release page.
The best way is using shell script to upload to release automatically.

**Comment by Perfare** [comment]
Thank you for your reminder, because Unity will always release new versions, it is basically guaranteed that AssetStudio will be updated within six months.
But I will also consider uploading the build version to other places.

**Comment by networm** [comment]
I know AssetStudio will be updated within six months, but there is some goodies that old version offers: may be one old version have better compatibility with certain Unity version. And there are lots of legacy project using old Unity version. So I think it's good to keep all AssetStudio artifacts permanently.
