### ISSUE TITLE
Cannot access textures.bundle file because it is being used by another process

### ISSUE THREAD

**Issue by Rillz7** [Perfare/AssetStudio#556]
I am trying to load assets from the game Rust so I can get the models and make HD  pictures for thumbnails by using blender but the loading keeps getting stopped at textures.bundle and then gives the error "System.IO.IOException: The process cannot access the file 'C:\Program Files (x86)\Steam\steamapps\common\Rust\Bundles\shared\textures.bundle_unpacked\CAB-ecb18893e8022cd3473422c8de13be6d.resS' because it is being used by another process." 
I have no clue what process could be using it, i really don't think anything is. Can someone explain? Thanks a lot! 
Heres a picture: 
![a3743a6868f43c4e2a33d235b5b108d4](https://user-images.githubusercontent.com/65697030/82521608-1cdafc80-9af5-11ea-92a5-7fb1f2ed5829.png)

**Comment by phoondos** [comment]
I have the same problem

**Comment by Perfare** [comment]
@Rillz7 @phoondos Can you upload the textures.bundle file to me?

**Comment by Perfare** [comment]
Because this file is larger than 2gb after decompression, AssetStudio will decompress it to a folder with the suffix _unpacked before reading it. This error will occur if the File-Load folder is used after decompression. so you only need to delete this _unpacked folder.
