### ISSUE TITLE
Reset AssetStudio

### ISSUE THREAD

**Issue by Three65** [Perfare/AssetStudio#563]
For some reason my AssetStudio will no longer export any asset out it goes through the motions like its exporting out a file, but no file is created. I have tried deleting it and re-downloading it, however but it seems like something is still broken with it or my machine. One thing I noticed after deleting it and re-downloading it that my settings under the options was remembered. Is there some where on my system that a temp file would be that is keeping these settings that I need to delete?

**Comment by Perfare** [comment]
Local settings will be stored in C:\Users\UserName\AppData\Local\AssetStudioGUI
