### ISSUE TITLE
Unsupported bundle and building tree structure for hours

### ISSUE THREAD

**Issue by 09williamsad** [Perfare/AssetStudio#564]
Game: Gundam Battle CN
Version: 0.14.38
CPU: Ryzen 5 3600
RAM: 20GB
Game files: [https://mega.nz/folder/PT4wnIja#w1qy0KrBcqI2w9u0ubiueg](url)

On loading the game folder Asset Studio will load the assets then get stuck on "Building Tree Structure".
For around 10 minutes or so it will have 3GB to 8GB of RAM usage with around 10% CPU usage, after that its around 5MB RAM with the same CPU usage.

I left it doing that for around 8 hours and it did not complete.

**Comment by 09williamsad** [comment]
After some testing I have determined that this bundle is the cause
[p_1gkgja1_ui.zip](https://github.com/Perfare/AssetStudio/files/4866581/p_1gkgja1_ui.zip)

**Comment by Perfare** [comment]
These files should be encrypted.
