### ISSUE TITLE
TextAssets garbled

### ISSUE THREAD

**Issue by therealchjones** [Perfare/AssetStudio#566]
While I've had success accessing most assets, TextAssets from some programs are extracted as nonsense text (apparently ASCII-US encoded, but without other useful information). I have attached one bundle in which this is particularly prominent; MonoScript and MonoBehavior assets are displayed and extract as expected, but most (not all) of the TextAssets are not readable. I am unable to determine if this is a product of serialization or encoding/encrypting, or a limitation of AssetStudio. Thank you for investigating.

[text.zip](https://github.com/Perfare/AssetStudio/files/4863901/text.zip)

**Comment by Perfare** [comment]
TextAssets does not mean that it is a plaintext txt file, programmers can store files in any format as TextAssets.
