### ISSUE TITLE
Compatibility issue with Castlevania: Grimoire of Souls

### ISSUE THREAD

**Issue by radzo73** [Perfare/AssetStudio#568]
Because currently, you can only export meshes as .obj, meaning that you lose things such as vertex/boneset weights.

**Comment by 09williamsad** [comment]
There is an option to export rigged models as FBX.
Model tab > Export

**Comment by radzo73** [comment]
what if the mesh has weights, but it's separate from the boneset? Can the mesh be exported as a .fbx then?

**Comment by 09williamsad** [comment]
> 
> 
> what if the mesh has weights, but it's separate from the boneset? Can the mesh be exported as a .fbx then?
As far as I am aware in Unity if a model has weights then it has bones.

**Comment by radzo73** [comment]
That apparently isn't the case for games like Castlevania: Grimoire of Souls. In that game, meshes are stored separately from the bonesets (I assume to save on space because there's no need to have 18 duplicates of the same boneset when every costume can use the one boneset), meaning that currently, we can only export said meshes as .obj, meaning that we lose all the boneset weights the mesh had.

**Comment by 09williamsad** [comment]
> 
> 
> That apparently isn't the case for games like Castlevania: Grimoire of Souls. In that game, meshes are stored separately from the bonesets (I assume to save on space because there's no need to have 18 duplicates of the same boneset when every costume can use the one boneset), meaning that currently, we can only export said meshes as .obj, meaning that we lose all the boneset weights the mesh had.

Sounds like a game compatibility problem, uploading asset bundle samples may help.

**Comment by radzo73** [comment]
[p001ab.zip](https://github.com/Perfare/AssetStudio/files/4939172/p001ab.zip)

**Comment by 09williamsad** [comment]
Took a look at the game files and it looks to be a compatibility issue.
I suggest you change the issue title to reflect that.
Game files https://mega.nz/file/bD5TlJIY#Mq4-lXks7F5330zJHsPXIpRaRMiUiW3nBL0cSFpwXCc

**Comment by Perfare** [comment]
I don’t quite understand your problem. First of all, the file you provided is incomplete and it can’t be exported. I used the game file provided by 09williamsad and checked the exported fbx, and I did not encounter any bone problems.

**Comment by 09williamsad** [comment]
> 
> 
> I don’t quite understand your problem. First of all, the file you provided is incomplete and it can’t be exported. I used the game file provided by 09williamsad and checked the exported fbx, and I did not encounter any bone problems.

His issue is that a specific model does not export with a rig.
The meshes p001 and a01_p001 which appear to be p001, p001_1 and p001_2 in the hierarchy.

**Comment by Perfare** [comment]
I verified these files again, Mesh is not linked to any SkinnedMeshRenderer, so when exporting the model from the hierarchy, It did not get any bound mesh.
But in fact, the corresponding Avatar can be judged by the name, for example, the Avatar of p001 is p001Avatar. With Avatar, we can export a complete model including bones, but it is difficult to automate through code.
