### ISSUE TITLE
Can't load the files

### ISSUE THREAD

**Issue by Alexis33700** [Perfare/AssetStudio#571]
Hello, I am not sure I am in the right place but I have a problem with AssetStudio, I can't look the file preview for Texture2D and I have an error message.
Tell me if you need more informations.
Thank you for helping me

![image0](https://user-images.githubusercontent.com/68435555/87803180-712efe00-c852-11ea-9db2-5e8c7cb91719.jpg)

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#requirements
