### ISSUE TITLE
Mario Kart Tour files not being loaded

### ISSUE THREAD

**Issue by Ziiella** [Perfare/AssetStudio#573]
The files for the latest version of Mario Kart Tour don't appear to be loading into AssetStudio v0.14.38. When opening the file, there is no error messages or anything and just says "No File Loaded". According to the file, the unity version should be 2018.4.21f1.

Here's a sample file. 
https://drive.google.com/file/d/1i8MHEBPJJSoQY5wup4fcuKI4Thime1qU/view?usp=sharing

**Comment by Ziiella** [comment]
After some experimenting it seems to be related to 0x0D0A EOL bytes. When I change all instances of 0x0D0A to just 0x0A, it seems to work. Not sure if this is an issue with the software or my computer.

**Comment by Perfare** [comment]
I think this is a means by which the game prevents assets being extracted.

**Comment by Perfare** [comment]
Because the problem has been solved, I will close this issue. If you have other problems, you can open a new issue.
