### ISSUE TITLE
Random GDI+ exception when exporting large list of files

### ISSUE THREAD

**Issue by marcselman** [Perfare/AssetStudio#574]
I have a large list of assets.
I filter on Texture2D and then export filtered assets.
After about 200 items or so it gives a dialog about a GDI+ exception in `System.Drawing.Image.Save`.

**Comment by marcselman** [comment]
Ah, apparently it's because when opening the assets it took up some GBs of extra diskspace. Then while exporting it ran out of space. So I guess the tool should catch that exception and show a diskspace warning dialog?

**Comment by hozuki** [comment]
It should be related to #570.

**Comment by Perfare** [comment]
Should be fixed.
