### ISSUE TITLE
Others formats

### ISSUE THREAD

**Issue by Contra6** [Perfare/AssetStudio#576]
Hi, i want know, you planning add in future others format?
Here list (believe their many) But write a little.
It games from mobile
**************************************
Art of Conquest (unknown .BIN,ARC)
A Certain Magical Index (NPK,MAP)
Dawn of Titans (unknown .BOF)
DreamWorks Universe of Legends (unknown .KUF)
Disney Magic Kingdoms (unknown .BDAE)
Heroes of Order & Chaos (unknown .BIN)
LEGO Star Wars: The Force Awakens (unknown .FIB)
MARVEL Super War (unknown .NPK)
Mortal Kombat (unknown .PAK)
Minion Rush (unknown .JPK)
Tales of Edeland (unknown .PFS)
Teenage Mutant Ninja Turtles: Legends (unknown .DAB,DSB,DHR)
The Elder Scrolls: Blades (unknown .BNK,WEM)
**************************************

**Comment by Perfare** [comment]
I’m sorry, this program is only designed to extract Unity resources.
