### ISSUE TITLE
Audio Files Missing

### ISSUE THREAD

**Issue by Frogman9** [Perfare/AssetStudio#579]
This may or may not be related to this amazing software:
The game One Piece Bounty Rush is one of those where you must download additional files upon first launch. 
After the download, if I use this (or UABE) to extract all the .unity3D files, I get a bunch of stuff, but no audio files. Nothing in the OBB folder, either. 
So, as far as I can tell, either the audio files are compressed again somehow within the .unity3D files, or AssetStudio is not able to see them (along with UABE).

**Comment by Perfare** [comment]
If you load all the Unity files and do not see the AudioClip, it usually means that the game may not use Unity's audio system. This is actually very common. At this time, the audio files should be placed in a separate folder. Or the game may encrypt the audio. Putting it in TextAsset is possible. Further research is needed.

**Comment by Frogman9** [comment]
> If you load all the Unity files and do not see the AudioClip, it usually means that the game may not use Unity's audio system. This is actually very common. At this time, the audio files should be placed in a separate folder. Or the game may encrypt the audio. Putting it in TextAsset is possible. Further research is needed.

I have been poking around and still haven't found where they tucked the audio files, what could they encrypt them with or would there be any rhyme or reason to the hiding them in the TextAsset?

**Comment by Ryukomat44** [comment]
> > If you load all the Unity files and do not see the AudioClip, it usually means that the game may not use Unity's audio system. This is actually very common. At this time, the audio files should be placed in a separate folder. Or the game may encrypt the audio. Putting it in TextAsset is possible. Further research is needed.
> 
> I have been poking around and still haven't found where they tucked the audio files, what could they encrypt them with or would there be any rhyme or reason to the hiding them in the TextAsset?

can u check the streaming assets folder to see if the audio files are in .BANK format? cause then u can turn them into .FSB and then extract them to .wav
