### ISSUE TITLE
Large memory usage.

### ISSUE THREAD

**Issue by Gigabait** [Perfare/AssetStudio#581]
What the fuck. I have only 16gb ram and this program use all of that. 
If I understand that this program decodes all files, and it doesn't matter if this file is opened in preview or not.
Who in the world use this. 
Fix this problem. If you look at other programs of this kind you won't see a lot of memory usage there.

**Comment by Perfare** [comment]
I think you are opening a bundle file, if you open it directly, AssetStudio will decompress it in the memory and read it, so it will take up a lot of memory.
You can use v0.15.5 and later version, use File-Extract file or File-Extract folder to decompress the bundle file to the local, and then load it with AssetStudio,

**Comment by Gigabait** [comment]
@Perfare Now i use latest version. I decompressed folder and load it with AssetStudio. About a 8k files... And it still uses up a lot of memory. 
Why programm read all files ? Its very bad. Why not just read the file names and add him to ListView and after user click to file in line of the ListView it was be read ?

**Comment by Perfare** [comment]
Note that the decompressed file should not be placed in the same folder as the original file.
This is the way the program was originally designed, I don’t have more energy to refactor, sorry.
