### ISSUE TITLE
Issue with extracting Sprite/Texture2D from mobile game

### ISSUE THREAD

**Issue by lyouma** [Perfare/AssetStudio#582]
Hi, I'm trying to extract sprites and convert them into .png files but I keep getting this error.

![image](https://user-images.githubusercontent.com/69379908/89703669-67a92b00-d912-11ea-8969-43bf42f96770.png)

**Comment by hozuki** [comment]
The same problem in #585

**Comment by Perfare** [comment]
Download the latest version, this problem should be fixed.
