### ISSUE TITLE
Texture2D Preview Error（Original File）

### ISSUE THREAD

**Issue by EndlessMISAKA** [Perfare/AssetStudio#586]
大佬好，我又来了，谢谢您开发的工具。

关于部分图片预览失败的问题，
![QQ截图20200809182700](https://user-images.githubusercontent.com/25360394/89730082-18780d00-da6e-11ea-8d72-482ff2fc41fa.jpg)

在旧版（我忘了是哪个版本了，应该是0.12附近）是正常的。
![QQ截图20200809182714](https://user-images.githubusercontent.com/25360394/89730083-1c0b9400-da6e-11ea-8ad9-8bff7b375254.jpg)

源文件：
[assets.zip](https://github.com/Perfare/AssetStudio/files/5047205/assets.zip)

**Comment by hozuki** [comment]
#585 
有没有安装[2015-2019的vcredist](https://support.microsoft.com/en-us/help/2977003/the-latest-supported-visual-c-downloads)？

**Comment by Perfare** [comment]
下载最新版本，现在不需要安装vc运行库了。
