### ISSUE TITLE
il2cpp Type Exception + Fix

### ISSUE THREAD

**Issue by atom0s** [Perfare/AssetStudio#587]
Firstly, thanks for the great tools. I'm new to tinkering with Unity-based games and your work has been greatly helpful. :) 

I noticed that AssetStudio does not seem to like games that are compiled with il2cpp and had issues getting it to dump MonoBehaviour assets.

To fix this and replicate a working setup for me, this is what I did:

1. Dump the game using your il2cppDumper tool: https://github.com/Perfare/Il2CppDumper
2. Open the target asset in AssetStudio. (In my case, sharedassets0.assets)
3. Choose 'Asset List' and find the specific MonoBehaviour I wish to dump.
4. At this point, AssetStudio will only dump the header and error with `Error while dump type`

This appears to be due to script dumper throwing errors on System based types when checking if the type is from Unity inside of `IsAssignFromUnityObject`. This can be "fixed" and avoided by adjusting the function to the following:

```csharp
        private static bool IsAssignFromUnityObject(TypeDef typeDef)
        {
            if (typeDef.FullName == "UnityEngine.Object")
            {
                return true;
            }
            if (typeDef.BaseType != null)
            {
                if (typeDef.BaseType.FullName == "UnityEngine.Object")
                {
                    return true;
                }
                while (true)
                {
                    if (typeDef.BaseType != null &&
                        typeDef.BaseType.FullName.StartsWith("System."))
                        return false;

                    typeDef = typeDef.BaseType.ResolveTypeDefThrow();

                    if (typeDef.BaseType == null)
                    {
                        break;
                    }
                    if (typeDef.BaseType.FullName == "UnityEngine.Object")
                    {
                        return true;
                    }
                }
            }
            return false;
        }
```

This will prevent dnlib from throwing and killing the parse attempt when a System based type is hit. 
Now the MonoBehaviour will fully dump as expected.

_Untested outside of 1 game and a few asset files, so not sure if this will have any negative side affects._

**Comment by Perfare** [comment]
First of all thank you for your support. 
The original intention of Il2CppDumper was to analyze the MonoBehaviour of the il2cpp game. The reason why it was not put in AssetStudio is because usually il2cpp game executable files are encrypted, so users still need to perform manual operations on Il2CppDumper.
I just refactored the parsing logic of MonoBehaviour. It now uses cecil as a reading tool. I am not sure if this problem still exists. You are welcome to test it. If you have any problems, please let me know.
