### ISSUE TITLE
Assetbundle file can't be extracted

### ISSUE THREAD

**Issue by asdfghjklu2000** [Perfare/AssetStudio#590]
Hi,

I have some assetbundle files listed below from this game 'Tower of Saviors', and I want to extract them.

https://ab.tosconfig.com/assetBundleFiles/android/43B376A89BD0C9E39E408C5A0143436563CEAB6D.assetbundle
https://ab.tosconfig.com/assetBundleFiles/android/CC54ADA3298065E0C169EE94001273A5C150EB50.assetbundle
https://ab.tosconfig.com/assetBundleFiles/android/E1188C052DCCB0408B1635BF5A8ACA9713E5B147.assetbundle
https://ab.tosconfig.com/assetBundleFiles/android/6F239089E212E41AC016FA7D067884ECA5A87F99.assetbundle
https://ab.tosconfig.com/assetBundleFiles/android/E5D39CD982835DE161C2D6C0366988106C74A6E3.assetbundle

But I can't load these file in AssetStudio. If I extract them into extract folder then I can't recognize what file type they are.
So I'm wondering are these assetbundle file have been encrypted or some other reason?

Thank you!

**Comment by Perfare** [comment]
These files erased the version numbers in the file header, causing AssetStudio to be unable to read them. You can manually add the correct version number to the 0.0.0 position, and it should be resolved.
![image](https://user-images.githubusercontent.com/12952226/90216057-1f1cd080-de30-11ea-8f7d-fb1179c2dda9.png)

**Comment by Perfare** [comment]
Supplementary note, you need to extract assetbundle into assets and then modify.

**Comment by asdfghjklu2000** [comment]
Ok, thank for your tips.
I can make sure one thing is they build these file in Unity Version "**2019.3.0f6**".
So here it is
1. Use AssetStudio extract these assetbundle files.
2. Fix all the assets in each folder.
3. Repack them to a assetbundle file(Excuse me I am not sure what **tool** I may use?).
4. Load them into AssetStudio.

Is that right? I'll try to fix it and thank you again!
