### ISSUE TITLE
Dude, this made my pc fucking die

### ISSUE THREAD

**Issue by yellowface7** [Perfare/AssetStudio#592]
So I tried to load something up and while the GUI is reading, all of the little amount of memory remaining disappeared and my computer started to freak out.

I had like 10 gigs and the read process ate it all, so I had to panic close the program. Now I have like 7 gigs left.

**Comment by Perfare** [comment]
https://github.com/Perfare/AssetStudio#load-assetsassetbundles
You may need to decompress them locally first.
