### ISSUE TITLE
Normal MAP

### ISSUE THREAD

**Issue by Nazarus13** [Perfare/AssetStudio#593]
Hello, i used Asset GUI on game Raid:Shadows Legend & all perfect, except normal map.
I dont know why, but Bump is orange.
How it must be:
![изображение](https://user-images.githubusercontent.com/69793579/90383487-e3c90e80-e088-11ea-81d2-36c93ba756de.png)
& i have it )
![изображение](https://user-images.githubusercontent.com/69793579/90383569-fd6a5600-e088-11ea-847f-217608d78925.png)

**Comment by Nazarus13** [comment]
Guys, i found theme #529 
Answer: This is Unity normal map optimization. To get normal Normal map move Alpha channel to Green channel and fill Blue channel with pure white
Can you tell me please, How to do it in CS6 Photoshop or another programm.
Please.

**Comment by IrfanRahmat007** [comment]
Export the normal map manually from Asset List tab as tga (set the format from export option menu) then you should be able to access the alpha channel in photoshop. You can move it to other channel by clicking the alpha channel, select all area, cut and then paste it to the red channel. you can fill blue channel with the bucket tool.

**Comment by Nazarus13** [comment]
Thanks man!
I did a mistake, i exported png..
