### ISSUE TITLE
Copying pathID from context menu

### ISSUE THREAD

**Issue by Aceship** [Perfare/AssetStudio#594]
Is it possible to add copy path id through the context menu ?
![image](https://user-images.githubusercontent.com/5337323/91072218-5cb8ff00-e663-11ea-8b53-c7807cfc4b78.png)

**Comment by Perfare** [comment]
The function of the copy menu is to copy the text that your mouse is pointing at.

**Comment by Aceship** [comment]
ah i thought it was to copy the file, cause selecting it highlight the whole row

**Comment by Perfare** [comment]
Ok i will change it.
