### ISSUE TITLE
textures wasn't extracted currectly from APK asset bundell

### ISSUE THREAD

**Issue by bob-morane** [Perfare/AssetStudio#598]
I tried to extract assets from call of duty mobile but all textures in asset list have very small size that ignored to export or they are damaged .

![P_BR_ShipCargo_Building_TODLightmap](https://user-images.githubusercontent.com/70179203/91718780-4eaa3780-eba9-11ea-8982-48294a089071.png)

**Comment by Perfare** [comment]
You need to upload the source file to me, but I think the game should modify the structure of Texture2D.

**Comment by bob-morane** [comment]
this is the link of .obb file 

[](https://www.dl.farsroid.com/game/Call-of-Duty-Mobile-1.0.16(www.Farsroid.com).zip)

**Comment by bob-morane** [comment]
[https://www.dl.farsroid.com/game/Call-of-Duty-Mobile-1.0.16(www.Farsroid.com).zip](url)

**Comment by Perfare** [comment]
Custom Unity structure.
