### ISSUE TITLE
Issues with directory ("Cannot open included file 'fbxsdk.h': No such file or directory")

### ISSUE THREAD

**Issue by race9000** [Perfare/AssetStudio#600]
I've been having troubles with the changing the directory to FBX SDK; whenever I try to build it throws this error. Does anyone know why this is happening and how to fix it?
![FileNotFound](https://user-images.githubusercontent.com/70740087/92202374-7bc64680-ee44-11ea-8d3e-f8a99527ab88.png)

**Comment by Perfare** [comment]
You need to set the directory to the exact directory instead of the root directory of FBX. For example, the include directory should be set to `FBX SDK\version\include`.

**Comment by race9000** [comment]
> You need to set the directory to the exact directory instead of the root directory of FBX. For example, the include directory should be set to `FBX SDK\version\include`.

I tried setting the Include Directory to 'FBX SDK\2020.0.1\include' and the Library Directory to 'FBX SDK\2020.0.1\lib' but it still returned the same result, regardless of if I had 'inherit from parent or project defaults' enabled. (I did use a freshly downloaded version)

**Comment by Perfare** [comment]
Sorry because this question is not actually related to AssetStudio, I cannot provide more help, I recommend you to use search engines for more help.

**Comment by oOtroyOo** [comment]
My solution . open AssetStudioFBXNative.vcxproj by Text,
search all `"C:"` , Replace each to your installed SDK location ,such as `include`,`lib` , and make sure your `vs20xx` folders exsist in subdirectory of `lib`.
