### ISSUE TITLE
Cant't load texture files

### ISSUE THREAD

**Issue by fdtggf** [Perfare/AssetStudio#604]
This file is come from a moblie game "Blade Xlord"

Original files AssetStudio can't read.
I use HxD delete first line"09 08 06 01" and change fifth word to "55"(U).
Then AssetStudio can read head,body textures and mesh,
But character hair texture files can't read yet.
I think reason is file headline have something wrong.
Can you help me take a look?

[sample](https://mega.nz/file/BJxlUbZK#1350NKV2cyh_UHt7dmx4tXs27Z-JQWGlH3tTcJNFUSw)

**Comment by Perfare** [comment]
According to your description, these files should be XOR encrypted.
