### ISSUE TITLE
Normal maps export red instead of standard blue

### ISSUE THREAD

**Issue by rfs5052** [Perfare/AssetStudio#605]
![weapon_repeating_smle_1p_nrm](https://user-images.githubusercontent.com/70817727/92311400-a9b2a480-ef84-11ea-978b-c460fa223d9e.png)

This is an example of one such normal map. When extracted, it came out red instead of blue. The red channel appears to be missing its data, and the alpha channel contains one of the color channels instead. I tried various ways of rearranging them, but I couldn't get it to come out blue again.

**Comment by IrfanRahmat007** [comment]
Export manually as tga from the asset list tab, move alpha content to green channel and fill blue channel with white. I think this is just how the developer made the texture since somone has the same problem as yours (check the resolved section of issues)

**Comment by rfs5052** [comment]
Thanks, that fixed the issue! There is a step that you forgot to mention tho. Replace Red with Green, Green with Alpha, and Blue with Red.

**Comment by ag2s20150909** [comment]
![](https://ftp.bmp.ovh/imgs/2020/09/842b56e4860c49ad.png)

**Comment by tERB00** [comment]
Sorry for bumping an old thread but... Does anybody know a tool to mass-convert normal maps from unity to regular format? Or maybe someone can make a little python script or something?
