### ISSUE TITLE
Missing AudioClips?

### ISSUE THREAD

**Issue by AndnixSH** [Perfare/AssetStudio#606]
Some Unity games begin to hide some AudioClips or even completely gone from assets list, but none of AudioClip assets file are removed. I'm not sure if it has been converted to new format that AssetStudio couldn't read.

Pokemon Go is an example that they removed AudioClips in around septemper 2019. I did checked downloaded content on /data/data and /Android/data, only 2 AudioClips found. Yes, I did dropped the assets folder to read all assets at the same time

This is the last version (and below 0.153.0) with all audioclips https://www.apkmirror.com/apk/niantic-inc/pokemon-go/pokemon-go-0-153-0-release/pokemon-go-0-153-0-android-apk-download/download/

![image](https://user-images.githubusercontent.com/40742924/92323652-aed22b00-f03a-11ea-8fec-e2d704fabd37.png)

This is the version (and above 0.157.0) with missing audioclips https://www.apkmirror.com/apk/niantic-inc/pokemon-go/pokemon-go-0-157-0-release/pokemon-go-0-157-0-2-android-apk-download/download/

![image](https://user-images.githubusercontent.com/40742924/92323655-b2fe4880-f03a-11ea-8de3-2a3015e8bcb2.png)

**List is sorted as size. Notice the difference**

Downloaded content: https://drive.google.com/file/d/1T48MfROfXBL9POoYpedAryeMAcPx7tWd/view

![image](https://user-images.githubusercontent.com/40742924/92323646-a7128680-f03a-11ea-80fa-3bde7f0f0691.png)

I'm not sure what i'm missing. Do you know what's going on?

**Comment by Perfare** [comment]
#579
