### ISSUE TITLE
AssetStudioGUI has stopped working

### ISSUE THREAD

**Issue by guanzhangrtk** [Perfare/AssetStudio#607]
![image](https://user-images.githubusercontent.com/44019025/92468706-6de82c80-f188-11ea-930d-534f09df3fa1.png)

Any ideas why this is happening? The files seemingly exported correctly, here are the error messages:

Problem signature:
  Problem Event Name:	CLR20r3
  Problem Signature 01:	AssetStudioGUI.exe
  Problem Signature 02:	0.15.20.0
  Problem Signature 03:	ca876fba
  Problem Signature 04:	System
  Problem Signature 05:	4.7.3451.0
  Problem Signature 06:	5d37b695
  Problem Signature 07:	2fe0
  Problem Signature 08:	29b
  Problem Signature 09:	System.ComponentModel.Win32
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	1033
  Additional Information 1:	0a9e
  Additional Information 2:	0a9e372d3b4ad19135b953a78882e789
  Additional Information 3:	0a9e
  Additional Information 4:	0a9e372d3b4ad19135b953a78882e789

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt

Running on Windows 7 32-bit (please don't judge :P) Thanks!

**Comment by Perfare** [comment]
You may need to check the memory usage, the 32-bit machine may not have enough memory to run AssetStudio.

**Comment by guanzhangrtk** [comment]
Thanks for the response. There are instances where the machine does run out of memory and it would show a different error message (which said that it ran out of memory). If I check the memory usage and it's not very high, is this something you can look into? Also, sometimes when I try to export assets it would crash immediately after it's done, not sure if they are related or not, thanks again!

**Comment by Perfare** [comment]
Sorry to reply to you now. If you still encounter this problem, I need more detailed information, in the Windows Event Viewer, view application events, you should see an error whose source is .NET Runtime, give me its details, thanks.
