### ISSUE TITLE
0.15版本的怎么运行

### ISSUE THREAD

**Issue by IrisSundew** [Perfare/AssetStudio#612]
把x64文件夹里的文件丢到软件根目录下也不能运行，而0.14版本的就能用

**Comment by Perfare** [comment]
不需要移动任何文件，直接全部解压，确保电脑已安装.NET Framework 4.7.2，最好使用win10运行

**Comment by IrisSundew** [comment]
感谢大大回复，我直接解压拉到磁盘目录下可以打开了，应该是我之前放的文件夹是中文命名的关系




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Perfare/AssetStudio"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2020年12月14日(星期一) 凌晨1:33
收件人:&nbsp;"Perfare/AssetStudio"<AssetStudio@noreply.github.com&gt;;
抄送:&nbsp;"Iris露Sundew🎐📮"<1595648424@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [Perfare/AssetStudio] 0.15版本的怎么运行 (#612)





 
不需要移动任何文件，直接全部解压，确保电脑已安装.NET Framework 4.7.2，最好使用win10运行
