### ISSUE TITLE
can't load models from WOG (again)

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#615]
It's been from #548. I'm trying to load this asset without any luck with latest (AssetStudio.v0.15.20) build.

All I see is this:
![image](https://user-images.githubusercontent.com/24209966/93665324-3af24280-fa7e-11ea-9bcd-3cb9cde92932.png)

can you check it one more time?

p.s.: there's should be model and textures of this gun:
![image](https://user-images.githubusercontent.com/24209966/93665425-12b71380-fa7f-11ea-97c3-ed45323434e4.png)

**Comment by Perfare** [comment]
If you think this asset is a model, it usually means that the developer converted the model to binary and put it in the TextAsset.

**Comment by Tosyk** [comment]
so how to convert this ASCII type model?
