### ISSUE TITLE
Broken skeleton when importing to blender

### ISSUE THREAD

**Issue by Hiccupcc** [Perfare/AssetStudio#619]
Whenever I try to export a mesh from a unity game with it's skeleton using Model --> Export Selected Objects (Merge), the skeleton becomes really messed up as shown in the picture above. 

It's exported as an FBX file, and the way I import it into blender is by going to File --> Import --> FBX

(Blender version 2.79, AssetStudioGUI v0.15.20)
(First image is the broken skeleton with the mesh, second image is what I select from the scene hierarchy, third image is the mesh without exporting the skeleton too)
![Blender File](https://user-images.githubusercontent.com/69525619/94371746-1ab72900-00f9-11eb-9b4c-dbe47572106f.PNG)
![AssetStudio 1](https://user-images.githubusercontent.com/69525619/94371777-4c2ff480-00f9-11eb-9905-801ec009d54e.PNG)
![Blender File 2](https://user-images.githubusercontent.com/69525619/94371870-e728ce80-00f9-11eb-8254-139d756899b1.PNG)

**Comment by Tosyk** [comment]
Hiccupcc, what you consider as broken skeleton? the view of it in the preview or it doesn't bound to your model?

**Comment by Hiccupcc** [comment]
> Hiccupcc, what you consider as broken skeleton? the view of it in the preview or it doesn't bound to your model?

The skeleton in the first image sort of doesn't bound to my model, and the skeleton is way larger than the mesh itself, to the point where it's not seen. The rig still works, but it's not set correctly.

**Comment by 127lh** [comment]
give me the file. i'll fix it

**Comment by Perfare** [comment]
I need the source file to check this error.

**Comment by DonovanPhoenix** [comment]
I have the same issue
![image](https://user-images.githubusercontent.com/40139772/104831598-19219480-5893-11eb-8bec-5b1321cb13af.png)
That small spiky thing is the armature

here is the data file
[__data.zip](https://github.com/Perfare/AssetStudio/files/5825584/__data.zip)

I can also probably help with an original source file if that would help.

**Comment by helpplease1108** [comment]
Ihave same issue
