### ISSUE TITLE
Morphs export fbx

### ISSUE THREAD

**Issue by nigthshadex** [Perfare/AssetStudio#69]
Is there ways to export models that has blend shape keys loaded in them, and export them properly from it?

**Comment by Perfare** [comment]
Sorry, I don't understand what you say

**Comment by Tosyk** [comment]
nigthshadex, meant morphs. like on this picture: 
![image](https://user-images.githubusercontent.com/24209966/27727789-a244c746-5d88-11e7-96cc-fd16f58143e3.png)
it's when same mesh differently deformatted for animating head or face. it's another type of animation besides animation with bones.

**Comment by nigthshadex** [comment]
Aye, like what Tosyk mentioned. Sometimes, there's meshes that uses morph method, rather than rigging. I know some games uses morph methods, and wonder if theres a way to extract them as well?

**Comment by nigthshadex** [comment]
Would you be able to look into this? Perfare

**Comment by Perfare** [comment]
Sorry, I lack of 3d model knowledge, It is beyond my ability

**Comment by Tosyk** [comment]
it's year passed, have you learn something about morphs?
they could store as a separate deformed geometry with same polycount as basic mesh or as pure transform data for one basic mesh

**Comment by Perfare** [comment]
@Tosyk Morphs should be able to export using the new fbx export feature.

**Comment by Tosyk** [comment]
Oh, wow! thanks for this! really! :)
