### ISSUE TITLE
Models exporting not in t-pose

### ISSUE THREAD

**Issue by Tosyk** [Perfare/AssetStudio#70]
I need models in t-pose to be exported.
If I open model in preview window in Unity Studio it appears like this:
![111](https://user-images.githubusercontent.com/24209966/28237681-e217a638-694d-11e7-8b37-538513879080.png)

but after export model looks like this:
![221](https://user-images.githubusercontent.com/24209966/28237682-ed170a6a-694d-11e7-9345-17b7b41ce386.png)

it's like first frame of animation been applied to the mesh.

Is there a way to export models in t-pose?

**Comment by Tosyk** [comment]
I updated request with images.

**Comment by Yuuyatails** [comment]
I have also faces this issue when trying to extracting 3d model from certain games. It appears that some 3d models are pre-rotated.

**Comment by Perfare** [comment]
Sorry, I lack of 3d model knowledge, It is beyond my ability

**Comment by Perfare** [comment]
Can you check these files with the new export model feature? I think the problem may have been solved.

**Comment by Tosyk** [comment]
Have checked and got same result.

**Comment by Perfare** [comment]
Can you upload files?

**Comment by Tosyk** [comment]
sure: https://drive.google.com/file/d/1qSbg92Rl35klt_-J9-4ux8FOs1__VLvc/view?usp=sharing
it's antisquad tactics

**Comment by Perfare** [comment]
I checked the file, the problem should be as described by the Yuuyatails, if export the model with skin, this situation can't be avoided.
By the way, thanks for this file, I fixed a bug and can now export the model with its binding animation from Scene Hierarchy.

**Comment by Tosyk** [comment]
So the reason why exported models are not in t-pose is because game just don't have t-pose frame for this models, correct?

**Comment by Perfare** [comment]
yes

**Comment by Tosyk** [comment]
this must be closed then. thank you for checking it.
