### ISSUE TITLE
Will support on exporting skeletion in future?

### ISSUE THREAD

**Issue by ngovandang** [Perfare/AssetStudio#82]
For new unity files. I can only export model as OBJ on Assets tab
There is no way to get skeletion?

**Comment by Perfare** [comment]
Export - All 3D Objects or Selected 3D Object will export model with skeletion

**Comment by ngovandang** [comment]
Yeah I did, but on Crossfire Legend or Crossfire Mobile
I can get model with skeletion, I think its locked some where
Found it from Assets Tab but not found on tree list
Also export models from Assets tab got no UV
