### ISSUE TITLE
Issue exporting 3D Models from Scene Hierarchy

### ISSUE THREAD

**Issue by RobertTopala** [Perfare/AssetStudio#88]
When I export a 3D model from the Scene Hierarchy, even it's in another parent, also export 3D models from other things

**Comment by Perfare** [comment]
If you choose export "Skin Deformers", this problem will happen when you choose something that contains LimbNode, but LimbNode father or childis in other things.

**Comment by RobertTopala** [comment]
It doesn't seems the problem, it's like in Unity Studio assign like Combined Root Meshes, and the 3D model I want to export it's fusioned with the other meshes, and then, causes in a broken 3D model that it's des-organizated and gives me pieces from other Combined Root Meshes

**Comment by JuGGerNaunT** [comment]
Unity combine meshes of static objects at build time. Asset contains several submeshes, and those submeshes corresponts to initial meshes in Unity. The thing is MeshFilter and MeshRenderer components knows nothing abount submesh's index, only whole mesh reference.
Other problem is about objects with same material but different texture property for this metarial still combining in same mesh. So the best you can do is export submeshes as different fbx-es and apply materials for each one separetly

**Comment by Alvarezmd90** [comment]
I cannot seem to do that with scenes from Before The Storm. It just generated one big fbx which totally looks like a twisted up ball of geometry. I will look into this again. I'm using the latest 0.8.
