### ISSUE TITLE
Life is Strange Before the Storm Eye Issue

### ISSUE THREAD

**Issue by Escope12** [Perfare/AssetStudio#92]
When I Extract the models from Life is Strange Before the Storm, their eyes look so weird.
![img_5426](https://user-images.githubusercontent.com/8963276/30518165-b4cde836-9b43-11e7-8096-55b2b54d21d7.PNG)

**Comment by Stellarspace** [comment]
Maybe you should upload the file to Mega instead of giving a screenshot and saying a general statement.

**Comment by carpedee** [comment]
Here is a mesh with a similar issue (from the same game), the eyes are displaying no iris (the textures are exported though): https://www.mediafire.com/file/8ivho13d097e7wc/mesh.zip
FBX exported using the last version of UnityStudio (I included the textures).

There is another issue: when I export with the skeleton (whether as bones or dummy), I can see it perfectly in Noesis but when I load the fbx in Maya or 3dsmax, the bones are all over the places with this error (for this very mesh) "[WARNING] BindPose - Incomplete BindPose [nodes parents] - The following parent and/or ancestor node(s) is/are not part of the BindPose definition. CH_S_Rachel_Punk"

Note: the game was ade using Unity 5.5.3p1

Any ideas explaining this issue?
Thanks!

**Comment by Escope12** [comment]
![cc0f4059-aa3f-4b0f-ba4a-acb19e632aa5](https://user-images.githubusercontent.com/8963276/32146246-a119f252-bcaa-11e7-966d-0f0cb62c4fd9.png)
The eyes are supposed to look like this.

**Comment by Alvarezmd90** [comment]
This is not an issue with the extractor. The game uses Eye Advanced shader: https://www.assetstore.unity3d.com/en/#!/content/30762 from Tanuki Digital. It creates a non-existent eye texture controlling various settings like pupil dilation and parallax effects.

**Comment by Escope12** [comment]
Is there a way to recreate the eye to look like that?

**Comment by Alvarezmd90** [comment]
Yes. By combining the sclera texture with the iris texture. Shader gives
best result though.

Op 13 dec. 2017 23:49 schreef "Escope12" <notifications@github.com>:

**Comment by Escope12** [comment]
What program would I need to do this?

**Comment by Alvarezmd90** [comment]
Photoshop cs6 will do fine. I can send you the needed files tomorrow if
you'd like. You don't use Unity?

Op 13 dec. 2017 23:51 schreef "Escope12" <notifications@github.com>:

**Comment by Escope12** [comment]
@Alvarezmd90 Sure. That could work.

**Comment by Alvarezmd90** [comment]
http://www.mediafire.com/file/2k6sacn0jdx2ptf/Textures.7z

You know I can't upload the rest.. But these are all textures, at least. xD
No need to fiddle around with Rachel's eye UVW map. As it is set to be perfect for the current texture. You can scale the pupil yourself within the texture to control dilation. (The bigger the pupils, the more attractive Rachel looks) Speaking of pupils, try to get the reflection to NOT obscure them. If they do, it tends to look weird. Here's how she looks in Unity:

http://www.mediafire.com/convkey/a9ee/03bhrdj48irgy6czg.jpg

**Comment by Escope12** [comment]
Can I merge these textures? @Alvarezmd90

**Comment by Alvarezmd90** [comment]
It seems obvious you don't know what to do so, here's an example:
http://www.mediafire.com/convkey/7618/0m3jls28vb6cvyczg.jpg

**Comment by Escope12** [comment]
@Alvarezmd90 Do you have a tutorial?

**Comment by Escope12** [comment]
@Alvarezmd90 http://www.mediafire.com/file/v2jle784g6qz5jx/TX_Eye_Sclera_D.psd

**Comment by Escope12** [comment]
![tx_eye_iris_blue_bloody_d](https://user-images.githubusercontent.com/8963276/34076190-56e0f5be-e2ac-11e7-9f47-0c03b76f7975.png)
![tx_eye_iris_blue_d](https://user-images.githubusercontent.com/8963276/34076191-56ecf12a-e2ac-11e7-80b9-7401e29ad5b9.png)
![tx_eye_iris_dkbrown_d](https://user-images.githubusercontent.com/8963276/34076192-57017320-e2ac-11e7-8c94-48d23ddea2ff.png)
![tx_eye_iris_green_d](https://user-images.githubusercontent.com/8963276/34076193-570cf88a-e2ac-11e7-9beb-adeeea46deb2.png)
![tx_eye_iris_hazel_d](https://user-images.githubusercontent.com/8963276/34076194-57191002-e2ac-11e7-943c-2626e3319d75.png)
![tx_eye_iris_ltbrown_d](https://user-images.githubusercontent.com/8963276/34076195-57226828-e2ac-11e7-83ba-3b5823b644be.png)
![tx_eye_sclera_d](https://user-images.githubusercontent.com/8963276/34076196-572f68c0-e2ac-11e7-8023-c9525d40a9ee.png)
![tx_eye_scleracry_d](https://user-images.githubusercontent.com/8963276/34076197-573b31be-e2ac-11e7-8273-9261ab5fa22e.png)
Here are all the eye textures from Life is Strange Before the Storm.

**Comment by Escope12** [comment]
@Alvarezmd90 Do you mind recreating that eye effect with each Eye Texture as a PSD for each Iris color with these textures I extracted with Life is Strange Before the Storm?
[Life is Strange Before the Storm Eye Textures.zip](https://github.com/Perfare/UnityStudio/files/1574291/Life.is.Strange.Before.the.Storm.Eye.Textures.zip)

**Comment by Escope12** [comment]
I bought the Eye Advanced Shader. @Alvarezmd90
